<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brian B. Avants">
<meta name="author" content="Nicholas J. Tustison">
<meta name="author" content="James R. Stone">

<title>3&nbsp; Experiments</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04_discussion.html" rel="next">
<link href="./02_methods.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./03_experiments.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Experiments</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro_background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction and Background</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_experiments.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_discussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Discussion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_brca_clinical_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Multi-omics Clinical Validation (TCGA-BRCA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_operational.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_flow_simr_v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Normalizing Flow SiMR with Linear Encoder Bottleneck (Flow-SiMR-V)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#reproducibility-protocol-and-experimental-setup" id="toc-reproducibility-protocol-and-experimental-setup" class="nav-link active" data-scroll-target="#reproducibility-protocol-and-experimental-setup"><span class="header-section-number">3.1</span> Reproducibility Protocol and Experimental Setup</a>
  <ul class="collapse">
  <li><a href="#data-regimes-and-replication-structure" id="toc-data-regimes-and-replication-structure" class="nav-link" data-scroll-target="#data-regimes-and-replication-structure"><span class="header-section-number">3.1.1</span> Data Regimes and Replication Structure</a></li>
  <li><a href="#interpretation-of-generative-regimes" id="toc-interpretation-of-generative-regimes" class="nav-link" data-scroll-target="#interpretation-of-generative-regimes"><span class="header-section-number">3.1.2</span> Interpretation of Generative Regimes</a></li>
  </ul></li>
  <li><a href="#rigorous-statistical-review-multi-classifier-demšar-benchmark" id="toc-rigorous-statistical-review-multi-classifier-demšar-benchmark" class="nav-link" data-scroll-target="#rigorous-statistical-review-multi-classifier-demšar-benchmark"><span class="header-section-number">3.2</span> Rigorous Statistical Review: Multi-Classifier Demšar Benchmark</a></li>
  <li><a href="#multi-objective-pareto-frontier-analysis" id="toc-multi-objective-pareto-frontier-analysis" class="nav-link" data-scroll-target="#multi-objective-pareto-frontier-analysis"><span class="header-section-number">3.3</span> Multi-Objective Pareto Frontier Analysis</a></li>
  <li><a href="#ground-truth-latent-discovery-across-generative-regimes" id="toc-ground-truth-latent-discovery-across-generative-regimes" class="nav-link" data-scroll-target="#ground-truth-latent-discovery-across-generative-regimes"><span class="header-section-number">3.4</span> Ground-Truth Latent Discovery across Generative Regimes</a></li>
  <li><a href="#precision-clinical-audit-trails-structural-xai-vs.-post-hoc-methods" id="toc-precision-clinical-audit-trails-structural-xai-vs.-post-hoc-methods" class="nav-link" data-scroll-target="#precision-clinical-audit-trails-structural-xai-vs.-post-hoc-methods"><span class="header-section-number">3.5</span> Precision Clinical Audit Trails: Structural XAI vs.&nbsp;Post-Hoc Methods</a>
  <ul class="collapse">
  <li><a href="#diabetes-progression-audit" id="toc-diabetes-progression-audit" class="nav-link" data-scroll-target="#diabetes-progression-audit"><span class="header-section-number">3.5.1</span> Diabetes Progression Audit</a></li>
  <li><a href="#heart-disease-audit" id="toc-heart-disease-audit" class="nav-link" data-scroll-target="#heart-disease-audit"><span class="header-section-number">3.5.2</span> Heart Disease Audit</a></li>
  <li><a href="#interpretability-of-the-nsa-layer-learned-mathbfv-matrices" id="toc-interpretability-of-the-nsa-layer-learned-mathbfv-matrices" class="nav-link" data-scroll-target="#interpretability-of-the-nsa-layer-learned-mathbfv-matrices"><span class="header-section-number">3.5.3</span> Interpretability of the NSA Layer (Learned <span class="math inline">\(\mathbf{V}\)</span> Matrices)</a></li>
  <li><a href="#topological-regularization-loo-vs.-star-consensus-pathways" id="toc-topological-regularization-loo-vs.-star-consensus-pathways" class="nav-link" data-scroll-target="#topological-regularization-loo-vs.-star-consensus-pathways"><span class="header-section-number">3.5.4</span> Topological Regularization: LOO vs.&nbsp;STAR Consensus Pathways</a></li>
  </ul></li>
  <li><a href="#complexity-and-scaling-benchmarks" id="toc-complexity-and-scaling-benchmarks" class="nav-link" data-scroll-target="#complexity-and-scaling-benchmarks"><span class="header-section-number">3.6</span> Complexity and Scaling Benchmarks</a></li>
  <li><a href="#flow-simr-v-gating-stability-and-clinical-robustness" id="toc-flow-simr-v-gating-stability-and-clinical-robustness" class="nav-link" data-scroll-target="#flow-simr-v-gating-stability-and-clinical-robustness"><span class="header-section-number">3.7</span> Flow-SiMR-V Gating Stability and Clinical Robustness</a>
  <ul class="collapse">
  <li><a href="#mixed-non-linear-sinusoidal-benchmark" id="toc-mixed-non-linear-sinusoidal-benchmark" class="nav-link" data-scroll-target="#mixed-non-linear-sinusoidal-benchmark"><span class="header-section-number">3.7.1</span> Mixed Non-linear Sinusoidal Benchmark</a></li>
  <li><a href="#brca-clinical-multi-omics-evaluation" id="toc-brca-clinical-multi-omics-evaluation" class="nav-link" data-scroll-target="#brca-clinical-multi-omics-evaluation"><span class="header-section-number">3.7.2</span> BRCA Clinical Multi-omics Evaluation</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Experiments</span></h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Brian B. Avants </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Virginia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Nicholas J. Tustison </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Virginia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">James R. Stone </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Virginia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="reproducibility-protocol-and-experimental-setup" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="reproducibility-protocol-and-experimental-setup"><span class="header-section-number">3.1</span> Reproducibility Protocol and Experimental Setup</h2>
<section id="data-regimes-and-replication-structure" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="data-regimes-and-replication-structure"><span class="header-section-number">3.1.1</span> Data Regimes and Replication Structure</h3>
<p>To evaluate the multi-modal architectures rigorously, we conduct a comprehensive benchmark encompassing 70 independent task blocks (comprising 490 complete evaluations). The evaluation spans seven distinct data regimes covering synthetic generative manifolds, clinical tabular cohorts, and high-dimensional multi-omics data:</p>
<ol type="1">
<li><strong>Synthetic Generative Manifolds (Controlled Signal Recovery):</strong>
<ul>
<li><code>Linear</code>: Ground-truth linear factor generator (<span class="math inline">\(\mathbf{X}_m = \mathbf{U}^* \mathbf{V}_m^T + \mathbf{E}_m\)</span>).</li>
<li><code>Polynomial</code>: Non-linear quadratic and cubic interaction manifold (<span class="math inline">\(\mathbf{X}_m = 0.5(\mathbf{U}^*)^2 + 0.3(\mathbf{U}^*)^3 + \mathbf{E}_m\)</span>).</li>
<li><code>Sine</code>: Strongly non-linear periodic manifold (<span class="math inline">\(\mathbf{X}_m = \sin(\pi \mathbf{U}^*) + \mathbf{E}_m\)</span>).</li>
<li><code>Shared+Private</code>: Structured shared latent consensus <span class="math inline">\(\mathbf{U}_{\text{shared}}^*\)</span> overlaid with orthogonal view-specific private noise <span class="math inline">\(\mathbf{U}_{\text{private}}^*\)</span>.</li>
<li><strong>Objectives:</strong> Exact quantification of ground-truth latent recovery (Canonical Mean Correlation <span class="math inline">\(CMC\)</span> on <span class="math inline">\(\mathbf{U}\)</span>) and feature basis discovery (Procrustes <span class="math inline">\(R^2\)</span> on <span class="math inline">\(\mathbf{V}\)</span>).</li>
</ul></li>
<li><strong>Heart Disease (Clinical Tabular Classification):</strong>
<ul>
<li>Cleveland Heart Disease cohort (<span class="math inline">\(N=303\)</span>, 2 views: <span class="math inline">\(p_1=7, p_2=6\)</span>) <span class="citation" data-cites="detrano1989international">(<a href="#ref-detrano1989international" role="doc-biblioref">Detrano et al. 1989</a>)</span>.</li>
<li><strong>Prediction Target:</strong> Binary diagnostic classification of coronary artery disease presence.</li>
</ul></li>
<li><strong>Diabetes Progression (Clinical Continuous Regression):</strong>
<ul>
<li>Efron clinical cohort (<span class="math inline">\(N=442\)</span>, 2 views: vitals <span class="math inline">\(p_1=5\)</span>, blood serums <span class="math inline">\(p_2=5\)</span>) <span class="citation" data-cites="efron2004least">(<a href="#ref-efron2004least" role="doc-biblioref">Efron et al. 2004</a>)</span>.</li>
<li><strong>Prediction Target:</strong> Quantitative measure of disease progression one year post-baseline.</li>
</ul></li>
<li><strong>Multi-Omics Cohort (High-Dimensional Biological Discovery):</strong>
<ul>
<li>Simulated 3-view biological cohort (<span class="math inline">\(N=400\)</span>, mRNA <span class="math inline">\(p_1=60\)</span>, CNV <span class="math inline">\(p_2=40\)</span>, Proteomics <span class="math inline">\(p_3=30\)</span>, <span class="math inline">\(k=3\)</span> known ground-truth latents) patterned after TCGA breast invasive carcinoma (BRCA) <span class="citation" data-cites="tcga2012breast cancerdiscovery2016esr1">(<a href="#ref-tcga2012breast" role="doc-biblioref">The Cancer Genome Atlas Network 2012</a>; <a href="#ref-cancerdiscovery2016esr1" role="doc-biblioref">Cancer Discovery 2016</a>)</span>.</li>
<li><strong>Prediction Target:</strong> Multi-view phenotypic status and ground-truth latent recovery.</li>
</ul></li>
</ol>
<p>Inference is conducted strictly at the level of the independent replicate (<span class="math inline">\(N_{\text{seeds}} = 10\)</span> independent random seeds: <span class="math inline">\([42, 43, 44, 45, 46, 47, 48, 49, 50, 51]\)</span>). All 490 evaluations are cached in <code>paper/results_cache/deep_ranking_benchmark.csv</code> and analyzed through a unified statistical inference engine (<code>src/pysimlr/benchmarks/deep_ranking.py</code>).</p>
</section>
<section id="interpretation-of-generative-regimes" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="interpretation-of-generative-regimes"><span class="header-section-number">3.1.2</span> Interpretation of Generative Regimes</h3>
<div id="cell-fig-generative-shapes" class="cell" data-message="false" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-generative-shapes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-generative-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_experiments_files/figure-html/fig-generative-shapes-output-1.png" width="1528" height="374" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-generative-shapes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.1: The Generative Landscape. Visualization of the mapping from a 1D latent coordinate <span class="math inline">\(\mathbf{U}\)</span> to observable features <span class="math inline">\(\mathbf{X}\)</span>. Baseline (Linear) demonstrates pure proportionality (A). Non-linear regimes (B-Polynomial, C-Sine) test higher-order and periodic interactions. Proposed private noise mapping (D) tests robustness to view-specific interference.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-generative-shapes" class="quarto-xref">Figure&nbsp;<span>3.1</span></a> illustrates the synthetic mapping from the 1D latent coordinate <span class="math inline">\(\mathbf{U}\)</span> to observable features <span class="math inline">\(\mathbf{X}\)</span>. The progression from pure linearity (A) to higher-order polynomials (B), periodicity (C), and structured private interference (D) benchmarks whether deep architectures extract the invariant linear subspace without succumbing to representation collapse.</p>
</section>
</section>
<section id="rigorous-statistical-review-multi-classifier-demšar-benchmark" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="rigorous-statistical-review-multi-classifier-demšar-benchmark"><span class="header-section-number">3.2</span> Rigorous Statistical Review: Multi-Classifier Demšar Benchmark</h2>
<p>To establish a definitive empirical ranking, we evaluate seven architectures across all 70 independent task blocks (<span class="math inline">\(7 \text{ data regimes} \times 10 \text{ random seeds} = 490\)</span> runs). Following <span class="citation" data-cites="Demsar2006">Demšar (<a href="#ref-Demsar2006" role="doc-biblioref">2006</a>)</span>, we eschew pooled parametric analysis of variance across heterogeneous task distributions, relying instead on non-parametric omnibus tests, critical difference thresholds, and exact distribution-free sign-flip permutations.</p>
<p>With 10 independent seeds per task block, the exact distribution-free sign-flip permutation resolution floor is: <span class="math display">\[
\frac{2}{2^{10}} = \frac{2}{1024} \approx 0.001953
\]</span> We eliminate unadjusted pooled <span class="math inline">\(p\)</span>-values, which historically inflated degrees of freedom across repeated measures on the same data split <span class="citation" data-cites="benavoli2016should">(<a href="#ref-benavoli2016should" role="doc-biblioref">Benavoli et al. 2016</a>)</span>.</p>
<p>Across all 70 paired blocks, the non-parametric Friedman test reveals highly significant architectural divergence: <span class="math display">\[
\chi_F^2 = 69.39, \quad p = 5.44 \times 10^{-13}
\]</span> The Iman-Davenport extension further confirms this separation: <span class="math display">\[
F_F = 13.66, \quad p = 3.63 \times 10^{-14} \quad (\text{df}_1 = 6, \text{df}_2 = 414)
\]</span> At <span class="math inline">\(\alpha = 0.05\)</span>, the two-tailed Nemenyi Critical Difference is <span class="math inline">\(CD = 1.077\)</span> rank units.</p>
<div id="tbl-deep-ranking-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-message="false" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-deep-ranking-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.1: Global Deep Ranking Benchmark Summary across 70 independent task blocks (7 datasets x 10 seeds). Mean ranks derived from non-parametric Friedman test (<span class="math inline">\(\chi_F^2 = 69.39, p = 5.44 \times 10^{-13}\)</span>). Critical difference <span class="math inline">\(CD = 1.077\)</span> at <span class="math inline">\(\alpha = 0.05\)</span>. Pareto status computed across predictive accuracy, frame defect, and fit time.
</figcaption>
<div aria-describedby="tbl-deep-ranking-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 4%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 6%">
<col style="width: 11%">
<col style="width: 6%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Architecture</th>
<th style="text-align: right;">Mean Rank</th>
<th style="text-align: left;">Predictive (Mean ± SD)</th>
<th style="text-align: right;">Peak</th>
<th style="text-align: right;">Strictly Linear (XV)</th>
<th style="text-align: right;">Axis Sensitive (RF)</th>
<th style="text-align: right;">CMC (U)</th>
<th style="text-align: right;">Frame Defect (D)</th>
<th style="text-align: left;">Fit Time</th>
<th style="text-align: left;">Pareto Frontier</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Flow-SiMLR-V</td>
<td style="text-align: right;">2.47</td>
<td style="text-align: left;">0.631 ± 0.278</td>
<td style="text-align: right;">0.963</td>
<td style="text-align: right;">0.675</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.684</td>
<td style="text-align: right;">0.259</td>
<td style="text-align: left;">4.13s</td>
<td style="text-align: left;">Pareto Optimal</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEND</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: left;">0.567 ± 0.284</td>
<td style="text-align: right;">0.951</td>
<td style="text-align: right;">0.675</td>
<td style="text-align: right;">0.648</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.05</td>
<td style="text-align: left;">1.65s</td>
<td style="text-align: left;">Dominated</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SiMLR-LBFGS</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: left;">0.572 ± 0.302</td>
<td style="text-align: right;">0.961</td>
<td style="text-align: right;">0.67</td>
<td style="text-align: right;">0.645</td>
<td style="text-align: right;">0.64</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: left;">1.50s</td>
<td style="text-align: left;">Pareto Optimal</td>
</tr>
<tr class="even">
<td style="text-align: left;">SiMLR</td>
<td style="text-align: right;">3.71</td>
<td style="text-align: left;">0.546 ± 0.293</td>
<td style="text-align: right;">0.931</td>
<td style="text-align: right;">0.667</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.612</td>
<td style="text-align: right;">0.029</td>
<td style="text-align: left;">0.11s</td>
<td style="text-align: left;">Pareto Optimal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NED</td>
<td style="text-align: right;">4.68</td>
<td style="text-align: left;">0.539 ± 0.263</td>
<td style="text-align: right;">0.858</td>
<td style="text-align: right;">0.675</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.645</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;">2.05s</td>
<td style="text-align: left;">Dominated</td>
</tr>
<tr class="even">
<td style="text-align: left;">NEDPP</td>
<td style="text-align: right;">4.69</td>
<td style="text-align: left;">0.541 ± 0.267</td>
<td style="text-align: right;">0.868</td>
<td style="text-align: right;">0.676</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.646</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: left;">2.38s</td>
<td style="text-align: left;">Dominated</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NSAFlow-Turnkey</td>
<td style="text-align: right;">5.04</td>
<td style="text-align: left;">-0.452 ± 1.332</td>
<td style="text-align: right;">0.821</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">0.624</td>
<td style="text-align: right;">0.713</td>
<td style="text-align: right;">1.047</td>
<td style="text-align: left;">4.64s</td>
<td style="text-align: left;">Pareto Optimal</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>As detailed in <a href="#tbl-deep-ranking-summary" class="quarto-xref">Table&nbsp;<span>3.1</span></a> and <a href="#fig-cd-diagram" class="quarto-xref">Figure&nbsp;<span>3.2</span></a>: 1. <strong>Flow-SiMLR-V</strong> is the global top performer, achieving a mean rank of <strong>2.47</strong> across all 70 tasks. The distance to the next-ranked architectures (LEND and SiMLR-LBFGS at 3.70) is <span class="math inline">\(\Delta R = 1.23 &gt; CD (1.077)\)</span>, establishing that Flow-SiMLR-V forms an <strong>isolated, statistically dominant clique</strong>. 2. <strong>SiMLR-LBFGS</strong> bridges the linear-to-deep gap. Achieving a mean rank of <strong>3.70</strong>, it matches the hybrid deep model LEND while statistically significantly outperforming pure deep architectures NED (<span class="math inline">\(p=0.0148\)</span>) and NEDPP (<span class="math inline">\(p=0.0274\)</span>). 3. <strong>Linear-to-Deep Parity</strong>: Across all models, Strictly Linear prediction on <span class="math inline">\(\mathbf{X}\mathbf{V}\)</span> (<span class="math inline">\(0.675\)</span> for Flow-SiMLR-V) matches or exceeds coordinate-sensitive Random Forest probes (<span class="math inline">\(0.647\)</span>), validating that the Only Linear Encoder Entrypoint (OLEE) extracts the invariant feature subspace without suffering a “transparency penalty”.</p>
<div id="cell-fig-cd-diagram" class="cell" data-message="false" data-execution_count="3">
<div class="cell-output cell-output-display">
<div id="fig-cd-diagram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cd-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_experiments_files/figure-html/fig-cd-diagram-output-1.png" width="2820" height="930" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cd-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.2: Demšar (2006) Critical Difference Diagram across 70 independent paired task blocks (<span class="math inline">\(\alpha=0.05, CD=1.077\)</span>). Flow-SiMLR-V forms an isolated top-performing statistical clique. The horizontal bar connects architectures whose mean ranks do not differ significantly. Green points denote Pareto-optimal models.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="tbl-deep-pairwise" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-message="false" data-execution_count="4">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-deep-pairwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.2: Pairwise Non-Parametric Significance Tests. Wilcoxon signed-rank tests with Holm-Bonferroni correction and exact sign-flip permutation tests across 70 independent task blocks. All tests respect the replication structure; permutation resolution floor is <span class="math inline">\(2/2^{10} \approx 0.00195\)</span>.
</figcaption>
<div aria-describedby="tbl-deep-pairwise-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 29%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Comparison (A vs B)</th>
<th style="text-align: right;">Mean Difference</th>
<th style="text-align: right;">Wilcoxon-Holm p</th>
<th style="text-align: right;">Exact Permutation p</th>
<th style="text-align: left;">Significant?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Flow-SiMLR-V vs LEND</td>
<td style="text-align: right;">0.0642</td>
<td style="text-align: right;">0.00014913</td>
<td style="text-align: right;">5e-06</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flow-SiMLR-V vs NED</td>
<td style="text-align: right;">0.0919</td>
<td style="text-align: right;">1.0065e-08</td>
<td style="text-align: right;">5e-06</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flow-SiMLR-V vs NEDPP</td>
<td style="text-align: right;">0.0906</td>
<td style="text-align: right;">7.9311e-09</td>
<td style="text-align: right;">5e-06</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flow-SiMLR-V vs SiMLR</td>
<td style="text-align: right;">0.0855</td>
<td style="text-align: right;">0.00026126</td>
<td style="text-align: right;">5e-06</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Flow-SiMLR-V vs SiMLR-LBFGS</td>
<td style="text-align: right;">0.0592</td>
<td style="text-align: right;">0.0029777</td>
<td style="text-align: right;">7e-05</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Flow-SiMLR-V vs NSAFlow-Turnkey</td>
<td style="text-align: right;">1.0833</td>
<td style="text-align: right;">7.3228e-08</td>
<td style="text-align: right;">5e-06</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SiMLR-LBFGS vs NED</td>
<td style="text-align: right;">0.0327</td>
<td style="text-align: right;">0.014839</td>
<td style="text-align: right;">0.167504</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="even">
<td style="text-align: left;">SiMLR-LBFGS vs NEDPP</td>
<td style="text-align: right;">0.0314</td>
<td style="text-align: right;">0.027389</td>
<td style="text-align: right;">0.134319</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SiMLR-LBFGS vs SiMLR</td>
<td style="text-align: right;">0.0263</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.079545</td>
<td style="text-align: left;">Trend (p &lt; 0.10)</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEND vs NED</td>
<td style="text-align: right;">0.0277</td>
<td style="text-align: right;">0.02181</td>
<td style="text-align: right;">0.202699</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEND vs NEDPP</td>
<td style="text-align: right;">0.0264</td>
<td style="text-align: right;">0.042397</td>
<td style="text-align: right;">0.165294</td>
<td style="text-align: left;">Yes (p &lt; 0.05)</td>
</tr>
<tr class="even">
<td style="text-align: left;">LEND vs SiMLR-LBFGS</td>
<td style="text-align: right;">-0.005</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.769971</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="multi-objective-pareto-frontier-analysis" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="multi-objective-pareto-frontier-analysis"><span class="header-section-number">3.3</span> Multi-Objective Pareto Frontier Analysis</h2>
<p>Architectural selection across clinical and high-dimensional biomedical regimes cannot be reduced to a 1D predictive metric. In high-stakes applications, models must be evaluated against four fundamental axes: 1. <strong>Downstream Predictive Capacity (<span class="math inline">\(Y\)</span>)</strong>: Out-of-sample <span class="math inline">\(R^2\)</span> or diagnostic accuracy. 2. <strong>Ground-Truth Latent Discovery (<span class="math inline">\(CMC\)</span>)</strong>: Canonical Mean Correlation with known generative latents. 3. <strong>Mathematical Invariant Guarantees</strong>: Stiefel frame defect <span class="math inline">\(D = \|\mathbf{V}^T \mathbf{V} - \mathbf{I}\|_F^2\)</span> and lobe crosstalk <span class="math inline">\(\mathbf{V}^+ \odot \mathbf{V}^- = \mathbf{0}\)</span>. 4. <strong>Computational Throughput</strong>: Wall-clock training latency.</p>
<div id="cell-fig-pareto-frontier" class="cell" data-message="false" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="fig-pareto-frontier" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pareto-frontier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_experiments_files/figure-html/fig-pareto-frontier-output-1.png" width="3862" height="1469" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pareto-frontier-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.3: Multi-Objective Pareto Analysis across 70 Paired Blocks. (A) Empirical Predictive Accuracy vs.&nbsp;Training Latency. The Pareto envelope connects SiMLR (fastest), SiMLR-LBFGS (hybrid), and Flow-SiMLR-V (highest accuracy). (B) Ground-Truth Latent Recovery (CMC on <span class="math inline">\(\mathbf{U}\)</span>) vs.&nbsp;Frame Defect (<span class="math inline">\(D\)</span>). NSAFlow-Turnkey anchors the discovery frontier with near-perfect latent identifiability.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="ground-truth-latent-discovery-across-generative-regimes" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="ground-truth-latent-discovery-across-generative-regimes"><span class="header-section-number">3.4</span> Ground-Truth Latent Discovery across Generative Regimes</h2>
<p>To test identifiability directly, we evaluate latent recovery where mathematical ground-truth <span class="math inline">\((\mathbf{U}^*, \mathbf{V}^*)\)</span> is known: the 4 synthetic generative regimes (Linear, Polynomial, Sine, Shared+Private) and the 3-view Multi-Omics biological cohort.</p>
<div id="cell-fig-cmc-recovery" class="cell" data-message="false" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-cmc-recovery" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cmc-recovery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_experiments_files/figure-html/fig-cmc-recovery-output-1.png" width="2961" height="1409" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cmc-recovery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.4: Ground-Truth Latent Coordinate Recovery (Canonical Mean Correlation on <span class="math inline">\(\mathbf{U}\)</span>). Across all regimes with defined latent generators (4 synthetic + 3-View Multi-Omics), NSAFlow-Turnkey and Flow-SiMLR-V demonstrate leading alignment with the true underlying manifold coordinates.
</figcaption>
</figure>
</div>
</div>
</div>
<p>As demonstrated in <a href="#fig-cmc-recovery" class="quarto-xref">Figure&nbsp;<span>3.4</span></a>: - On <strong>3-View Multi-Omics</strong>, <strong>NSAFlow-Turnkey</strong> achieves near-perfect latent recovery (<strong>CMC = 0.9880</strong>), closely followed by <strong>Flow-SiMLR-V</strong> (<strong>CMC = 0.9274</strong>) and <strong>SiMLR-LBFGS</strong> (<strong>CMC = 0.8933</strong>). Standard SiMLR attains <span class="math inline">\(0.7823\)</span>. - On <strong>Linear</strong> generative manifolds, <strong>NSAFlow-Turnkey</strong> leads all architectures with <strong>CMC = 0.8484</strong> (vs <span class="math inline">\(0.6799\)</span> for baseline SiMLR). - On the <strong>Shared+Private</strong> manifold, <strong>Flow-SiMLR-V</strong> achieves the highest recovery (<strong>CMC = 0.7137</strong>), proving that bijective normalizing flows filter out view-specific private noise without suffering the numerical degradation seen in explicit cross-covariance penalties (NEDPP). - <strong>Invariant Guarantees</strong>: Lobe crosstalk (<span class="math inline">\(\mathbf{V}^+ \odot \mathbf{V}^- = \mathbf{0}\)</span>) is exactly <span class="math inline">\(0.0000\)</span> across all 490 runs. Frame defect <span class="math inline">\(D = \|\mathbf{V}^T \mathbf{V} - \mathbf{I}\|_F^2\)</span> is bounded near zero for SiMLR-LBFGS (<span class="math inline">\(0.0204\)</span>) and exactly <span class="math inline">\(0.0000\)</span> on Cleveland Heart and Diabetes.</p>
</section>
<section id="precision-clinical-audit-trails-structural-xai-vs.-post-hoc-methods" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="precision-clinical-audit-trails-structural-xai-vs.-post-hoc-methods"><span class="header-section-number">3.5</span> Precision Clinical Audit Trails: Structural XAI vs.&nbsp;Post-Hoc Methods</h2>
<p>The <strong>NED</strong> and <strong>LEND</strong> architectures provide direct pathways for structural explainability. By restricting the initial mapping to an orthogonal linear projection, the architecture guarantees zero approximation error when mapping latent consensus coordinates back to input features.</p>
<section id="diabetes-progression-audit" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="diabetes-progression-audit"><span class="header-section-number">3.5.1</span> Diabetes Progression Audit</h3>
<p>To bridge the gap between global importance and individual patient care, we utilize the linear basis to generate local audit trails. <a href="#fig-diabetes-audit" class="quarto-xref">Figure&nbsp;<span>3.5</span></a> decomposes the latent signal for Patient #1 into constituent feature impacts. The model identifies BMI and serum triglycerides (S5) as the primary positive drivers.</p>
<div id="cell-fig-diabetes-audit" class="cell" data-message="false" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="fig-diabetes-audit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diabetes-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_experiments_files/figure-html/fig-diabetes-audit-output-1.png" width="798" height="525" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diabetes-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.5: Localized Feature Impact Analysis (Diabetes). Baseline (Post-hoc SHAP) vs.&nbsp;Proposed (Exact Structural XAI). Local feature attribution derived directly from the first-layer linear basis with zero approximation error <span class="citation" data-cites="Lundberg_2017 Smith2023posthoc">(<a href="#ref-Lundberg_2017" role="doc-biblioref">Lundberg and Lee 2017</a>; <a href="#ref-Smith2023posthoc" role="doc-biblioref">Radulovic 2023</a>)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="heart-disease-audit" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="heart-disease-audit"><span class="header-section-number">3.5.2</span> Heart Disease Audit</h3>
<p>We apply the local audit protocol to the Heart Disease dataset. <a href="#fig-heart-audit" class="quarto-xref">Figure&nbsp;<span>3.6</span></a> highlights ‘thalach’ (maximum heart rate) and ‘cp’ (chest pain type) as dominant factors for a high-risk individual.</p>
<div id="fig-heart-audit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heart-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/heart_waterfall.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heart-audit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.6: Individualized Cardiovascular Audit. Baseline (Black box classification) vs.&nbsp;Proposed (Auditable Linear Attribution). Local feature attribution for a high-risk patient. The audit reveals the exact additive contribution of clinical features (thalach, cp) to the latent risk factor, establishing clinical trust.
</figcaption>
</figure>
</div>
</section>
<section id="interpretability-of-the-nsa-layer-learned-mathbfv-matrices" class="level3" data-number="3.5.3">
<h3 data-number="3.5.3" class="anchored" data-anchor-id="interpretability-of-the-nsa-layer-learned-mathbfv-matrices"><span class="header-section-number">3.5.3</span> Interpretability of the NSA Layer (Learned <span class="math inline">\(\mathbf{V}\)</span> Matrices)</h3>
<p>The learned <span class="math inline">\(\mathbf{V}\)</span> matrices map feature contributions directly to the latent consensus space. We visualize these weights using importance heatmaps in <a href="#fig-nsa-v-interpretability" class="quarto-xref">Figure&nbsp;<span>3.7</span></a>.</p>
<div id="fig-nsa-v-interpretability" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nsa-v-interpretability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/nsa_v_interpretability.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nsa-v-interpretability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.7: Interpretability of Learned NSA Layer Weights. Baseline (Black Box Importance) vs.&nbsp;Proposed (Exact <span class="math inline">\(\mathbf{V}\)</span> Matrix Weights). Heatmaps of learned <span class="math inline">\(\mathbf{V}\)</span> matrices for Heart Disease and Diabetes datasets. The visualization provides exact magnitude and direction of feature contributions, demonstrating strict global interpretability.
</figcaption>
</figure>
</div>
</section>
<section id="topological-regularization-loo-vs.-star-consensus-pathways" class="level3" data-number="3.5.4">
<h3 data-number="3.5.4" class="anchored" data-anchor-id="topological-regularization-loo-vs.-star-consensus-pathways"><span class="header-section-number">3.5.4</span> Topological Regularization: LOO vs.&nbsp;STAR Consensus Pathways</h3>
<p>To evaluate architectural constraints, we compare the baseline <strong>Star topology</strong> with the proposed strict <strong>Leave-One-Out (LOO) topology</strong>. In Star topology, modality <span class="math inline">\(m\)</span> aligns to a consensus <span class="math inline">\(\mathbf{U}\)</span> that includes its own information. In LOO topology, modality <span class="math inline">\(m\)</span> aligns against a consensus <span class="math inline">\(\mathbf{U}_{\neq m}\)</span> built exclusively from other modalities.</p>
<div id="fig-v21-loo-vs-star" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v21-loo-vs-star-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_v21_loo_vs_star.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v21-loo-vs-star-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.8: Topological Regularization Benefit. Baseline (Star Topology) vs.&nbsp;Proposed (LOO Topology). Strictly Linear Accuracy on the Diabetes dataset. The LOO topology acts as a regularizer for high-capacity models, forcing the discovery of robust shared features rather than memorizing modality-specific noise.
</figcaption>
</figure>
</div>
<div id="fig-v21-loo-vs-star-gap" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-v21-loo-vs-star-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/fig_v21_loo_vs_star_gap.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-v21-loo-vs-star-gap-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.9: Generalization Gap by Topology. Baseline (Star Topology) vs.&nbsp;Proposed (LOO Topology). Train-test accuracy gap. The LOO consensus pathway narrows the generalization gap for deep architectures, proving that strict cross-modal prediction prevents self-prediction leaks.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="complexity-and-scaling-benchmarks" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="complexity-and-scaling-benchmarks"><span class="header-section-number">3.6</span> Complexity and Scaling Benchmarks</h2>
<p>We analyze wall-time complexity as a function of sample size <span class="math inline">\(N\)</span> and latent dimension <span class="math inline">\(K\)</span>. <a href="#fig-scaling" class="quarto-xref">Figure&nbsp;<span>3.10</span></a> (Left) shows execution time scales linearly with <span class="math inline">\(N\)</span> (<span class="math inline">\(\mathcal{O}(N)\)</span>), confirming optimized deep forward and backward passes. <a href="#fig-scaling" class="quarto-xref">Figure&nbsp;<span>3.10</span></a> (Right) details non-linear growth concerning <span class="math inline">\(K\)</span>, specifically <span class="math inline">\(\mathcal{O}(K^3)\)</span> for the Newton-Schulz consensus. For typical biomedical ranks (<span class="math inline">\(K &lt; 100\)</span>), the overhead remains negligible.</p>
<div id="cell-fig-scaling" class="cell" data-message="false" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-scaling" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="03_experiments_files/figure-html/fig-scaling-output-1.png" width="1143" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3.10: Algorithmic Efficiency. Baseline (Linear Scaling) vs.&nbsp;Proposed (NSA Overhead). Execution Wall-time Scaling. (Left) Sample size <span class="math inline">\(N\)</span> scaling is linear. (Right) Latent dimension <span class="math inline">\(K\)</span> scaling reflects Newton-Schulz and covariance overhead (<span class="math inline">\(\mathcal{O}(K^3)\)</span>). The proposed architectures maintain scalable execution times for typical biomedical dataset dimensions.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="flow-simr-v-gating-stability-and-clinical-robustness" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="flow-simr-v-gating-stability-and-clinical-robustness"><span class="header-section-number">3.7</span> Flow-SiMR-V Gating Stability and Clinical Robustness</h2>
<p>We evaluate the Modality Alignment Index (MAI) dynamic weight gating on normalizing flow architectures under two challenging scenarios: a mixed non-linear synthetic benchmark containing a structured periodic signal and a completely random rogue noise view, and the TCGA-BRCA multi-omics classification task.</p>
<section id="mixed-non-linear-sinusoidal-benchmark" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="mixed-non-linear-sinusoidal-benchmark"><span class="header-section-number">3.7.1</span> Mixed Non-linear Sinusoidal Benchmark</h3>
<p>As shown in <a href="#tbl-mixed-synthetic-results" class="quarto-xref">Table&nbsp;<span>3.3</span></a>, purely static weights fail to suppress rogue noise, yielding a lower latent recovery (<span class="math inline">\(R^2 = 0.1288\)</span>). Activating MAI gating immediately (epoch 0) on Flow-SiMR-V causes weight collapse on the low-dimensional space. Implementing <strong>Delayed Gating Warmup</strong> (uniform weights for the first 60 epochs) allows the projection layers to stabilize. When gating is activated at epoch 60, the model successfully quarantines the rogue view (noise weight driven to absolute zero) and achieves stable consensus alignment (<span class="math inline">\(R^2 = 0.3073\)</span>), while the unconstrained Flow-SiMR model achieves <span class="math inline">\(R^2 = 0.8193\)</span>.</p>
<div id="tbl-mixed-synthetic-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-mixed-synthetic-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.3: Mixed Non-linear Synthetic Benchmark Results. Flow-SiMR-V with Delayed Gating achieves stable consensus recovery and successfully quarantines rogue noise views without suffering weight collapse.
</figcaption>
<div aria-describedby="tbl-mixed-synthetic-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model Configuration</th>
<th style="text-align: center;">Dynamic (MAI)?</th>
<th style="text-align: center;">Delayed Start?</th>
<th style="text-align: center;">Latent Recovery <span class="math inline">\(R^2\)</span></th>
<th style="text-align: left;">Modality Weights (<span class="math inline">\(V_1, V_2, V_3, \text{Rogue}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMR-V (Static)</strong></td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;"><span class="math inline">\(0.1288\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.250, 0.250, 0.250, 0.250]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Flow-SiMR-V (Immediate)</strong></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Epoch 0</td>
<td style="text-align: center;"><span class="math inline">\(0.7236\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.526, 0.001, 0.473, 0.000]\)</span> (Collapsed <span class="math inline">\(V_2\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMR-V (Delayed)</strong></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Epoch 60</td>
<td style="text-align: center;"><strong><span class="math inline">\(0.3073\)</span></strong></td>
<td style="text-align: left;"><span class="math inline">\([0.445, 0.149, 0.406, 0.000]\)</span> (Stable Gating)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Flow-SiMR (Static)</strong></td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;"><span class="math inline">\(0.8257\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.250, 0.250, 0.250, 0.250]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMR (Dynamic)</strong></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Epoch 0</td>
<td style="text-align: center;"><strong><span class="math inline">\(0.8193\)</span></strong></td>
<td style="text-align: left;"><span class="math inline">\([0.341, 0.306, 0.332, 0.021]\)</span> (Stable Gating)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="brca-clinical-multi-omics-evaluation" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="brca-clinical-multi-omics-evaluation"><span class="header-section-number">3.7.2</span> BRCA Clinical Multi-omics Evaluation</h3>
<p>We validate the stability of Flow-SiMR-V gating on the high-dimensional TCGA-BRCA multi-omics clinical dataset (<span class="math inline">\(N = 1010\)</span> samples). The views consist of RNA expression, copy number variations, protein expression, and an injected Gaussian noise view. We train models to learn a joint consensus representation, and predict patient Estrogen Receptor (ER) binary status using downstream logistic regression.</p>
<p>As shown in <a href="#tbl-brca-gating-results" class="quarto-xref">Table&nbsp;<span>3.4</span></a>, under <strong>Delayed Gating (warmup = 75 epochs)</strong>, Flow-SiMR-V achieves the highest downstream ER status prediction accuracy of <strong>87.27%</strong>, outperforming both the static baseline (79.09%) and unconstrained Flow-SiMR (74.55%) by successfully quarantining the noise modality (weight reduced to <span class="math inline">\(0.0593\)</span>) while maintaining representation capacity across all biological views.</p>
<div id="tbl-brca-gating-results" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-brca-gating-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3.4: BRCA Clinical Multi-omics Gating Results. Flow-SiMR-V with Delayed Gating achieves the highest classification accuracy by isolating genomic noise and balancing biological views.
</figcaption>
<div aria-describedby="tbl-brca-gating-results-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model Configuration</th>
<th style="text-align: center;">Dynamic (MAI)?</th>
<th style="text-align: center;">Delayed Start?</th>
<th style="text-align: center;">ER Status Accuracy</th>
<th style="text-align: left;">Modality Weights (<span class="math inline">\(\text{RNA}, \text{DNA}_{\text{CN}}, \text{Protein}, \text{Noise}\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMR-V (Static)</strong></td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;"><span class="math inline">\(79.09\%\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.2500, 0.2500, 0.2500, 0.2500]\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Flow-SiMR-V (Immediate)</strong></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Epoch 0</td>
<td style="text-align: center;"><span class="math inline">\(82.73\%\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.3640, 0.3288, 0.3042, 0.0029]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMR-V (Delayed)</strong></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Epoch 75</td>
<td style="text-align: center;"><strong><span class="math inline">\(87.27\%\)</span></strong></td>
<td style="text-align: left;"><span class="math inline">\([0.3353, 0.3364, 0.2690, 0.0593]\)</span> (Optimal Gating)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Flow-SiMR (Static)</strong></td>
<td style="text-align: center;">No</td>
<td style="text-align: center;">N/A</td>
<td style="text-align: center;"><span class="math inline">\(70.00\%\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.2500, 0.2500, 0.2500, 0.2500]\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMR (Dynamic)</strong></td>
<td style="text-align: center;">Yes</td>
<td style="text-align: center;">Epoch 0</td>
<td style="text-align: center;"><span class="math inline">\(74.55\%\)</span></td>
<td style="text-align: left;"><span class="math inline">\([0.3102, 0.2502, 0.3167, 0.1229]\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-benavoli2016should" class="csl-entry" role="listitem">
Benavoli, Alessio, Giorgio Corani, Janez Demšar, and Marco Zaffalon. 2016. <span>“Should We Really Use Post-Hoc Tests Based on Mean-Ranks?”</span> <em>Journal of Machine Learning Research</em> 17 (5): 1–10.
</div>
<div id="ref-cancerdiscovery2016esr1" class="csl-entry" role="listitem">
Cancer Discovery. 2016. <span>“Multiple Noncoding Mutations Regulate <span>ESR1</span> Expression in Breast Cancer.”</span> <em>Cancer Discovery</em> 6 (11): OF5–5. <a href="https://doi.org/10.1158/2159-8290.cd-rw2016-170">https://doi.org/10.1158/2159-8290.cd-rw2016-170</a>.
</div>
<div id="ref-Demsar2006" class="csl-entry" role="listitem">
Demšar, Janez. 2006. <span>“Statistical Comparisons of Classifiers over Multiple Data Sets.”</span> <em>Journal of Machine Learning Research</em> 7: 1–30.
</div>
<div id="ref-detrano1989international" class="csl-entry" role="listitem">
Detrano, Robert, Andras Janosi, William Steinbrunn, et al. 1989. <span>“International Application of a New Probability Algorithm for the Diagnosis of Coronary Artery Disease.”</span> <em>The American Journal of Cardiology</em> 64 (5): 304–10.
</div>
<div id="ref-efron2004least" class="csl-entry" role="listitem">
Efron, Bradley, Trevor Hastie, Iain Johnstone, and Robert Tibshirani. 2004. <span>“Least Angle Regression.”</span> <em>The Annals of Statistics</em> 32 (2): 407–99.
</div>
<div id="ref-Lundberg_2017" class="csl-entry" role="listitem">
Lundberg, Scott M, and Su-In Lee. 2017. <span>“A Unified Approach to Interpreting Model Predictions.”</span> <em>Advances in Neural Information Processing Systems</em> 30.
</div>
<div id="ref-Smith2023posthoc" class="csl-entry" role="listitem">
Radulovic, Nedeljko. 2023. <span>“Post-Hoc Explainable AI for Black Box Models on Tabular Data.”</span> PhD thesis, Institut Polytechnique de Paris. <a href="https://doi.org/10.70675/622ba75cz4386z48e4z934ez365c407c74d5">https://doi.org/10.70675/622ba75cz4386z48e4z934ez365c407c74d5</a>.
</div>
<div id="ref-tcga2012breast" class="csl-entry" role="listitem">
The Cancer Genome Atlas Network. 2012. <span>“Comprehensive Molecular Portraits of Human Breast Tumours.”</span> <em>Nature</em> 490 (7418): 61–70. <a href="https://doi.org/10.1038/nature11412">https://doi.org/10.1038/nature11412</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02_methods.html" class="pagination-link" aria-label="Methods">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Methods</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04_discussion.html" class="pagination-link" aria-label="Discussion">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Discussion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>