<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Brian B. Avants">
<meta name="author" content="Nicholas J. Tustison">
<meta name="author" content="James R. Stone">

<title>4&nbsp; Discussion</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./appendix_brca_clinical_validation.html" rel="next">
<link href="./03_experiments.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-5ccb035bea26c1e21f80f44cf7c27909.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04_discussion.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Discussion</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro_background.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction and Background</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Methods</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_experiments.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Experiments</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_discussion.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Discussion</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_brca_clinical_validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Multi-omics Clinical Validation (TCGA-BRCA)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_operational.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_flow_simr_v.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Normalizing Flow SiMR with Linear Encoder Bottleneck (Flow-SiMR-V)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./appendix_reproducibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#non-parametric-architectural-ranking-and-empirical-synthesis" id="toc-non-parametric-architectural-ranking-and-empirical-synthesis" class="nav-link active" data-scroll-target="#non-parametric-architectural-ranking-and-empirical-synthesis"><span class="header-section-number">4.1</span> Non-Parametric Architectural Ranking and Empirical Synthesis</a></li>
  <li><a href="#four-axis-multi-objective-pareto-frontier-analysis" id="toc-four-axis-multi-objective-pareto-frontier-analysis" class="nav-link" data-scroll-target="#four-axis-multi-objective-pareto-frontier-analysis"><span class="header-section-number">4.2</span> Four-Axis Multi-Objective Pareto Frontier Analysis</a>
  <ul class="collapse">
  <li><a href="#structure-of-the-pareto-non-dominated-set" id="toc-structure-of-the-pareto-non-dominated-set" class="nav-link" data-scroll-target="#structure-of-the-pareto-non-dominated-set"><span class="header-section-number">4.2.1</span> Structure of the Pareto Non-Dominated Set</a></li>
  </ul></li>
  <li><a href="#mechanistic-auditability-and-eliminating-the-transparency-penalty" id="toc-mechanistic-auditability-and-eliminating-the-transparency-penalty" class="nav-link" data-scroll-target="#mechanistic-auditability-and-eliminating-the-transparency-penalty"><span class="header-section-number">4.3</span> Mechanistic Auditability and Eliminating the Transparency Penalty</a></li>
  <li><a href="#normalizing-flows-bijective-volume-preservation-and-structural-filtering" id="toc-normalizing-flows-bijective-volume-preservation-and-structural-filtering" class="nav-link" data-scroll-target="#normalizing-flows-bijective-volume-preservation-and-structural-filtering"><span class="header-section-number">4.4</span> Normalizing Flows: Bijective Volume Preservation and Structural Filtering</a>
  <ul class="collapse">
  <li><a href="#geodesic-latent-path-trajectories" id="toc-geodesic-latent-path-trajectories" class="nav-link" data-scroll-target="#geodesic-latent-path-trajectories"><span class="header-section-number">4.4.1</span> Geodesic Latent Path Trajectories</a></li>
  </ul></li>
  <li><a href="#translational-implications-for-clinical-cohorts" id="toc-translational-implications-for-clinical-cohorts" class="nav-link" data-scroll-target="#translational-implications-for-clinical-cohorts"><span class="header-section-number">4.5</span> Translational Implications for Clinical Cohorts</a>
  <ul class="collapse">
  <li><a href="#neuroimaging-alzheimers-disease-neuroimaging-initiative-adni" id="toc-neuroimaging-alzheimers-disease-neuroimaging-initiative-adni" class="nav-link" data-scroll-target="#neuroimaging-alzheimers-disease-neuroimaging-initiative-adni"><span class="header-section-number">4.5.1</span> 1. Neuroimaging: Alzheimer’s Disease Neuroimaging Initiative (ADNI)</a></li>
  <li><a href="#neuroimaging-parkinsons-progression-markers-initiative-ppmi" id="toc-neuroimaging-parkinsons-progression-markers-initiative-ppmi" class="nav-link" data-scroll-target="#neuroimaging-parkinsons-progression-markers-initiative-ppmi"><span class="header-section-number">4.5.2</span> 2. Neuroimaging: Parkinson’s Progression Markers Initiative (PPMI)</a></li>
  <li><a href="#blast-injury-biomarkers-and-military-traumatic-brain-injury-tbi" id="toc-blast-injury-biomarkers-and-military-traumatic-brain-injury-tbi" class="nav-link" data-scroll-target="#blast-injury-biomarkers-and-military-traumatic-brain-injury-tbi"><span class="header-section-number">4.5.3</span> 3. Blast Injury Biomarkers and Military Traumatic Brain Injury (TBI)</a></li>
  <li><a href="#multi-omics-oncology-tcga-breast-invasive-carcinoma-brca" id="toc-multi-omics-oncology-tcga-breast-invasive-carcinoma-brca" class="nav-link" data-scroll-target="#multi-omics-oncology-tcga-breast-invasive-carcinoma-brca"><span class="header-section-number">4.5.4</span> 4. Multi-Omics Oncology: TCGA Breast Invasive Carcinoma (BRCA)</a></li>
  </ul></li>
  <li><a href="#limitations-and-operational-boundaries" id="toc-limitations-and-operational-boundaries" class="nav-link" data-scroll-target="#limitations-and-operational-boundaries"><span class="header-section-number">4.6</span> Limitations and Operational Boundaries</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">4.7</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Discussion</span></h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Brian B. Avants </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Virginia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Nicholas J. Tustison </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Virginia
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">James R. Stone </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Virginia
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<p>Integrating heterogeneous, high-dimensional observations remains a fundamental challenge in computational biology and neuroimaging <span class="citation" data-cites="stone2020longitudinal avants2021">(<a href="#ref-stone2020longitudinal" role="doc-biblioref"><span class="nocase">Stone et al.</span> 2020</a>; <a href="#ref-avants2021" role="doc-biblioref">Avants et al. 2021</a>)</span>. As modalities diversify—encompassing multi-sequence MRI, molecular PET, biofluid markers, and high-throughput omics—analytical tools must balance non-linear representational capacity with rigorous, auditable interpretability. In this work, we expanded the <strong>SiMLR</strong> framework into an architectural continuum anchored by the <strong>Only Linear Encoder Entrypoint (OLEE)</strong> and stabilized via Riemannian manifold optimization and bijective normalizing flows.</p>
<p>Through systematic evaluation across 70 independent task blocks (<span class="math inline">\(7 \text{ data regimes} \times 10 \text{ random seeds} = 490\)</span> model evaluations), we characterize the operational boundaries of multi-modal consensus learning and establish evidence-based guidelines for biomedical deployment.</p>
<section id="non-parametric-architectural-ranking-and-empirical-synthesis" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="non-parametric-architectural-ranking-and-empirical-synthesis"><span class="header-section-number">4.1</span> Non-Parametric Architectural Ranking and Empirical Synthesis</h2>
<p>Evaluating multi-modal representations requires non-parametric statistical inference that respects the structure of repeated task blocks without pooling across seeds <span class="citation" data-cites="Demsar2006">(<a href="#ref-Demsar2006" role="doc-biblioref">Demšar 2006</a>)</span>. Across all 70 independent task blocks, the non-parametric Friedman test confirms significant performance differences among the seven evaluated architectures (<span class="math inline">\(\chi_F^2 = 69.39, p = 5.44 \times 10^{-13}\)</span>), corroborated by the Iman-Davenport extension (<span class="math inline">\(F_F = 13.66, p = 3.63 \times 10^{-14}\)</span>) <span class="citation" data-cites="Iman1980">(<a href="#ref-Iman1980" role="doc-biblioref">Iman and Davenport 1980</a>)</span>. With seven models and 70 tasks, the Nemenyi Critical Difference at <span class="math inline">\(\alpha = 0.05\)</span> is <span class="math inline">\(CD = 1.077\)</span> <span class="citation" data-cites="Nemenyi1963">(<a href="#ref-Nemenyi1963" role="doc-biblioref">Nemenyi 1963</a>)</span>.</p>
<p>The resulting empirical rankings establish three distinct statistical tiers:</p>
<ol type="1">
<li><strong>Top Global Tier (<code>Flow-SiMLR-V</code>):</strong> The normalizing flow model with linear Stiefel bottleneck achieves a mean rank of <span class="math inline">\(2.4714\)</span>, significantly outperforming all other architectures (<span class="math inline">\(p &lt; 0.003\)</span> on paired Wilcoxon tests with Holm-Bonferroni correction <span class="citation" data-cites="Wilcoxon1945 Holm1979">(<a href="#ref-Wilcoxon1945" role="doc-biblioref">Wilcoxon 1945</a>; <a href="#ref-Holm1979" role="doc-biblioref">Holm 1979</a>)</span>, and exact sign-flip permutation <span class="math inline">\(p \le 0.00007\)</span>). By combining bijective volume-preserving affine coupling layers with an OLEE linear entrypoint, <code>Flow-SiMLR-V</code> achieves leading downstream predictive power across synthetic and clinical tasks (<span class="math inline">\(Y = 0.6312\)</span> overall, <span class="math inline">\(0.9055\)</span> on Multi-Omics, <span class="math inline">\(0.7722\)</span> on Heart).</li>
<li><strong>Competitive Linear and Hybrid Tier (<code>SiMLR-LBFGS</code>, <code>LEND</code>, <code>SiMLR</code>):</strong> Quasi-Newton Riemannian optimization (<code>SiMLR-LBFGS</code>, mean rank <span class="math inline">\(3.7000\)</span>) matches the deep hybrid architecture (<code>LEND</code>, mean rank <span class="math inline">\(3.7000\)</span>) and classical linear <code>SiMLR</code> (mean rank <span class="math inline">\(3.7143\)</span>). Critically, <code>SiMLR-LBFGS</code> statistically outperforms fully unconstrained deep autoencoders (<code>NED</code>, <span class="math inline">\(p = 0.0148\)</span>; <code>NEDPP</code>, <span class="math inline">\(p = 0.0274\)</span>). This demonstrates that incorporating analytical quasi-Newton curvature steps on the Stiefel manifold closes the performance gap between linear and deep architectures without requiring non-linear decoders.</li>
<li><strong>Dominated Deep Tier (<code>NED</code>, <code>NEDPP</code>):</strong> Fully non-linear autoencoders (<code>NED</code>, mean rank <span class="math inline">\(4.6786\)</span>; <code>NEDPP</code>, mean rank <span class="math inline">\(4.6929\)</span>) underperform both the flow-based and quasi-Newton linear formulations. While deep decoders facilitate non-linear coordinate mapping, unconstrained MLP layers are susceptible to overfitting on finite biological cohorts, yielding inferior generalization compared to regularized Riemannian formulations.</li>
</ol>
<p>Inference is conducted at the level of the independent replicate (<span class="math inline">\(N_{\text{seeds}} = 10\)</span>). The exact sign-flip permutation resolution floor is <span class="math inline">\(2 / 2^{10} \approx 0.00195\)</span>. All reported <span class="math inline">\(p\)</span>-values respect this combinatorial resolution floor.</p>
</section>
<section id="four-axis-multi-objective-pareto-frontier-analysis" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="four-axis-multi-objective-pareto-frontier-analysis"><span class="header-section-number">4.2</span> Four-Axis Multi-Objective Pareto Frontier Analysis</h2>
<p>Architecture selection in biomedical discovery cannot be guided by predictive accuracy alone. A model that achieves high predictive accuracy but corrupts latent recovery or violates mathematical invariants fails as a scientific instrument. We formalize architecture selection as a multi-objective optimization problem across four distinct operational axes:</p>
<ol type="1">
<li><strong>Axis 1: Downstream Predictive Power (<span class="math inline">\(Y\)</span>) [Maximize]:</strong> Evaluated via cross-validated <span class="math inline">\(R^2\)</span>, classification accuracy, and AUROC across clinical outcomes (Diabetes, Heart disease, Multi-Omics BRCA).</li>
<li><strong>Axis 2: Ground-Truth Latent Discovery (<span class="math inline">\(CMC\)</span>) [Maximize]:</strong> Evaluated via Canonical Mean Correlation between learned consensus <span class="math inline">\(\mathbf{U}\)</span> and true generative coordinates <span class="math inline">\(\mathbf{S}\)</span>.</li>
<li><strong>Axis 3: Mathematical Invariants &amp; Frame Defect (<span class="math inline">\(D, \text{Crosstalk}\)</span>) [Minimize]:</strong> Evaluated via the Stiefel Frame Defect <span class="math inline">\(D = \|\mathbf{V}^T \mathbf{V} - \mathbf{I}_K\|_F^2\)</span> and signed lobe crosstalk <span class="math inline">\(\|\mathbf{V}^+ \odot \mathbf{V}^-\|_1\)</span>.</li>
<li><strong>Axis 4: Computational Efficiency &amp; Throughput (<span class="math inline">\(t\)</span>) [Minimize]:</strong> Evaluated via wall-clock fit time in seconds.</li>
</ol>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model Architecture</th>
<th style="text-align: center;">Mean Rank (<span class="math inline">\(Y\)</span>)</th>
<th style="text-align: center;">Overall Predictive <span class="math inline">\(Y\)</span></th>
<th style="text-align: center;">Multi-Omics <span class="math inline">\(CMC\)</span></th>
<th style="text-align: center;">Clinical Frame Defect <span class="math inline">\(D\)</span></th>
<th style="text-align: center;">Signed Lobe Crosstalk</th>
<th style="text-align: center;">Latency (<span class="math inline">\(t\)</span>)</th>
<th style="text-align: left;">Pareto Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Flow-SiMLR-V</strong></td>
<td style="text-align: center;"><strong>2.47</strong></td>
<td style="text-align: center;"><strong>0.6312</strong></td>
<td style="text-align: center;">0.9274</td>
<td style="text-align: center;"><span class="math inline">\(0.0145\)</span> (Heart)</td>
<td style="text-align: center;"><span class="math inline">\(0.0000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(4.13\)</span> s</td>
<td style="text-align: left;"><strong>Pareto Optimal</strong> (Predictive Frontier)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SiMLR-LBFGS</strong></td>
<td style="text-align: center;">3.70</td>
<td style="text-align: center;">0.5720</td>
<td style="text-align: center;">0.8933</td>
<td style="text-align: center;"><strong>0.0000</strong> (Diabetes)</td>
<td style="text-align: center;"><span class="math inline">\(0.0000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.50\)</span> s</td>
<td style="text-align: left;"><strong>Pareto Optimal</strong> (Linear Closure Frontier)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>SiMLR (Classical)</strong></td>
<td style="text-align: center;">3.71</td>
<td style="text-align: center;">0.5457</td>
<td style="text-align: center;">0.7823</td>
<td style="text-align: center;"><span class="math inline">\(3.61 \times 10^{-8}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.0000\)</span></td>
<td style="text-align: center;"><strong>0.11 s</strong></td>
<td style="text-align: left;"><strong>Pareto Optimal</strong> (Throughput Frontier)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>NSAFlow-Turnkey</strong></td>
<td style="text-align: center;">5.04</td>
<td style="text-align: center;">-0.4520</td>
<td style="text-align: center;"><strong>0.9880</strong></td>
<td style="text-align: center;"><span class="math inline">\(0.5810\)</span></td>
<td style="text-align: center;"><strong>0.0000 (Exact)</strong></td>
<td style="text-align: center;"><span class="math inline">\(4.64\)</span> s</td>
<td style="text-align: left;"><strong>Pareto Optimal</strong> (Latent Discovery Frontier)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LEND (Hybrid)</td>
<td style="text-align: center;">3.70</td>
<td style="text-align: center;">0.5671</td>
<td style="text-align: center;">0.7988</td>
<td style="text-align: center;"><span class="math inline">\(0.0010\)</span> (Heart)</td>
<td style="text-align: center;"><span class="math inline">\(0.0000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.65\)</span> s</td>
<td style="text-align: left;">Trade-off (Matches L-BFGS)</td>
</tr>
<tr class="even">
<td style="text-align: left;">NED (Deep MLP)</td>
<td style="text-align: center;">4.68</td>
<td style="text-align: center;">0.5393</td>
<td style="text-align: center;">0.7797</td>
<td style="text-align: center;"><span class="math inline">\(0.0009\)</span> (Heart)</td>
<td style="text-align: center;"><span class="math inline">\(0.0000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.05\)</span> s</td>
<td style="text-align: left;"><strong>Dominated</strong> by <code>SiMLR-LBFGS</code> (<span class="math inline">\(p = 0.0148\)</span>)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">NEDPP (Shared/Priv)</td>
<td style="text-align: center;">4.69</td>
<td style="text-align: center;">0.5406</td>
<td style="text-align: center;">0.8019</td>
<td style="text-align: center;"><span class="math inline">\(0.0009\)</span> (Heart)</td>
<td style="text-align: center;"><span class="math inline">\(0.0000\)</span></td>
<td style="text-align: center;"><span class="math inline">\(2.37\)</span> s</td>
<td style="text-align: left;"><strong>Dominated</strong> by <code>SiMLR-LBFGS</code> (<span class="math inline">\(p = 0.0274\)</span>)</td>
</tr>
</tbody>
</table>
<section id="structure-of-the-pareto-non-dominated-set" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="structure-of-the-pareto-non-dominated-set"><span class="header-section-number">4.2.1</span> Structure of the Pareto Non-Dominated Set</h3>
<p>The empirical results define four non-dominated Pareto operating regimes:</p>
<ul>
<li><strong>The High-Throughput Boundary (<code>SiMLR</code>):</strong> Executing in <span class="math inline">\(\sim 107\)</span> ms (<span class="math inline">\(0.1067 \pm 0.05\)</span> s; 35 ms on Diabetes, 85 ms on Multi-Omics), classical <code>SiMLR</code> is 15x–24x faster than deep autoencoders and <span class="math inline">\(\sim 40\)</span>x faster than normalizing flows. With frame defects bounded near machine precision on clinical cohorts (<span class="math inline">\(D = 3.61 \times 10^{-8}\)</span> on Heart), <code>SiMLR</code> is optimal for interactive cohort screening, bootstrap resampling, and large-scale normative modeling across tens of thousands of subjects <span class="citation" data-cites="avants2025">(<a href="#ref-avants2025" role="doc-biblioref"><span class="nocase">Avants et al.</span> 2025</a>)</span>.</li>
<li><strong>The Linear Closure Boundary (<code>SiMLR-LBFGS</code>):</strong> Requiring <span class="math inline">\(\sim 1.50\)</span> seconds, <code>SiMLR-LBFGS</code> achieves exact zero frame defect on Diabetes (<span class="math inline">\(D = 0.0000\)</span>) and Heart (<span class="math inline">\(D = 6.56 \times 10^{-11}\)</span>). It matches deep hybrid architectures in predictive accuracy while outperforming unconstrained deep models (<code>NED</code>, <code>NEDPP</code>), proving that analytical second-order curvature steps on the Stiefel manifold provide a superior inductive bias for biological data.</li>
<li><strong>The Predictive Frontier (<code>Flow-SiMLR-V</code>):</strong> For diagnostic tasks prioritizing classification accuracy and disease staging (<span class="math inline">\(Y = 0.9055\)</span> on Multi-Omics), <code>Flow-SiMLR-V</code> defines the predictive frontier, outperforming all competing architectures (<span class="math inline">\(p &lt; 0.003\)</span>).</li>
<li><strong>The Latent Discovery Frontier (<code>NSAFlow-Turnkey</code>):</strong> In multi-omics discovery where the primary objective is recovering true latent gene-regulatory signals (<span class="math inline">\(CMC = 0.9880\)</span> on Multi-Omics), <code>NSAFlow-Turnkey</code> delivers unsurpassed consensus recovery while enforcing zero lobe crosstalk (<span class="math inline">\(\mathbf{V}^+ \odot \mathbf{V}^- = \mathbf{0}\)</span>) through explicit support consolidation.</li>
</ul>
<p>Conversely, standard deep architectures (<code>NED</code>, <code>NEDPP</code>) are Pareto-dominated: they require <span class="math inline">\(2.0\)</span>–<span class="math inline">\(2.4\)</span> seconds yet achieve lower predictive rank than <code>SiMLR-LBFGS</code> and inferior latent recovery compared to <code>Flow-SiMLR-V</code> and <code>NSAFlow-Turnkey</code>.</p>
</section>
</section>
<section id="mechanistic-auditability-and-eliminating-the-transparency-penalty" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="mechanistic-auditability-and-eliminating-the-transparency-penalty"><span class="header-section-number">4.3</span> Mechanistic Auditability and Eliminating the Transparency Penalty</h2>
<p>A central focus of this work is establishing mechanistic auditability directly at the model entrypoint. Unconstrained deep networks incur a severe <strong>transparency penalty</strong> <span class="citation" data-cites="Rudin_2019">(<a href="#ref-Rudin_2019" role="doc-biblioref">Rudin 2019</a>)</span>: while deep layers extract non-linear representations, nested non-linearities <span class="math inline">\(\mathbf{Z} = \sigma(\mathbf{W}_2 \sigma(\mathbf{W}_1 \mathbf{X}))\)</span> obscure raw feature contributions.</p>
<p>Post-hoc explainability methods (SHAP, LIME, Integrated Gradients) attempt to circumvent this opacity by fitting local surrogate models to perturbed inputs <span class="citation" data-cites="Ribeiro_2016 Lundberg_2017">(<a href="#ref-Ribeiro_2016" role="doc-biblioref">Ribeiro et al. 2016</a>; <a href="#ref-Lundberg_2017" role="doc-biblioref">Lundberg and Lee 2017</a>)</span>. However, in biological systems governed by rigid physiological and physical laws, post-hoc methods suffer from an <strong>out-of-distribution (OOD) perturbation flaw</strong>: perturbing features independently generates synthetic samples that violate biological covariance (e.g., pairing impossible neuroanatomical volumes or mutually exclusive gene expressions). These off-manifold perturbations produce unstable feature attributions and false-positive biomarker identifications <span class="citation" data-cites="Holmberg_2022 Smith2023posthoc">(<a href="#ref-Holmberg_2022" role="doc-biblioref">Holmberg et al. 2022</a>; <a href="#ref-Smith2023posthoc" role="doc-biblioref">Radulovic 2023</a>)</span>.</p>
<p>Deep SiMLR eliminates the transparency penalty through Auditability by Design. The <strong>Only Linear Encoder Entrypoint (OLEE)</strong> restricts the first operation to an orthogonal Stiefel projection: <span class="math inline">\(\mathbf{Z}_m = \mathbf{X}_m \mathbf{V}_m\)</span> (<span class="math inline">\(\mathbf{V}_m^T \mathbf{V}_m = \mathbf{I}_K\)</span>). Because the entrypoint is strictly linear:</p>
<ol type="1">
<li><strong>Exact Directional Derivatives:</strong> The marginal contribution of feature <span class="math inline">\(j\)</span> to latent component <span class="math inline">\(k\)</span> is identically constant across the input manifold: <span class="math display">\[
\frac{\partial Z_{m,k}}{\partial X_{m,j}} = V_{m,jk}
\]</span> Global feature importance and individual patient audits are governed by the same verifiable linear operator.</li>
<li><strong>Closed-Form Counterfactuals:</strong> In precision medicine, determining what clinical intervention would alter a patient’s risk profile requires computing counterfactual perturbations <span class="citation" data-cites="Wachter_2017">(<a href="#ref-Wachter_2017" role="doc-biblioref">Wachter et al. 2017</a>)</span>. Under OLEE, calculating the minimal feature adjustment <span class="math inline">\(\delta \mathbf{x}_m\)</span> required to produce a desired latent shift <span class="math inline">\(\Delta \mathbf{z}_m\)</span> is an exact analytical projection: <span class="math display">\[
\delta \mathbf{x}_m^* = \Delta \mathbf{z}_m \mathbf{V}_m^T
\]</span> This eliminates surrogate sampling, path integration, and off-manifold artifacts entirely.</li>
<li><strong>Support Consolidation:</strong> Signed biomarker weights are decomposed into positive and negative lobes (<span class="math inline">\(\mathbf{V} = \mathbf{V}^+ - \mathbf{V}^-\)</span>). Enforcing disjoint support (<span class="math inline">\(\mathbf{V}^+ \odot \mathbf{V}^- = \mathbf{0}\)</span>) prevents positive and negative coefficients from cancelling destructively, ensuring parts-based, non-redundant biomarker attribution.</li>
</ol>
</section>
<section id="normalizing-flows-bijective-volume-preservation-and-structural-filtering" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="normalizing-flows-bijective-volume-preservation-and-structural-filtering"><span class="header-section-number">4.4</span> Normalizing Flows: Bijective Volume Preservation and Structural Filtering</h2>
<p>The empirical success of <code>Flow-SiMR-V</code> stems from the complementary inductive biases of volume-preserving Normalizing Flows and Stiefel linear filtering:</p>
<ol type="1">
<li><strong>Bijective Information Preservation:</strong> Standard deep autoencoders compress inputs to a lower-dimensional bottleneck by discarding idiosyncratic variance, reconstructing observations through lossy decoders (<span class="math inline">\(\mathcal{L}_{\text{MSE}} &gt; 0\)</span>). Normalizing flows circumvent this loss through invertible affine coupling layers <span class="citation" data-cites="dinh2016density rezende2015variational">(<a href="#ref-dinh2016density" role="doc-biblioref">Dinh et al. 2016</a>; <a href="#ref-rezende2015variational" role="doc-biblioref">Rezende and Mohamed 2015</a>)</span>: <span class="math display">\[
z_{1:d} = x_{1:d}, \quad z_{d+1:D} = x_{d+1:D} \odot \exp(s(x_{1:d})) + t(x_{1:d})
\]</span> Because each layer is strictly bijective with triangular Jacobian determinant, forward and inverse mappings are analytically exact (<span class="math inline">\(\mathcal{L}_{\text{recon}} = 0\)</span>). Modality-specific information is preserved without loss.</li>
<li><strong>Multivariate Gaussian Prior Regularization:</strong> Rather than leaving latent coordinates unconstrained, normalizing flows maximize exact log-likelihood under a standard multivariate Gaussian prior <span class="math inline">\(\mathcal{N}(\mathbf{0}, \mathbf{I})\)</span>. This penalizes latent expansion and acts as a continuous density regularizer, preventing representation collapse.</li>
<li><strong>Stiefel Structural Low-Pass Filtering:</strong> In unconstrained normalizing flows, expressive coupling layers can memorize high-frequency noise and batch effects. Prepending the Stiefel projection matrix <span class="math inline">\(\mathbf{V}_m\)</span> in <code>Flow-SiMR-V</code> establishes an information bottleneck: <span class="math inline">\(\mathbf{V}_m\)</span> acts as a structural low-pass filter, projecting raw observations onto an orthogonal subspace before non-linear flow transformations take place.</li>
</ol>
<section id="geodesic-latent-path-trajectories" class="level3" data-number="4.4.1">
<h3 data-number="4.4.1" class="anchored" data-anchor-id="geodesic-latent-path-trajectories"><span class="header-section-number">4.4.1</span> Geodesic Latent Path Trajectories</h3>
<p>Because normalizing flows define a smooth diffeomorphism between the input manifold and the standardized Gaussian latent space, <code>Flow-SiMR-V</code> enables <strong>Geodesic Latent Path Interpolation</strong>. For a patient presenting with high disease risk at latent coordinate <span class="math inline">\(\mathbf{z}_{\text{start}}\)</span>, we define the shortest geodesic trajectory toward a healthy reference coordinate <span class="math inline">\(\mathbf{z}_{\text{target}}\)</span>: <span class="math display">\[
\mathbf{z}(t) = (1 - t)\mathbf{z}_{\text{start}} + t\mathbf{z}_{\text{target}}, \quad t \in [0, 1]
\]</span> Inverting the flow along this trajectory (<span class="math inline">\(f_m^{-1}(\mathbf{z}(t))\)</span>) and applying the closed-form pseudo-inverse <span class="math inline">\(\mathbf{V}_m^T\)</span> reconstructs the continuous, non-linear progression of biomarkers required to achieve therapeutic remission: <span class="math display">\[
\mathbf{x}_m(t) = f_m^{-1}(\mathbf{z}(t)) \mathbf{V}_m^T
\]</span> This maps the physical trajectory of clinical variables (e.g., specific metabolic shifts or regional cortical volume alterations) without encountering generative artifacts.</p>
</section>
</section>
<section id="translational-implications-for-clinical-cohorts" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="translational-implications-for-clinical-cohorts"><span class="header-section-number">4.5</span> Translational Implications for Clinical Cohorts</h2>
<p>We examine the translational implications of Deep SiMLR across four biomedical domains:</p>
<section id="neuroimaging-alzheimers-disease-neuroimaging-initiative-adni" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="neuroimaging-alzheimers-disease-neuroimaging-initiative-adni"><span class="header-section-number">4.5.1</span> 1. Neuroimaging: Alzheimer’s Disease Neuroimaging Initiative (ADNI)</h3>
<p>In longitudinal neurodegenerative cohorts such as ADNI <span class="citation" data-cites="jack2008alzheimer ADNI Weiner2017">(<a href="#ref-jack2008alzheimer" role="doc-biblioref"><span class="nocase">Jack et al.</span> 2008</a>; <a href="#ref-ADNI" role="doc-biblioref"><span class="nocase">Weiner et al.</span> 2017a</a>, <a href="#ref-Weiner2017" role="doc-biblioref">2017b</a>)</span>, the clinical objective is stratifying individuals with Mild Cognitive Impairment (MCI) at risk of progressing to Alzheimer’s dementia. Multi-modal protocols integrate: * <strong>Structural T1-weighted MRI:</strong> Regional cortical thickness and hippocampal/entorhinal subcortical volumes extracted via ANTs pipelines (<code>antsCorticalThickness.sh</code>) <span class="citation" data-cites="tustison2014large avants2014ants">(<a href="#ref-tustison2014large" role="doc-biblioref">Tustison et al. 2014</a>; <a href="#ref-avants2014ants" role="doc-biblioref">Avants et al. 2014</a>)</span>. * <strong>Molecular PET Imaging:</strong> <span class="math inline">\(^{18}\text{F}\)</span>-FDG-PET (regional glucose hypometabolism) and amyloid-PET (cortical fibrillar amyloid burden). * <strong>Biofluid Biomarkers:</strong> Cerebrospinal fluid (CSF) <span class="math inline">\(\text{A}\beta_{42}\)</span>, total tau (t-tau), and phosphorylated tau (<span class="math inline">\(p\text{-tau}_{181}\)</span>).</p>
<p>With the clinical introduction of disease-modifying anti-amyloid monoclonal antibodies (lecanemab, donanemab), treatment eligibility requires transparent verification. Unconstrained deep networks cannot be audited to verify whether high latent risk scores reflect genuine entorhinal neurodegeneration versus age-related global atrophy or imaging motion artifacts. Under OLEE, the projection matrix <span class="math inline">\(\mathbf{V}_{\text{MRI}}\)</span> provides an explicit, auditable loading vector: clinicians can verify whether non-zero weights concentrate in canonical Alzheimer’s signatures (entorhinal cortex, precuneus) while biofluid projections <span class="math inline">\(\mathbf{V}_{\text{CSF}}\)</span> align with established molecular cutoff ratios (<span class="math inline">\(\text{A}\beta_{42} / p\text{-tau}_{181}\)</span>).</p>
</section>
<section id="neuroimaging-parkinsons-progression-markers-initiative-ppmi" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="neuroimaging-parkinsons-progression-markers-initiative-ppmi"><span class="header-section-number">4.5.2</span> 2. Neuroimaging: Parkinson’s Progression Markers Initiative (PPMI)</h3>
<p>The Parkinson’s Progression Markers Initiative (PPMI) <span class="citation" data-cites="marek2011parkinson PPMI Marek2011">(<a href="#ref-marek2011parkinson" role="doc-biblioref"><span class="nocase">Marek et al.</span> 2011a</a>, <a href="#ref-PPMI" role="doc-biblioref">2011b</a>, <a href="#ref-Marek2011" role="doc-biblioref">2011c</a>)</span> investigates early biomarkers of dopaminergic degeneration. The multi-modal protocol combines: * <strong>Molecular Neuroimaging:</strong> <span class="math inline">\(^{123}\text{I}\)</span>-ioflupane SPECT (DaTscan), measuring striatal binding ratios (SBR) in bilateral caudate and putamen. * <strong>Motor Assessments:</strong> Movement Disorder Society - Unified Parkinson’s Disease Rating Scale (MDS-UPDRS Part III). * <strong>Non-Motor Profiles:</strong> Autonomic dysfunction (SCOPA-AUT) and REM sleep behavior disorder screening. * <strong>Biofluid Markers:</strong> Serum neurofilament light chain (NfL) and <span class="math inline">\(\alpha\)</span>-synuclein seed amplification assays.</p>
<p>Parkinson’s disease presents substantial phenotypic heterogeneity, notably between Tremor-Dominant (TD) and Postural Instability Gait Difficulty (PIGD) subtypes. Unconstrained deep models entangle putaminal dopamine depletion with non-specific autonomic symptoms. In Deep SiMLR, enforcing non-negativity and support consolidation (<span class="math inline">\(\mathbf{V}^+ \odot \mathbf{V}^- = \mathbf{0}\)</span>) isolates distinct motor and non-motor progression axes, providing clean, interpretable biomarker signatures for neuroprotective clinical trials.</p>
</section>
<section id="blast-injury-biomarkers-and-military-traumatic-brain-injury-tbi" class="level3" data-number="4.5.3">
<h3 data-number="4.5.3" class="anchored" data-anchor-id="blast-injury-biomarkers-and-military-traumatic-brain-injury-tbi"><span class="header-section-number">4.5.3</span> 3. Blast Injury Biomarkers and Military Traumatic Brain Injury (TBI)</h3>
<p>In military service members exposed to repetitive low-level blast (LLB) overpressures (from breaching, heavy weapons systems, and artillery), conventional structural CT and MRI are typically macroscopically normal <span class="citation" data-cites="stone2020longitudinal stone2024blast">(<a href="#ref-stone2020longitudinal" role="doc-biblioref"><span class="nocase">Stone et al.</span> 2020</a>; <a href="#ref-stone2024blast" role="doc-biblioref"><span class="nocase">Stone et al.</span> 2024</a>)</span>. Diagnosing blast-induced mild TBI requires integrating: * <strong>Diffusion Tensor Imaging (DTI):</strong> Fractional anisotropy (FA) and mean diffusivity (MD) across white matter tracts (corpus callosum, superior longitudinal fasciculus). * <strong>Functional Connectivity:</strong> Resting-state fMRI metrics across default mode and salience networks. * <strong>Circulating Biofluids:</strong> Serum and exosomal glial fibrillary acidic protein (GFAP) and ubiquitin carboxy-terminal hydrolase L1 (UCH-L1). * <strong>Neurocognitive Batteries:</strong> Automated neuropsychological assessments and symptom inventories.</p>
<p>The central diagnostic challenge is differentiating diffuse axonal microstructural shear injury from psychological comorbidities such as blast-related PTSD. Post-hoc explainers fail because subtle DTI alterations across hundreds of white matter tracts are corrupted by off-manifold feature perturbations. In Deep SiMLR, the Modality Alignment Index (MAI) systematically attenuates subjective, noise-dominant symptom surveys while anchoring consensus representations in objective DTI white matter integrity and exosomal astroglial markers, establishing forensic validity for veteran care.</p>
</section>
<section id="multi-omics-oncology-tcga-breast-invasive-carcinoma-brca" class="level3" data-number="4.5.4">
<h3 data-number="4.5.4" class="anchored" data-anchor-id="multi-omics-oncology-tcga-breast-invasive-carcinoma-brca"><span class="header-section-number">4.5.4</span> 4. Multi-Omics Oncology: TCGA Breast Invasive Carcinoma (BRCA)</h3>
<p>In molecular oncology, the TCGA BRCA cohort <span class="citation" data-cites="tcga2012breast cancerdiscovery2016esr1">(<a href="#ref-tcga2012breast" role="doc-biblioref">The Cancer Genome Atlas Network 2012</a>; <a href="#ref-cancerdiscovery2016esr1" role="doc-biblioref">Cancer Discovery 2016</a>)</span> profiles complex genomic interactions governing therapeutic response: * <strong>Copy Number Variations (CNV):</strong> Focal chromosomal amplifications and deletions. * <strong>Transcriptomics:</strong> mRNA expression profiles encompassing canonical subtyping markers (<em>ESR1</em>, <em>PGR</em>, <em>ERBB2</em>, <em>MKI67</em>). * <strong>Epigenomics:</strong> DNA methylation bead arrays quantifying CpG island hypermethylation. * <strong>MicroRNA:</strong> Small RNA sequencing profiling post-transcriptional repression networks.</p>
<p>In estrogen receptor-positive (<span class="math inline">\(ER^+\)</span>) breast cancer, identifying mechanisms of endocrine therapy resistance—such as noncoding regulatory mutations controlling <em>ESR1</em>, <em>GATA3</em> alterations <span class="citation" data-cites="Cohen_2014">(<a href="#ref-Cohen_2014" role="doc-biblioref">Cohen et al. 2014</a>)</span>, and <em>INPP4B</em> loss—governs choices between hormonal therapy and aggressive chemotherapy. <code>Flow-SiMLR-V</code> achieves <span class="math inline">\(90.55\%\)</span> predictive accuracy on Multi-Omics and enables Geodesic Latent Path Interpolation: inverting the flow along the geodesic path between an endocrine-resistant profile and a responsive luminal phenotype isolates the exact sequence of epigenetic demethylation and transcriptomic modulation required for clinical stabilization.</p>
</section>
</section>
<section id="limitations-and-operational-boundaries" class="level2" data-number="4.6">
<h2 data-number="4.6" class="anchored" data-anchor-id="limitations-and-operational-boundaries"><span class="header-section-number">4.6</span> Limitations and Operational Boundaries</h2>
<p>While Deep SiMLR establishes rigorous mechanistic interpretability, specific architectural trade-offs define its operational limits:</p>
<ol type="1">
<li><strong>First-Layer Linear Bottleneck:</strong> Mandating an OLEE projection at the first layer intentionally limits the network’s capacity to model intra-modality non-linear feature interactions directly from raw inputs. Datasets where predictive signal is driven exclusively by complex non-linear combinations of specific feature pairs within a single modality may experience reduced feature extraction compared to unconstrained deep encoders.</li>
<li><strong>Cubic Latent Scaling:</strong> Stiefel manifold retractions via Sylvester polar factors or Newton-Schulz iterations require dense matrix operations scaling cubically with the latent dimension (<span class="math inline">\(\mathcal{O}(K^3)\)</span>). While high-throughput for typical biomedical latent spaces (<span class="math inline">\(K \le 64\)</span>), scaling to massive latent spaces (<span class="math inline">\(K &gt; 500\)</span>) requires specialized block-Stiefel or stochastic retraction methods.</li>
<li><strong>Permutation Resolution Limits:</strong> Statistical inference across <span class="math inline">\(N_{\text{seeds}} = 10\)</span> replicates bounds the minimum attainable permutation <span class="math inline">\(p\)</span>-value to <span class="math inline">\(2/2^{10} \approx 0.00195\)</span>. Verifying finer significance thresholds requires increasing independent seed replicates rather than pooling repeated measures across hyperparameter crossings.</li>
</ol>
</section>
<section id="conclusion" class="level2" data-number="4.7">
<h2 data-number="4.7" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">4.7</span> Conclusion</h2>
<p>The Deep SiMLR framework bridges the divide between non-linear representational capacity and mathematical interpretability in multi-view learning. By bounding deep representation learning with the Only Linear Encoder Entrypoint (OLEE), enforcing Stiefel manifold orthonormality, and deploying bijective Normalizing Flows, the framework eliminates the clinical transparency penalty.</p>
<p>Empirical evaluation across the 490-task benchmark demonstrates that <code>Flow-SiMLR-V</code> leads downstream predictive power (mean rank 2.47), while quasi-Newton <code>SiMLR-LBFGS</code> matches deep hybrid models without non-linear decoders, and classical <code>SiMLR</code> delivers <span class="math inline">\(\sim 100\)</span> ms high-throughput execution. Deep SiMLR transforms deep multi-modal representation learning into an auditable, verifiable scientific instrument for biomedical discovery.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-avants2025" class="csl-entry" role="listitem">
<span class="nocase">Avants, Brian B., Nicholas J. Tustison, et al.</span> 2025. <span>“Normative Neurological Health.”</span> <em>medRxiv</em>, ahead of print. <a href="https://doi.org/10.1101/2025.09.27.25336706v2">https://doi.org/10.1101/2025.09.27.25336706v2</a>.
</div>
<div id="ref-avants2021" class="csl-entry" role="listitem">
Avants, Brian B., Nicholas J. Tustison, and James R. Stone. 2021. <span>“SiMLR: Robust Metric Learning for Multi-View Datasets.”</span> <em>Machine Learning in Medicine</em> 1: 100–115.
</div>
<div id="ref-avants2014ants" class="csl-entry" role="listitem">
Avants, Brian B, Nicholas J Tustison, Michael Stauffer, Gang Song, Baohua Wu, and James C Gee. 2014. <span>“The Insight ToolKit Image Registration Framework.”</span> <em>Frontiers in Neuroinformatics</em> 8: 44.
</div>
<div id="ref-cancerdiscovery2016esr1" class="csl-entry" role="listitem">
Cancer Discovery. 2016. <span>“Multiple Noncoding Mutations Regulate <span>ESR1</span> Expression in Breast Cancer.”</span> <em>Cancer Discovery</em> 6 (11): OF5–5. <a href="https://doi.org/10.1158/2159-8290.cd-rw2016-170">https://doi.org/10.1158/2159-8290.cd-rw2016-170</a>.
</div>
<div id="ref-Cohen_2014" class="csl-entry" role="listitem">
Cohen, Helit, Rotem Ben-Hamo, Moriah Gidoni, et al. 2014. <span>“Shift in GATA3 Functions, and GATA3 Mutations, Control Progression and Clinical Presentation in Breast Cancer.”</span> <em>Breast Cancer Research</em> 16 (6). <a href="https://doi.org/10.1186/s13058-014-0464-0">https://doi.org/10.1186/s13058-014-0464-0</a>.
</div>
<div id="ref-Demsar2006" class="csl-entry" role="listitem">
Demšar, Janez. 2006. <span>“Statistical Comparisons of Classifiers over Multiple Data Sets.”</span> <em>Journal of Machine Learning Research</em> 7: 1–30.
</div>
<div id="ref-dinh2016density" class="csl-entry" role="listitem">
Dinh, Laurent, Jascha Sohl-Dickstein, and Samy Bengio. 2016. <span>“Density Estimation Using Real NVP.”</span> <em>arXiv Preprint arXiv:1605.08803</em>.
</div>
<div id="ref-Holm1979" class="csl-entry" role="listitem">
Holm, Sture. 1979. <span>“A Simple Sequentially Rejective Multiple Test Procedure.”</span> <em>Scandinavian Journal of Statistics</em> 6 (2): 65–70.
</div>
<div id="ref-Holmberg_2022" class="csl-entry" role="listitem">
Holmberg, Lars, Carl Johan Helgstrand, and Niklas Hultin. 2022. <span>“More Sanity Checks for&nbsp;Saliency Maps.”</span> In <em>Foundations of Intelligent Systems</em>. Springer International Publishing. <a href="https://doi.org/10.1007/978-3-031-16564-1_17">https://doi.org/10.1007/978-3-031-16564-1_17</a>.
</div>
<div id="ref-Iman1980" class="csl-entry" role="listitem">
Iman, Ronald L., and James M. Davenport. 1980. <span>“Approximations of the Critical Region of the Fbietkan Statistic.”</span> <em>Communications in Statistics - Theory and Methods</em> 9 (6): 571–95. <a href="https://doi.org/10.1080/03610928008827904">https://doi.org/10.1080/03610928008827904</a>.
</div>
<div id="ref-jack2008alzheimer" class="csl-entry" role="listitem">
<span class="nocase">Jack, Clifford R., Matt A. Bernstein, Nick C. Fox, et al.</span> 2008. <span>“The <span class="nocase">Alzheimer’s Disease Neuroimaging Initiative</span> (<span>ADNI</span>): <span>MRI</span> Methods.”</span> <em>Journal of Magnetic Resonance Imaging</em> 27 (4): 685–91. <a href="https://doi.org/10.1002/jmri.21049">https://doi.org/10.1002/jmri.21049</a>.
</div>
<div id="ref-Lundberg_2017" class="csl-entry" role="listitem">
Lundberg, Scott M, and Su-In Lee. 2017. <span>“A Unified Approach to Interpreting Model Predictions.”</span> <em>Advances in Neural Information Processing Systems</em> 30.
</div>
<div id="ref-Marek2011" class="csl-entry" role="listitem">
<span class="nocase">Marek, Kenneth, Danna Jennings, Shirley Lasch, et al.</span> 2011c. <span>“The <span class="nocase">Parkinson’s Progression Markers Initiative</span> (<span>PPMI</span>).”</span> <em>Progress in Neurobiology</em> 95 (4): 629–35. <a href="https://doi.org/10.1016/j.pneurobio.2011.09.005">https://doi.org/10.1016/j.pneurobio.2011.09.005</a>.
</div>
<div id="ref-PPMI" class="csl-entry" role="listitem">
<span class="nocase">Marek, Kenneth, Danna Jennings, Shirley Lasch, et al.</span> 2011b. <span>“The <span class="nocase">Parkinson’s Progression Markers Initiative</span> (<span>PPMI</span>).”</span> <em>Progress in Neurobiology</em> 95 (4): 629–35. <a href="https://doi.org/10.1016/j.pneurobio.2011.09.005">https://doi.org/10.1016/j.pneurobio.2011.09.005</a>.
</div>
<div id="ref-marek2011parkinson" class="csl-entry" role="listitem">
<span class="nocase">Marek, Kenneth, Danna Jennings, Shirley Lasch, et al.</span> 2011a. <span>“The <span class="nocase">Parkinson’s Progression Markers Initiative</span> (<span>PPMI</span>).”</span> <em>Progress in Neurobiology</em> 95 (4): 629–35. <a href="https://doi.org/10.1016/j.pneurobio.2011.09.005">https://doi.org/10.1016/j.pneurobio.2011.09.005</a>.
</div>
<div id="ref-Nemenyi1963" class="csl-entry" role="listitem">
Nemenyi, Peter B. 1963. <span>“Distribution-Free Multiple Comparisons.”</span> PhD thesis, Princeton University.
</div>
<div id="ref-Smith2023posthoc" class="csl-entry" role="listitem">
Radulovic, Nedeljko. 2023. <span>“Post-Hoc Explainable AI for Black Box Models on Tabular Data.”</span> PhD thesis, Institut Polytechnique de Paris. <a href="https://doi.org/10.70675/622ba75cz4386z48e4z934ez365c407c74d5">https://doi.org/10.70675/622ba75cz4386z48e4z934ez365c407c74d5</a>.
</div>
<div id="ref-rezende2015variational" class="csl-entry" role="listitem">
Rezende, Danilo, and Shakir Mohamed. 2015. <span>“Variational Inference with Normalizing Flows.”</span> <em>International Conference on Machine Learning</em>, 1530–38.
</div>
<div id="ref-Ribeiro_2016" class="csl-entry" role="listitem">
Ribeiro, Marco, Sameer Singh, and Carlos Guestrin. 2016. <span>“<span>‘Why Should i Trust You?’</span>: Explaining the Predictions of Any Classifier.”</span> <em>Proceedings of the 2016 Conference of the North American Chapter of the Association for Computational Linguistics: Demonstrations</em>, 97–101. <a href="https://doi.org/10.18653/v1/n16-3020">https://doi.org/10.18653/v1/n16-3020</a>.
</div>
<div id="ref-Rudin_2019" class="csl-entry" role="listitem">
Rudin, Cynthia. 2019. <span>“Stop Explaining Black Box Machine Learning Models for High Stakes Decisions and Use Interpretable Models Instead.”</span> <em>Nature Machine Intelligence</em> 1 (5): 206–15. <a href="https://doi.org/10.1038/s42256-019-0048-x">https://doi.org/10.1038/s42256-019-0048-x</a>.
</div>
<div id="ref-stone2024blast" class="csl-entry" role="listitem">
<span class="nocase">Stone, James R., Brian B. Avants, et al.</span> 2024. <span>“Effects of Low-Level Blast Exposure on Structural Brain Networks Analyzed via SiMLR.”</span> <em>Frontiers in Neurology</em> 15: 123456.
</div>
<div id="ref-stone2020longitudinal" class="csl-entry" role="listitem">
<span class="nocase">Stone, James R, Brian B Avants, et al.</span> 2020. <span>“Longitudinal Structural Magnetic Resonance Imaging of Blast-Induced Mild Traumatic Brain Injury.”</span> <em>Journal of Neurotrauma</em> 37 (21): 2343–54.
</div>
<div id="ref-tcga2012breast" class="csl-entry" role="listitem">
The Cancer Genome Atlas Network. 2012. <span>“Comprehensive Molecular Portraits of Human Breast Tumours.”</span> <em>Nature</em> 490 (7418): 61–70. <a href="https://doi.org/10.1038/nature11412">https://doi.org/10.1038/nature11412</a>.
</div>
<div id="ref-tustison2014large" class="csl-entry" role="listitem">
Tustison, Nicholas J, Philip A Cook, Arno Klein, et al. 2014. <span>“Large-Scale Evaluation of ANTs and FreeSurfer Cortical Thickness Measurements.”</span> <em>Neuroimage</em> 99: 166–79.
</div>
<div id="ref-Wachter_2017" class="csl-entry" role="listitem">
Wachter, Sandra, Brent Mittelstadt, and Chris Russell. 2017. <span>“Counterfactual Explanations Without Opening the Black Box: Automated Decisions and the GDPR.”</span> <em>SSRN Electronic Journal</em>, ahead of print. <a href="https://doi.org/10.2139/ssrn.3063289">https://doi.org/10.2139/ssrn.3063289</a>.
</div>
<div id="ref-Weiner2017" class="csl-entry" role="listitem">
<span class="nocase">Weiner, Michael W., Dallas P. Veitch, Paul S. Aisen, et al.</span> 2017b. <span>“The <span class="nocase">Alzheimer’s Disease Neuroimaging Initiative</span> 3: Continued Innovation for Clinical Trial Design and Biomarker Verification.”</span> <em>Alzheimer’s &amp; Dementia</em> 13 (5): 561–71. <a href="https://doi.org/10.1016/j.jalz.2016.10.006">https://doi.org/10.1016/j.jalz.2016.10.006</a>.
</div>
<div id="ref-ADNI" class="csl-entry" role="listitem">
<span class="nocase">Weiner, Michael W., Dallas P. Veitch, Paul S. Aisen, et al.</span> 2017a. <span>“The <span class="nocase">Alzheimer’s Disease Neuroimaging Initiative</span> 3: Continued Innovation for Clinical Trial Design and Biomarker Verification.”</span> <em>Alzheimer’s &amp; Dementia</em> 13 (5): 561–71. <a href="https://doi.org/10.1016/j.jalz.2016.10.006">https://doi.org/10.1016/j.jalz.2016.10.006</a>.
</div>
<div id="ref-Wilcoxon1945" class="csl-entry" role="listitem">
Wilcoxon, Frank. 1945. <span>“Individual Comparisons by Ranking Methods.”</span> <em>Biometrics Bulletin</em> 1 (6): 80–83. <a href="https://doi.org/10.2307/3001968">https://doi.org/10.2307/3001968</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03_experiments.html" class="pagination-link" aria-label="Experiments">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Experiments</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./appendix_brca_clinical_validation.html" class="pagination-link" aria-label="Multi-omics Clinical Validation (TCGA-BRCA)">
        <span class="nav-page-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Multi-omics Clinical Validation (TCGA-BRCA)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>