% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
]{report}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother

\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{241,243,245}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.40,0.45,0.13}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\ExtensionTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.28,0.35,0.67}{#1}}
\newcommand{\ImportTok}[1]{\textcolor[rgb]{0.00,0.46,0.62}{#1}}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.68,0.00,0.00}{#1}}
\newcommand{\RegionMarkerTok}[1]{\textcolor[rgb]{0.00,0.23,0.31}{#1}}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.07,0.07,0.07}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.13,0.47,0.30}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.37,0.37,0.37}{\textit{#1}}}

\usepackage{longtable,booktabs,array}
\newcounter{none} % for unnumbered tables
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}



\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\makeatletter
\@ifpackageloaded{bookmark}{}{\usepackage{bookmark}}
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Deep SiMLR: Auditable Multi-Modal Integration for Biomedical Discovery},
  pdfauthor={Brian B. Avants; Nicholas J. Tustison; James R. Stone},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Deep SiMLR: Auditable Multi-Modal Integration for Biomedical
Discovery}
\author{Brian B. Avants \and Nicholas J. Tustison \and James R. Stone}
\date{2026-06-11}
\begin{document}
\maketitle

\renewcommand*\contentsname{Table of contents}
{
\setcounter{tocdepth}{2}
\tableofcontents
}

\bookmarksetup{startatroot}

\chapter*{Abstract}\label{abstract}
\addcontentsline{toc}{chapter}{Abstract}

\markboth{Abstract}{Abstract}

Deep multi-modal integration---typified by Deep Canonical Correlation
Analysis (Deep CCA), Multi-Omics Factor Analysis extensions (MOFA+), and
Multimodal Variational Autoencoders (MVAEs)---achieves strong predictive
performance but suffers from the ``Information Masking'' problem: deeply
nested non-linearities irreparably entangle input features, precluding
the exact feature attribution required in high-stakes scientific
domains. To solve this, we introduce Deep SiMLR (Similarity-driven
Multi-view Reconstruction), a joint-variational framework that bounds
deep representation learning with exact structural interpretability. We
impose an Information Bottleneck termed the Only Linear Encoder Entry
(OLEE)---a mandatory projection onto the Stiefel manifold
(\(\mathbf{V}^\top \mathbf{V} = \mathbf{I}\)) mapped as
\(\mathbf{Z} = \mathbf{X}\mathbf{V}\)---that guarantees every latent
factor remains a mathematically exact, invertible linear combination of
the input features. To combat the corruption of multi-modal consensus by
high-dimensional noise, we derive a Spectral Triage mechanism. By
weighting modalities via a Modality Alignment Index (MAI) based on
Spectral Sharpness (\(\sigma_1 / \sum \sigma_i\)), this mechanism
explicitly down-weights isotropic noise. Comprehensive evaluations on
synthetic manifolds and clinical multi-omics (BRCA) demonstrate that our
framework achieves predictive parity with unconstrained deep models
while solving Information Masking, providing the exact, analytic feature
attribution required for auditable discovery.

\bookmarksetup{startatroot}

\chapter{Introduction and Background}\label{introduction-and-background}

\section{Introduction}\label{introduction}

High-throughput multi-modal datasets provide complementary observations
of shared biological signals. Integrating these distinct data
streams---formalized as \emph{views} or \emph{modalities}
\(\mathbf{X}_m\)---is essential for defining complex phenotypes in
neuroimaging and genomics ({Stone et al.} 2020; Avants et al. 2014).
Deep representation learning techniques, including Deep Canonical
Correlation Analysis (Deep CCA) (Andrew et al. 2013), Multi-Omics Factor
Analysis extensions (MOFA+) (Argelaguet et al. 2020), and Multimodal
Variational Autoencoders (MVAEs) (Wu and Goodman 2018), achieve
state-of-the-art predictive performance by modeling non-linear
covariance structures. However, standard deep autoencoders and CCA
variants fail to preserve information bidirectionally, relying on lossy
projection bottlenecks. Furthermore, they fundamentally fail to provide
exact feature attribution. By projecting inputs through deeply nested
non-linearities, they induce the \textbf{Information Masking} problem:
the mathematical relationship between the original input features and
the derived latent consensus is irrevocably entangled. Normalizing Flows
(Rezende and Mohamed 2015; Dinh et al. 2016) present an alternative: by
defining bijective, information-preserving coordinate transformations,
they map high-dimensional observations to structured latents without
information loss. This black-box formulation violates the strict
interpretability requirements of high-stakes scientific and clinical
domains, where actionable discovery relies on identifying exactly which
biomarkers drive the predictive model.

We solve the Information Masking problem by introducing Deep SiMLR. We
enforce Auditability by Design through two core mechanisms. First, we
impose an Information Bottleneck termed the \textbf{Only Linear Encoder
Entry (OLEE)}. OLEE mandates that the initial transformation of any
modality \(\mathbf{X}_m\) is a strict projection onto an orthogonal
basis \(\mathbf{V}_m\) on the Stiefel manifold
(\(\mathbf{V}_m^\top \mathbf{V}_m = \mathbf{I}\)). This guarantees that
the entry point to any downstream deep network is a mathematically
exact, interpretable linear combination of the input features. Second,
to prevent high-dimensional noise from corrupting the shared
representation, we deploy \textbf{Spectral Triage}. This mechanism
computes a Modality Alignment Index (MAI) based on Spectral Sharpness,
aggressively penalizing noise-dominant modalities during consensus
formation. Together, OLEE and Spectral Triage yield a family of
architectures that match the predictive power of unconstrained deep
models while preserving perfect analytic transparency.

\subsection{Multimodal Consensus as Latent Signal
Recovery}\label{multimodal-consensus-as-latent-signal-recovery}

We formalize multi-view integration as the recovery of a latent signal
\(\mathbf{S} \in \mathbb{R}^{N \times K}\) from a set of \(M\)
high-dimensional observations \(\{\mathbf{X}_m\}_{m=1}^M\), where
\(\mathbf{X}_m \in \mathbb{R}^{N \times D_m}\). We model each view as
\(\mathbf{X}_m = g_m(\mathbf{S}) + \mathbf{E}_m\), where \(g_m\) denotes
a modality-specific generative function and \(\mathbf{E}_m\) represents
modality-specific noise. Optimal integration requires a mathematical
formulation that maps the covariance structure of each observer to a
shared consensus representation \(\mathbf{U}\) that approximates
\(\mathbf{S}\).

Heterogeneous noise profiles and distinct generative functions
complicate multi-modal integration. A primary failure mode arises when
high-dimensional data streams lacking structured signal, termed
``noise-dominant modalities,'' corrupt the consensus representation
through spurious correlations. Robust consensus discovery necessitates a
statistical mechanism to identify and attenuate these noise sources,
guaranteeing that the derived representations capture biological signal
rather than isotropic artifacts.

Historically, Canonical Correlation Analysis (CCA) (Hotelling 1936)
provided the foundation for multi-view integration. Similarity-driven
Multi-view Linear Reconstruction (SiMLR) extended CCA by applying
sparsity and positivity constraints (Zhao et al. 2011; Lee and Seung
1999), alongside optimization strategies that scale to large normative
modeling cohorts (Avants et al. 2021, 2025). While SiMLR provides a
robust, linear approach, modern deep learning architectures such as Deep
CCA and MVAEs achieve higher predictive performance by mapping
non-linear manifolds. However, as noted, these complex models obscure
the mapping from features to latents and are highly susceptible to
over-fitting in high-dimensional, noise-dominant regimes.

We bridge the gap between deep learning's representational capacity and
the transparency necessitated by scientific and clinical validation. We
introduce a family of architectures (LEND, NED, NEDPP) that implements
Auditability by Design. These models impose an interpretable first layer
that learns a linear basis subject to soft orthogonality constraints,
ensuring parts-based feature representations. This structural constraint
enables high-capacity encoders and decoders to guide the discovery of
optimal linear bases while retaining structural interpretability
(Carles-Bou and Carmona 2026; Otávio Becker 2023). Additionally, we
apply our Spectral Triage mechanism to systematically weight modality
contributions, mitigating the impact of noise-dominant views.

\section{Background}\label{background}

\subsection{Multi-View Representation
Learning}\label{multi-view-representation-learning}

Multi-view representation learning derives a unified latent space
\(\mathbf{U}\) that captures the shared variance across \(M\) distinct
data matrices \(\{\mathbf{X}_m\}_{m=1}^M\). This process identifies
view-specific transformations \(f_m(\mathbf{X}_m)\) that map each view
to \(\mathbf{U}\) via a shared similarity metric. Linear methods,
including generalized CCA and SiMLR, compute projection matrices
\(\mathbf{V}_m\), where the matrix elements directly quantify feature
contributions. In contrast, deep multi-view models parametrize \(f_m\)
as multilayer perceptrons (Sapkota et al. 2025; Zhao et al. 2024). While
these non-linear models capture complex data manifolds, they suffer from
the Information Masking problem; nested non-linearities obscure the
mathematical relationship between input features \(\mathbf{X}_m\) and
the latent space \(\mathbf{U}\) (Schennach and Gunsilius 2019; Chiueh
and Goodman 1988).

\subsection{Information Bottleneck and Structural
Interpretability}\label{information-bottleneck-and-structural-interpretability}

To resolve Information Masking and re-establish transparency in deep
multi-view learning, we enforce a mandatory linear projection
constraint, designated the \textbf{Only Linear Encoder Entry (OLEE)}.
The OLEE acts as an Information Bottleneck. It restricts the model's
representational capacity at the input layer:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Only Linear Encoder Entry (OLEE):} The model performs an
  initial, strictly linear transformation
  \(\mathbf{Z}_m = \mathbf{X}_m \mathbf{V}_m\). This constraint applies
  across our architectural taxonomy (LEND, NED, NEDPP).
\item
  \textbf{Orthonormal Basis and the Stiefel Manifold:} We restrict the
  projection matrix \(\mathbf{V}_m\) to the Stiefel manifold, defined by
  \(\mathbf{V}_m^\top \mathbf{V}_m = \mathbf{I}_K\). We enforce this
  constraint using \textbf{Non-negative Stiefel Approximating Flow
  (NSA-Flow)}, an optimization penalty that regularizes the linear
  encoding layer. This enforces the discovery of non-redundant,
  near-orthogonal features.
\item
  \textbf{Direct Feature Attribution:} By enforcing the OLEE, we
  guarantee that every downstream latent factor is an explicit linear
  combination of the input features \(\mathbf{X}_m\). The matrix
  \(\mathbf{V}_m\) operates as a globally interpretable weight matrix.
\end{enumerate}

This architecture ensures that interpretability is a structural
property. High-stakes clinical decision-making requires inherently
interpretable models (Rudin 2019). Existing post-hoc methods, such as
LIME (Ribeiro et al. 2016) and SHAP (Lundberg and Lee 2017), estimate
feature attribution by fitting local surrogate models to perturbed
inputs. These approximations lack stability, fail in high-dimensional
settings, and frequently fail to capture the true mechanics of complex
neural networks.

Our framework guarantees Auditability by Design. The weights within the
basis \(\mathbf{V}_m\) represent exact global feature importance
(Radulovic 2023). This structural property permits exact counterfactual
reasoning (Wachter et al. 2017). Because we map features linearly prior
to non-linear transformation, we compute the minimal input perturbation
required to shift the latent representation analytically.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-interpretability-gap.png}}

}

\caption{\label{fig-interpretability-gap}}

\end{figure}%

\subsection{Summary of Contributions}\label{summary-of-contributions}

We summarize our methodological contributions:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Solving Information Masking via OLEE:} We demonstrate the
  compatibility of deep representational capacity and mathematical
  transparency. Across LEND, NED, and NEDPP, enforcing an initial
  orthogonal linear projection provides analytically exact feature
  importance. This Information Bottleneck manages feature discovery,
  while downstream non-linear layers address manifold complexities.
\item
  \textbf{Spectral Triage and Robust Consensus:} We formulate a
  consensus mechanism utilizing \textbf{Spectral Sharpness} to identify
  and down-weight noise-dominant views. This \textbf{Modality Alignment
  Index (MAI)} stabilizes the shared representation by dynamically
  penalizing non-structured modalities.
\item
  \textbf{Manifold Regularization via NSA-Flow:} We apply
  \textbf{Non-negative Stiefel Approximating Flow (NSA-Flow)} to enforce
  approximate orthogonality on the linear encoding layer. This
  regularization prevents feature collapse and ensures each latent
  factor represents a statistically unique signal.
\item
  \textbf{Leave-One-Out (LOO) Topology:} We employ a
  \textbf{Leave-One-Out (LOO)} topology during consensus formation. By
  omitting each modality from its own target calculation, we prevent
  deep networks from memorizing modality-specific noise.
\item
  \textbf{Methodological Correctives for Model Selection:} We implement
  rigorous statistical criteria, including Tracy-Widom distributions,
  Bayesian Information Criterion (BIC), and the One-Standard-Error rule,
  for objective model validation.
\item
  \textbf{Shared-Private Disentanglement:} We formulate a shared-private
  partitioning architecture using cross-covariance penalties to isolate
  modality-specific idiosyncratic noise from the cross-modal consensus
  signal.
\item
  \textbf{Invertible Integration via Flow-SiMLR:} We introduce
  \textbf{Flow-SiMLR}, which embeds bijective Normalizing Flows directly
  into multi-view consensus discovery. By leveraging affine coupling
  layers, the architecture preserves exact mathematical invertibility,
  enabling joint Gaussian conditional inference for cross-view feature
  synthesis and clinical imputation.
\end{enumerate}

\subsection{Architectural Taxonomy}\label{architectural-taxonomy}

We evaluate this framework across four algorithmic implementations:

\begin{itemize}
\tightlist
\item
  {\textbf{SiMLR (Purely Linear - Blue):}} The strictly linear baseline,
  optimal for Gaussian data distributions.
\item
  {\textbf{LEND (Mixed Architecture - Green):}} A hybrid architecture
  coupling an OLEE-constrained linear encoder for feature discovery with
  a deep decoder for non-linear manifold mapping.
\item
  {\textbf{NED (Fully Nonlinear - Orange):}} A non-linear architecture
  that applies multi-layer perceptrons subsequent to the mandatory OLEE
  bottleneck.
\item
  {\textbf{NEDPP (Shared/Private - Purple):}} A disentangled
  architecture that explicitly separates the latent space into shared
  consensus and modality-specific private components.
\item
  {\textbf{Flow-SiMLR (Normalizing Flows - Teal):}} An invertible
  architecture utilizing normalizing flows to establish bijective,
  information-preserving coordinate transforms, enabling exact
  conditional inference and cross-view imputation.
\end{itemize}

Section 2 provides the mathematical definitions for the
joint-variational objective, OLEE, MAI, NSA-Flow, and the algorithmic
variants. Section 3 presents empirical evaluations of the
consistency-interpretability tradeoff using simulated benchmarks and a
clinical breast cancer (BRCA) cohort. Section 4 discusses implications
for explainable multi-omics integration and clinical translation.

\bookmarksetup{startatroot}

\chapter{Methods}\label{methods}

\section{Theoretical Foundation}\label{theoretical-foundation}

\subsection{The Multi-Modal Inverse
Problem}\label{the-multi-modal-inverse-problem}

We frame multi-modal integration as a highly structured inverse problem.
Each modality provides a partial, noisy observation of an underlying
high-dimensional manifold, which represents the true generative state of
the biological system. These observations reside within
modality-specific measurement domains (e.g., transcriptomics, clinical
phenotypes), each characterized by distinct signal-to-noise ratios and
domain-specific artifacts. The mathematical objective is to compute a
coherent, shared representation of the true state from these disparate
observations, isolating cross-modal consensus from idiosyncratic noise.

\subsection{OLEE as a Structural Information
Bottleneck}\label{olee-as-a-structural-information-bottleneck}

Following Tishby's Information Bottleneck theorem (Tishby et al. 2000),
standard multi-layer perceptrons (MLPs) process inputs via
\(\mathbf{Z} = \text{MLP}(\mathbf{X})\), which fundamentally entangles
the mutual information \(I(\mathbf{X}; \mathbf{Z})\) across successive
layers. While this enables high theoretical capacity, unconstrained deep
networks routinely memorize structured nuisance variables and
observational noise, leading to catastrophic representation collapse and
a failure to identify the true generative features.

We systematically resolve this entanglement by enforcing the Only Linear
Encoder Entry (OLEE) constraint, formulating the initial projection
\(\mathbf{Z}_m = \mathbf{X}_m \mathbf{V}_m\) as a rigorous, structural
information bottleneck. Because the dimensionality is strictly bounded
by \(k \ll d_m\) and the basis \(\mathbf{V}_m\) is maintained rigorously
orthogonal via optimization on the Stiefel manifold (Edelman et al.
1998), the mutual information \(I(\mathbf{X}_m; \mathbf{Z}_m)\) is
intrinsically constrained. OLEE forces the network to distill only the
most informative, non-redundant variance components that maximize
consensus alignment, actively discarding modality-specific noise before
non-linear entanglement can occur.

\subsection{Joint-Variational Optimization
Framework}\label{joint-variational-optimization-framework}

We introduce a generalized joint-variational optimization framework
unifying the Similarity-driven Multi-view Linear Reconstruction (SiMLR)
taxonomy.

For \(M\) modalities, let \(\mathbf{X}_m \in \mathbb{R}^{n \times d_m}\)
denote the input data matrix for modality \(m \in \{1, \dots, M\}\). We
optimize an encoder \(f_m: \mathbb{R}^{d_m} \to \mathbb{R}^k\) and a
decoder \(g_m: \mathbb{R}^k \to \mathbb{R}^{d_m}\). We define the latent
representation as
\(\mathbf{Z}_m = f_m(\mathbf{X}_m) \in \mathbb{R}^{n \times k}\) and the
reconstruction as \(\hat{\mathbf{X}}_m = g_m(\mathbf{Z}_m)\).

The global objective function \(\mathcal{L}\) is defined as:

\[
\mathcal{L}(\{f_m, g_m\}_{m=1}^M, \mathbf{U}) = \sum_{m=1}^M \left( \mathcal{L}_{\text{recon}}(\mathbf{X}_m, \hat{\mathbf{X}}_m) + \lambda_{\text{sim}} \mathcal{L}_{\text{align}}(\mathbf{Z}_m, \mathbf{U}_{\neq m}) + \gamma \mathcal{P}_{\text{NSA}}(\mathbf{V}_m) \right) + \mathcal{R}(\mathbf{Z})
\]

where: - \(\mathbf{U}_{\neq m}\) represents the consensus target derived
from all modalities except \(m\), enforced via the \textbf{Leave-One-Out
(LOO)} topology. - \(\mathcal{P}_{\text{NSA}}(\mathbf{V}_m)\) is the
\textbf{Non-negative Stiefel Approximating Flow (NSA-Flow)} penalty
applied to the linear basis \(\mathbf{V}_m\) to enforce orthogonality. -
\(\mathcal{R}(\mathbf{Z})\) defines joint regularization terms, such as
variance preservation and covariance penalization.

\section{Architectural Taxonomy}\label{architectural-taxonomy-1}

The joint-variational objective establishes a foundation for a modular
architectural taxonomy. We present four distinct algorithmic
implementations, each motivated by the limitations of the prior model,
progressively increasing representational capacity while strictly
maintaining the OLEE interpretability bottleneck.

\subsection{Classical SiMLR (Linear
Baseline)}\label{classical-simlr-linear-baseline}

The classical formulation provides a strictly linear baseline, assuming
the underlying manifold can be adequately mapped via Euclidean
projections.

\begin{itemize}
\tightlist
\item
  \textbf{Encoder:} \(f_m(\mathbf{X}_m) = \mathbf{X}_m \mathbf{V}_m\)
\item
  \textbf{Decoder:} \(g_m(\mathbf{Z}_m) = \mathbf{Z}_m \mathbf{W}_m\)
\end{itemize}

The linear basis \(\mathbf{V}_m\) is strictly regularized by NSA-Flow to
the Stiefel manifold. This enforces orthogonal feature discovery and
provides a fully interpretable, albeit capacity-limited, baseline.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-simlr.png}}

}

\caption{\label{fig-simlr}Classical SiMLR: Information flow for a linear
encoder and decoder. The basis \(\mathbf{V}_m\) acts as a structural
information bottleneck.}

\end{figure}%

\subsection{LEND (Linear Encoder, Deep
Decoder)}\label{lend-linear-encoder-deep-decoder}

While Classical SiMLR guarantees interpretability, a linear decoder
often fails to reconstruct highly non-linear observational spaces (e.g.,
raw pixel intensities or complex gene regulatory networks). LEND
addresses this by pairing the exact linear feature attribution of the
OLEE constraint with a deep, non-linear decoder.

\begin{itemize}
\tightlist
\item
  \textbf{Encoder:} \(f_m(\mathbf{X}_m) = \mathbf{X}_m \mathbf{V}_m\)
  (OLEE)
\item
  \textbf{Decoder:}
  \(g_m(\mathbf{Z}_m) = \text{MLP}_{\theta_m}(\mathbf{Z}_m)\)
\end{itemize}

LEND represents a Pareto-optimal operating point: it provides deep
manifold denoising during reconstruction without sacrificing the strict
mathematical auditability of the input features.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-lend.png}}

}

\caption{\label{fig-lend}LEND: OLEE-constrained linear encoder coupled
with a deep MLP decoder for non-linear manifold reconstruction.}

\end{figure}%

\subsection{Fully Deep NED (Non-linear Encoder
Decoder)}\label{fully-deep-ned-non-linear-encoder-decoder}

If the underlying biological signal is non-linearly embedded within the
feature space itself, LEND's linear bottleneck may drop critical
variance. NED mitigates this by applying a non-linear function to the
latent space strictly \emph{subsequent} to the initial OLEE constraint.

\begin{itemize}
\tightlist
\item
  \textbf{Encoder:}
  \(f_m(\mathbf{X}_m) = \text{MLP}_{\phi_m}(\mathbf{X}_m \mathbf{V}_m)\)
\item
  \textbf{Decoder:}
  \(g_m(\mathbf{Z}_m) = \text{MLP}_{\theta_m}(\mathbf{Z}_m)\)
\end{itemize}

This architecture provides maximal representational capacity. The
initial projection \(\mathbf{X}_m \mathbf{V}_m\) preserves the formal
Information Bottleneck, guaranteeing that all downstream non-linear
transformations are irrevocably grounded in an identifiable linear
subspace.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-ned.png}}

}

\caption{\label{fig-ned}NED: Multi-layer encoder subject to the initial
OLEE information bottleneck constraint, coupled with a deep MLP
decoder.}

\end{figure}%

\subsection{Shared-Private NEDPP (Disentangled
Discovery)}\label{shared-private-nedpp-disentangled-discovery}

Despite LOO consensus, highly expressive models like NED can still be
confounded if modality-specific idiosyncratic noise is massive enough to
dominate the optimization landscape. NEDPP resolves this by explicitly
partitioning the latent space, decoupling modality-specific variance
from the shared biological signal.

\begin{itemize}
\tightlist
\item
  \textbf{Encoder:}
  \(f_m(\mathbf{X}_m) = [\text{MLP}_{\phi_{m,\text{shared}}}(\mathbf{X}_m \mathbf{V}_{m,\text{shared}}) \parallel \text{MLP}_{\phi_{m,\text{private}}}(\mathbf{X}_m \mathbf{V}_{m,\text{private}})] = [\mathbf{S}_m \parallel \mathbf{P}_m]\)
\item
  \textbf{Decoder:}
  \(g_m(\mathbf{S}_m \parallel \mathbf{P}_m) = \text{MLP}_{\theta_m}(\mathbf{S}_m \parallel \mathbf{P}_m)\)
\end{itemize}

We enforce disentanglement via a cross-covariance penalty
\(\text{Cov}(\mathbf{S}_m, \mathbf{P}_m) \to \mathbf{0}\),
orthogonalizing the shared and private representations. Assuming
Gaussian-distributed latent variables, driving this penalty to zero
guarantees statistical independence between the subspaces. This
theoretical bound prevents high-variance artifacts from leaking into the
shared consensus, isolating the true cross-modal signal.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-nedpp.png}}

}

\caption{\label{fig-nedpp}NEDPP (Non-linear Encoder Decoder with Private
Partitions): Disentangled architecture utilizing OLEE constraints for
both shared and private subspaces. Incorporates cross-covariance
penalization for statistical independence.}

\end{figure}%

\subsection{Normalizing Flow SiMLR (Flow-SiMLR): Bijective Multimodal
Integration}\label{normalizing-flow-simlr-flow-simlr-bijective-multimodal-integration}

While the deep architectures (LEND, NED, NEDPP) increase representation
capacity, their projection bottlenecks are fundamentally lossy,
entangling features and losing fine-grained modality-specific
variations. Flow-SiMLR solves this by deploying bijective Normalizing
Flows (Rezende and Mohamed 2015; Dinh et al. 2016) to perform exact,
information-preserving coordinate transformations. Our normalizing flow
model is implemented natively in PyTorch, adapting design principles and
architectures from the Latent-Aligned Multiview Normalizing Flows (LAMNr
Flows) open-source library
(\href{https://github.com/ntustison/LAMNrFlows}{ntustison/LAMNrFlows}),
which focuses on exact log-likelihood maximization and consensus
alignment of multi-view spaces.

\subsubsection{1. Invertible Affine Coupling
Formulation}\label{invertible-affine-coupling-formulation}

Each view \(m\) is modeled via an invertible mapping
\(f_m: \mathbb{R}^{d_m} \to \mathbb{R}^{d_m}\) composed of a sequence of
affine coupling layers. For input \(x \in \mathbb{R}^{d_m}\), a coupling
layer splits features using a binary mask \(b \in \{0, 1\}^{d_m}\) and
maps them as: \[z_{1} = b \odot x\]
\[z_{2} = (1 - b) \odot \left( x \odot e^{s(z_{1})} + t(z_{1}) \right)\]
where \(s\) and \(t\) are scaling and translation networks (MLPs). To
ensure mathematical stability and prevent gradient explosion, scale
outputs are bounded using:
\[s(z_{1}) = \text{scale\_bound} \times \tanh\left(s_{\text{net}}(z_{1})\right)\]
The inverse transformation is analytically exact and requires no network
inversion: \[x_{1} = b \odot z\]
\[x_{2} = (1 - b) \odot \left( (z - t(z_{1})) \odot e^{-s(z_{1})} \right)\]
The log-Jacobian determinant for a single coupling layer is:
\[\log |\det J| = \sum_{j: b_j = 0} s_j(z_{1})\]

\subsubsection{2. Shared-Private Bottleneck \& Hybrid
Loss}\label{shared-private-bottleneck-hybrid-loss}

Normalizing flows preserve input dimensions. To implement a
low-dimensional consensus bottleneck \(k \ll d_m\), we partition the
latent coordinates into shared and private subspaces:
\[\mathbf{Z}_m = f_m(\mathbf{X}_m) \quad \text{where} \quad \mathbf{Z}_{m,\text{shared}} = \mathbf{Z}_{m, 1:k}, \quad \mathbf{Z}_{m,\text{private}} = \mathbf{Z}_{m, k+1:d_m}\]
Alignment optimization guides the shared components
\(\mathbf{Z}_{m,\text{shared}}\) toward the consensus target
\(\mathbf{U}_{\neq m}\). To force the flow to pack the essential
reconstruction information into these first \(k\) dimensions, we define
the decoder wrapper using zero-padding:
\[\hat{\mathbf{X}}_m = f_m^{-1}\left([\mathbf{Z}_{m,\text{shared}} \parallel \mathbf{0}]\right)\]
This yields a hybrid objective function:
\[\mathcal{L}_{\text{Flow-SiMLR}} = \beta \sum_{m=1}^M \mathcal{L}_{\text{NLL}}(\mathbf{X}_m) + \sum_{m=1}^M \mathcal{L}_{\text{align}}(\mathbf{Z}_{m,\text{shared}}, \mathbf{U}_{\neq m}) + \gamma \sum_{m=1}^M \mathcal{L}_{\text{MSE}}(\mathbf{X}_m, \hat{\mathbf{X}}_m)\]
where \(\mathcal{L}_{\text{NLL}}\) is the negative log-prior density
under a standard multivariate Gaussian:
\[\mathcal{L}_{\text{NLL}}(\mathbf{X}_m) = - \mathbb{E}_{x \sim \mathbf{X}_m} \left[ \log p_Z(f_m(x)) + \log |\det J_{f_m}(x)| \right]\]
with \(\log p_Z(z) = -\frac{1}{2} \|z\|_2^2 - \frac{d_m}{2}\log(2\pi)\).
The scaling factors \(\beta\) (default \(0.05\)) and \(\gamma\) (default
\(2.0\)) balance density maximization, alignment, and low-dimensional
reconstruction fidelity.

\subsubsection{3. Joint Gaussian Conditional
Inference}\label{joint-gaussian-conditional-inference}

Because normalizing flows transform complex distributions into Gaussian
latent representations, we parameterize the concatenated shared latent
space across all views as a joint multivariate Gaussian distribution:
\[\mathbf{Z}_{\text{joint}} = \left[\mathbf{Z}_{1,\text{shared}} \parallel \mathbf{Z}_{2,\text{shared}} \parallel \dots \parallel \mathbf{Z}_{M,\text{shared}}\right] \sim \mathcal{N}(\mu, \Sigma)\]
For any observed view \(A\) and unobserved target view \(B\), we
partition the joint mean vector and covariance matrix:
\[\mu = \begin{pmatrix} \mu_A \\ \mu_B \end{pmatrix}, \quad \Sigma = \begin{pmatrix} \Sigma_{AA} & \Sigma_{AB} \\ \Sigma_{BA} & \Sigma_{BB} \end{pmatrix}\]
Using the Schur complement, the exact conditional latent mean of view
\(B\) given observed latent view \(A\) is:
\[\mu_{B|A} = \mu_B + \Sigma_{BA} \Sigma_{AA}^{-1} \left(\mathbf{Z}_{A,\text{shared}} - \mu_A\right)\]
We solve this linear system efficiently using a Cholesky solver.
Finally, we pass the conditional latent coordinates through the inverse
flow decoder of view \(B\) to synthesize its features:
\[\hat{\mathbf{X}}_B = f_B^{-1}\left([\mu_{B|A} \parallel \mathbf{0}]\right)\]
This enables exact, mathematically principled cross-view imputation and
counterfactual clinical synthesis.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{figures/fig-flow-simlr.png}}

}

\caption{\label{fig-flow-simlr}Flow-SiMLR: Normalizing flow
architecture. The bijective flow maps inputs to a joint Gaussian latent
space. The first \(k\) dimensions are aligned with the shared cross-view
consensus, while the remaining dimensions act as an implicit private
partition. Padded decoding and Gaussian conditioning enable exact
reconstruction and cross-view synthesis.}

\end{figure}%

\section{Optimization, Consensus, and Spectral
Triage}\label{optimization-consensus-and-spectral-triage}

With the architectural models defined, we now detail the optimization
strategy, the consensus formation, and the automated mechanisms required
to stabilize deep multi-modal alignment.

\subsection{Block-Coordinate Descent and LOO
Topology}\label{block-coordinate-descent-and-loo-topology}

We rigidly formalize our parameter optimization through a strict
Block-Coordinate Descent (BCD) procedure. At each iteration \(t\), we
decouple the learning process into two distinct phases:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Consensus Formation (LOO Topology):} We fix the network
  parameters \(\{f_m, g_m\}\) and compute the consensus targets
  \(\mathbf{U}_{\neq m}\) using a strictly enforced Leave-One-Out (LOO)
  topology:
  \[ \mathbf{U}_{\neq m}^{(t)} = \text{Consensus}(\{\mathbf{Z}_i^{(t-1)}\}_{i \neq m}) \]
  The LOO topology explicitly excludes modality \(m\) from calculating
  its own target. This architectural constraint actively prevents
  high-capacity networks from memorizing trivial identity mappings,
  rigorously forcing the model to discover universally shared
  cross-modal signals.
\item
  \textbf{Parameter Update:} We fix the derived consensus
  \(\mathbf{U}_{\neq m}^{(t)}\) and globally minimize \(\mathcal{L}\)
  for each specific modality:
  \[ \{f_m^{(t)}, g_m^{(t)}\} = \arg\min_{f_m, g_m} \mathcal{L}(\{f_m, g_m\}, \mathbf{U}_{\neq m}^{(t)}) \]
\end{enumerate}

\subsection{Orthogonal Manifold Optimization via
NSA-Flow}\label{orthogonal-manifold-optimization-via-nsa-flow}

Enforcing exact orthogonality via traditional Singular Value
Decomposition (SVD) imposes a severe \(\mathcal{O}(K^3)\) computational
bottleneck and injects non-differentiable discontinuities into the
optimization trajectory. We conclusively bypass this limitation by
executing gradient descent directly on the Stiefel manifold
\(\mathbb{V}_{k,d_m} = \{ \mathbf{V} \in \mathbb{R}^{d_m \times k} \mid \mathbf{V}^\top \mathbf{V} = \mathbf{I}_k \}\)
(Edelman et al. 1998).

We achieve this by coupling the NSA-Flow penalty with Newton-Schulz
iterations. Employing the iterative update rule
\(\mathbf{V}_{t+1} = \frac{1}{2} \mathbf{V}_t (3\mathbf{I} - \mathbf{V}_t^\top \mathbf{V}_t)\)
drives quadratic convergence to the Stiefel manifold utilizing strictly
batched matrix multiplications, aggressively reducing computational
complexity to a highly scalable \(\mathcal{O}(d_m K^2)\). NSA-Flow
replaces hard SVD projections with a smooth, fully differentiable
penalty, mathematically guaranteeing that the BCD procedure
monotonically decreases the global objective without risking mode
collapse.

\subsection{Similarity Metrics (The Energy
Function)}\label{similarity-metrics-the-energy-function}

To operationalize the alignment \(\mathcal{L}_{\text{align}}\), we
implement multiple distinct similarity metrics (referred to as the
``energy'' of the consensus), each possessing specific theoretical
advantages depending on the noise distribution of the data:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Regression:} Minimizes the Mean Squared Error (MSE) between
  the normalized latent representations and the consensus target. This
  assumes Gaussian-distributed alignment errors and serves as an
  effective baseline for stable manifolds.
\item
  \textbf{Absolute Canonical Covariance (ACC):} Maximizes the
  unnormalized inner product with the consensus. ACC theoretically
  assumes a uniform signal magnitude across views, making it optimal
  when variances are precisely controlled and uniform.
\item
  \textbf{Normalized Covariance (NC):} Dynamically scales latent
  representations to unit variance prior to alignment. This prevents
  ``Modality Starvation''---where a low-variance modality is ignored by
  the consensus---ensuring that weak but informative signals contribute
  proportionally.
\item
  \textbf{Log-Cosh:} A robust, approximation of Independent Component
  Analysis (ICA) objectives. Log-Cosh bounds the influence of extreme
  outliers, providing superior cross-modal alignment when dealing with
  heavy-tailed clinical noise distributions.
\end{enumerate}

\subsection{Spectral Triage and Modality Alignment Index
(MAI)}\label{spectral-triage-and-modality-alignment-index-mai}

In high-dimensional limits, isotropic noise routinely forms spurious
correlations with the shared consensus. We introduce \textbf{Spectral
Triage} to rigorously detect and actively penalize these noise-dominant
views. We quantify modality fidelity using the \textbf{Modality
Alignment Index (MAI)}.

The default MAI formulation leverages Procrustes \(R^2\):
\[ \text{MAI}_m = 1 - \frac{\|\mathbf{Z}_m \mathbf{\Omega} - \mathbf{U}_{\neq m}\|_F^2}{\|\mathbf{U}_{\neq m}\|_F^2} \]
where
\(\mathbf{\Omega} = \arg\min_{\mathbf{\Omega}^\top \mathbf{\Omega} = \mathbf{I}} \|\mathbf{Z}_m \mathbf{\Omega} - \mathbf{U}_{\neq m}\|_F\)
denotes the optimal orthogonal rotation to align the local manifold with
the global consensus.

To eliminate spurious alignments, we augment the MAI by integrating
\textbf{Spectral Sharpness} \(\mathcal{S}_m\), which evaluates the
concentration of the singular values \(\sigma_i\) extracted from the
latent matrix \(\mathbf{Z}_m\):
\[ \mathcal{S}_m = \frac{\sigma_1}{\sum_{i=1}^k \sigma_i} \]

\textbf{The Marchenko-Pastur Limit and BBP Phase Transition:} This
formulation is grounded in the spectral theory of high-dimensional
random matrices. Under the assumption of purely isotropic observational
noise, the sample covariance matrix spectrum converges to the
Marchenko-Pastur bulk distribution limit. Consequently, the singular
values distribute uniformly, bounding the spectral sharpness to the bulk
limit \(\mathcal{S}_m = \mathcal{O}(1/K)\). In this regime, the metric
mathematically drives the contribution of unstructured isotropic noise
to exactly zero.

Conversely, following the Baik-Ben Arous-Péché (BBP) phase transition
theorem (Baik et al. 2005), true underlying signal components induce
rank-1 perturbations that spike explicitly outside the Marchenko-Pastur
bulk, rapidly forcing \(\mathcal{S}_m \to 1\). Spectral Sharpness
therefore functions as a mathematically exact threshold, actively
discriminating structured generative signal from isotropic background
noise. The final consensus target employs the product of MAI and
Spectral Sharpness to dynamically weight each modality, ensuring
noise-dominant views are decisively quarantined.

\subsection{Delayed Dynamic Weight Start (Gating
Warmup)}\label{delayed-dynamic-weight-start-gating-warmup}

When applying dynamic weights (\(w_m\)) to Normalizing Flow networks or
models with linear encoder layers (like Flow-SiMLR-V), initiating the
competitive gating update at epoch 0 can trigger a catastrophic positive
feedback loop. Early in training, the linear projection matrices
\(\mathbf{V}_m\) and bijective flow transformations are random,
producing noisy latents \(\mathbf{Z}_m\) and low MAI values. Softmax
competition:
\[ w_m^{(t)} = \text{softmax}(\tau \cdot \text{MAI}_m^{(t)}) \]
amplifies minor initialization variances, prematurely driving the
weights of valid but slow-to-converge views to zero. Once a modality's
weight approaches zero, its parameters stop receiving gradient updates,
locking the model into a collapsed state (Weight Collapse).

To resolve this instability, we introduce a \textbf{Delayed Dynamic
Weight Start} (gating warmup). We define the gating scheduler
\(\theta(t)\) at training epoch \(t\) as: \[ w_m^{(t)} = \begin{cases} 
\frac{1}{M} & \text{for } t < T_{\text{delayed}} \\
\text{softmax}(\tau \cdot \text{MAI}_m^{(t)}) & \text{for } t \ge T_{\text{delayed}}
\end{cases} \] By setting the weights to be uniform for the first
\(T_{\text{delayed}}\) epochs, the model is forced to train all
projections and flows cooperatively. Gating is activated only after the
network has established stable coordinate mappings, enabling smooth and
robust convergence to optimal weights.

\section{Properties \& Bounds}\label{properties-bounds}

\subsection{Auditability by Design and Exact
Counterfactuals}\label{auditability-by-design-and-exact-counterfactuals}

Standard post-hoc explainability methods (e.g., SHAP, LIME) are
notoriously unstable on entangled deep manifolds, frequently outputting
approximations that contradict the true mechanistic model. By enforcing
the OLEE constraint, SiMLR bypasses post-hoc approximations entirely.
The network is explicitly auditable by design, establishing three
rigorous theoretical properties:

\textbf{1. Exact Global Feature Importance via Variance Partitioning:}
Because NSA-Flow strictly confines the basis matrix \(\mathbf{V}_m\) to
the Stiefel manifold
(\(\mathbf{V}_m^\top \mathbf{V}_m = \mathbf{I}_k\)), the initial mapping
acts as an isometry. This structural rigor ensures that the total
variance explained by the model can be exactly partitioned among the
columns of \(\mathbf{X}_m\), providing an analytically exact,
non-redundant measure of global feature importance that cannot be
confounded by latent collinearities.

\textbf{2. Exact Local Interpretability:} For any individual sample
\(i\), the computed latent coordinate \(\mathbf{z}_{i}\) is explicitly
constructed via the linear combination of its raw input features:
\(\mathbf{z}_{i} = \mathbf{x}_{i} \mathbf{V}_m\). We extract local,
sample-specific feature attributions with zero approximation error.

\textbf{3. Analytically Exact, Minimum-Norm Counterfactuals:} In
post-hoc paradigms, off-manifold counterfactual perturbations often
generate nonsensical predictions. Conversely, OLEE provides a
closed-form analytic solution. Because \(\mathbf{V}_m\) is rigorously
orthogonal, its Moore-Penrose pseudoinverse simplifies exactly to its
transpose:
\(\mathbf{V}_m^+ = (\mathbf{V}_m^\top \mathbf{V}_m)^{-1} \mathbf{V}_m^\top = \mathbf{I}_k^{-1} \mathbf{V}_m^\top = \mathbf{V}_m^\top\).

Therefore, the exact, minimum-norm counterfactual perturbation
\(\delta \mathbf{x}\) required to induce a targeted latent shift
\(\Delta \mathbf{z}\) is formally:
\[ \delta \mathbf{x} = \Delta \mathbf{z} \mathbf{V}_m^\top \] This
guarantees that the proposed perturbation represents the most direct,
efficient intervention possible without relying on unstable surrogate
models.

\subsection{The Consistency-Interpretability
Tradeoff}\label{the-consistency-interpretability-tradeoff}

We define the tension between representational capacity and auditability
as the Consistency-Interpretability Tradeoff. Fully non-linear models
maximize latent recovery by approximating complex functions but obscure
the interpretability of derived features. LEND enforces the OLEE
constraint for feature discovery while utilizing non-linear decoders,
optimally balancing this tradeoff.

\subsection{Theoretical Bounds: The 1/M
Law}\label{theoretical-bounds-the-1m-law}

We formalize the variance of the shared consensus estimator under noise.

\textbf{Generative Assumptions:} We assume each modality observation
\(\mathbf{X}_m\) is generated by a shared true manifold embedded in
additive Gaussian noise.

\textbf{Mathematical Formulation:} Let the noise variance be
\(\sigma^2\) and the cross-modal noise correlation be \(\rho\).
Aggregating observations across \(M\) modalities yields the variance of
the consensus estimator \(\mathbf{U}\):
\[ \text{Var}(\mathbf{U}) = \frac{\sigma^2}{M} (1 - \rho) + \rho \sigma^2 \]
As \(M \to \infty\), the independent noise term
\(\frac{\sigma^2}{M}(1-\rho)\) vanishes. Consequently, the irreducible
error floor is strictly bounded by \(\rho \sigma^2\). This mathematical
bound proves that while expanding the number of modalities \(M\)
efficiently mitigates independent noise, it cannot resolve highly
correlated cross-modal artifacts, necessitating the LOO topology and
Spectral Triage to actively suppress correlated noise components.

\section{Evaluation Strategies}\label{evaluation-strategies}

\subsection{Technical Glossary of Performance
Metrics}\label{technical-glossary-of-performance-metrics}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Metric
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Symbol
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Definition
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Interpretation
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Strictly Linear Accuracy} & \(R^2_{\mathbf{XV}}\) &
\(R^2_P(\mathbf{X} \mathbf{V}, \mathbf{U}^*)\) & Fidelity of the linear
feature projection. \\
\textbf{Deep Consensus Accuracy} & \(R^2_{\mathbf{U}}\) (CMC) &
\(\max_{\mathbf{\Omega}, s} \left( 1 - \frac{\|\mathbf{\hat{U}}\mathbf{\Omega} s - \mathbf{U}^*\|_F^2}{\|\mathbf{U}^*\|_F^2} \right)\)
& Fidelity of the shared latent consensus recovery. \\
\textbf{Subspace Recovery Error} & \(SRE\) &
\(1 - \frac{1}{M} \sum_{m=1}^M R^2_P(\mathbf{\hat{V}}_m, \mathbf{V}^*_m)\)
& Error in recovering the true generative feature basis. \\
\textbf{OLEE} & - &
\(\mathbf{Z} = \sigma(\mathbf{X} \mathbf{V} \mathbf{W} + \mathbf{b})\) &
Initial linear projection acting as an Information Bottleneck. \\
\textbf{Procrustes \(R^2\)} & \(R^2_P\) &
\(1 - \frac{\min_{\mathbf{\Omega}} \|\mathbf{\hat{A}}\mathbf{\Omega} - \mathbf{A}^*\|_F^2}{\|\mathbf{A}^*\|_F^2}\)
& Alignment-invariant variance explained. \\
\textbf{Auditability by Design} & - & - & Structural guarantee linking
latent variables directly to features. \\
\end{longtable}
}

\subsection{Statistical Determination of Intrinsic Dimensionality
(K)}\label{statistical-determination-of-intrinsic-dimensionality-k}

We implement three statistical strategies to establish the optimal
latent dimensionality \(K\): 1. \textbf{Information Criteria (BIC):}
Evaluates the Bayesian Information Criterion to penalize excessive model
parameterization. 2. \textbf{Spectral Truncation (Tracy-Widom):}
Computes the statistical significance of singular values against the
null hypothesis of purely unstructured noise. 3. \textbf{V-fold
Cross-Validation:} Selects \(K\) by applying the One-Standard-Error Rule
to out-of-sample prediction performance.

\bookmarksetup{startatroot}

\chapter{Experiments}\label{experiments}

\section{Reproducibility Protocol and Experimental
Setup}\label{reproducibility-protocol-and-experimental-setup}

\subsection{Data Regimes and
Objectives}\label{data-regimes-and-objectives}

To evaluate the architectures rigorously, we utilize four distinct data
regimes. These regimes benchmark specific properties spanning synthetic
manifolds, tabular clinical datasets, and high-dimensional omics data.
This diverse set reflects the application areas of neuroimaging,
blast-exposure studies, and multi-omics integration ({Stone et al.}
2024; Avants et al. 2021):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Synthetic Data}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Purpose:} Controlled validation of architecture-specific
    latent discovery under defined manifold topologies (Linear,
    Polynomial, Sine, Private Noise).
  \item
    \textbf{Prediction Target:} Continuous response variable generated
    from the ground-truth latent coordinates. We emphasize that
    correlation does not imply causation; predictive capacity here
    reflects an association between observables and the target,
    necessitating interventional studies to claim causality (Pearl
    2009).
  \item
    \textbf{Why Interpretability Matters:} Allows exact quantification
    of ground-truth recovery via the first-layer linear basis, proving
    that deep consensus does not obscure mechanistic paths.
  \end{itemize}
\item
  \textbf{Heart Disease (Clinical)}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Purpose:} Evaluation on a standard, low-dimensional tabular
    clinical dataset with categorical and continuous features (Detrano
    et al. 1989).
  \item
    \textbf{Prediction Target:} Binary classification of heart disease
    presence.
  \item
    \textbf{Why Interpretability Matters:} In clinical diagnostics,
    assigning transparent risk scores to demographic and physiological
    features is legally and ethically required for trust (Rudin 2019;
    Biswas 2025).
  \end{itemize}
\item
  \textbf{Diabetes Progression (Clinical)}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Purpose:} Continuous risk stratification using baseline
    clinical indicators and blood serum measurements (Efron et al.
    2004).
  \item
    \textbf{Prediction Target:} Quantitative measure of disease
    progression one year post-baseline.
  \item
    \textbf{Why Interpretability Matters:} Identifying precise
    directional impacts of specific biomarkers enables personalized
    intervention strategies and provides an auditable trail for medical
    decisions (Thakur 2025; Wachter et al. 2017).
  \end{itemize}
\item
  \textbf{BRCA Multi-Omics (Biological Discovery)}

  \begin{itemize}
  \tightlist
  \item
    \textbf{Purpose:} High-dimensional, multi-modal integration
    (RNA-Seq, CNV, Proteomics) to discover complex biological drivers
    ({``Comprehensive Molecular Portraits of Human Breast Tumours''}
    2012; Sathyanarayanan 2023).
  \item
    \textbf{Prediction Target:} Estrogen Receptor (ER) Status.
  \item
    \textbf{Why Interpretability Matters:} Mechanistic transparency is
    essential to trace abstract multi-omics consensus back to actionable
    genetic or proteomic targets (El-Hassan 2023).
  \end{itemize}
\end{enumerate}

For reproducibility, we fix the seed (42) across the \textbf{Optimized
Benchmark Suite}. We train deep learning models using Adam (Kingma and
Ba 2014) or stochastic gradient descent (SGD) (Bottou 2010). The suite
evaluates 4 architectures (SiMLR, LEND, NED, NEDPP), 4 loss functions
(Regression, ACC, Log-Cosh, NC), and 4 consensus methods (Newton, SVD,
PCA, ICA).

For clinical tasks (Heart, Diabetes, BRCA), we determine the latent
basis size \(K\) empirically via 5-fold Cross-Validation (CV) (Stone
1974; Hastie et al. 2009). This sizes the representational bottleneck,
preventing over-parameterization while maximizing predictive capacity.
This empirical cross-validation satisfies the ``Statistical
Determination of the Intrinsic Dimensionality (\(K\))'' criteria
(Section 2), ensuring the chosen \(K\) separates from noise.

The benchmark enforces the following constraints: - \textbf{Near
Orthogonality:} NSA-Flow enabled with a stiffness parameter \(w=0.5\). -
\textbf{Parsimonious Sparsity:} A sparseness quantile of 0.5 applied to
the first-layer basis. - \textbf{Strict Positivity:} All weights
constrained to be non-negative, enforcing additive biomarker discovery.

We report Strictly Linear Accuracy (\(R^2_{\mathbf{X}\mathbf{V}}\)) as
the primary metric for the interpretability-performance trade-off
(Doshi-Velez and Kim 2018; Lipton 2018). We aggregate results over
\(N=20\) independent seeds for synthetic data and \(N=10\) for clinical
data. This sample size (\(N\)) provides sufficient power to identify
medium-to-large effect sizes without inflating the false discovery rate
(Cohen 1992).

We compute \(R^2_{\mathbf{X}\mathbf{V}}\) by averaging recovery fidelity
across all modalities.

Crucially, we extract the \(\mathbf{V}\) matrix utilized for prediction
and evaluation strictly post-sparseness and post-Stiefel constraint.
This ensures we evaluate the interpretable, constrained features
directly.

\subsection{Interpretation of Generative
Regimes}\label{interpretation-of-generative-regimes}

We evaluate architectures across four distinct manifold structures.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03_experiments_files/figure-pdf/fig-generative-shapes-output-1.pdf}}

}

\caption{\label{fig-generative-shapes}The Generative Landscape.
Visualization of the mapping from a 1D latent coordinate \(\mathbf{U}\)
to observable features \(\mathbf{X}\). Baseline (Linear) demonstrates
pure proportionality (A). Non-linear regimes (B-Polynomial, C-Sine) test
higher-order and periodic interactions. Proposed private noise mapping
(D) tests robustness to view-specific interference. Takeaway: Deep
manifold learning resolves structural interference where standard linear
projections fail.}

\end{figure}%

Figure~\ref{fig-generative-shapes} utilizes a four-panel layout. By
plotting the 1D latent coordinate \(\mathbf{U}\) against the observable
feature space \(\mathbf{X}\), we illustrate the mathematical
relationships discussed in Section 2. Synthetic features incorporate
Gaussian additive noise and structured, non-Gaussian interference
(Private Noise) to simulate realistic biological variability (Hastie et
al. 2009). The progression from linearity (A) to structured private
noise (D) defines the architectural challenge. Standard linear methods
exhibit diminished performance under non-linearity, whereas deep
architectures naturally disentangle complex latent generative factors
(Bengio et al. 2013; Goodfellow et al. 2016).

\section{Performance Matrix Summary}\label{performance-matrix-summary}

\subsection{Synthetic Benchmark
Results}\label{synthetic-benchmark-results}

The synthetic benchmarking suite provides a controlled environment to
test whether deep architectural regularizers improve the recovery of
linear latent structures. We evaluate models across four manifold
topologies (Linear, Polynomial, Sine, Private Noise). As shown in
Table~\ref{tbl-synthetic-summary}, Strictly Linear Accuracy
(\(R^2_{\mathbf{X}\mathbf{V}}\)) measures the signal captured by the
auditable first layer. The results confirm the hypothesis. The baseline
(SiMLR) performs optimally in the Linear regime. Proposed deep
architectures (NED, NEDPP) yield superior performance in non-linear
regimes (Sine, Polynomial), where the baseline linear projection fails
to capture periodic or higher-order variance.

Table~\ref{tbl-synthetic-summary} summarizes model performance across
synthetic regimes, focusing on the recovery of ground-truth structure
via the strictly linear basis.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1400}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1800}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1300}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1300}}
  >{\raggedright\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1300}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 12\tabcolsep) * \real{0.1400}}@{}}
\caption{Synthetic Benchmark Summary. Baseline (SiMLR) versus Proposed
Architectures (LEND, NED, NEDPP). Mean ± SD and Peak Performance based
on Strictly Linear Accuracy (\(R^2_{\mathbf{X}\mathbf{V}}\)). Results
aggregate \(N=1280\) tasks. Deep architectures consistently outperform
the linear baseline in recovering structure from non-linear generative
regimes (Polynomial, Sine, Private
Noise).}\label{tbl-synthetic-summary}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Regime
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Avg XV R2 ± SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Avg V Rec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Best Loss
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Best Cons
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Peak XV R2
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Regime
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Avg XV R2 ± SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Avg V Rec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Best Loss
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Best Cons
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Peak XV R2
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Linear & SiMLR & 0.782 ± 0.029 & 0.0317853 & acc & svd & 0.782241 \\
Linear & LEND & 0.794 ± 0.021 & 0.552253 & logcosh & svd & 0.796386 \\
Linear & NED & 0.793 ± 0.021 & 0.557274 & acc & pca & 0.795817 \\
Linear & NEDPP & 0.794 ± 0.020 & 0.560251 & acc & pca & 0.796051 \\
Linear & Flow-SiMLR-V & 0.792 ± 0.021 & 0.408423 & regression & newton &
0.795513 \\
Polynomial & SiMLR & 0.776 ± 0.013 & 0.120952 & acc & svd & 0.777125 \\
Polynomial & LEND & 0.782 ± 0.018 & 0.260374 & nc & svd & 0.788584 \\
Polynomial & NED & 0.783 ± 0.018 & 0.276212 & acc & ica & 0.789494 \\
Polynomial & NEDPP & 0.784 ± 0.018 & 0.273627 & nc & newton &
0.789423 \\
Polynomial & Flow-SiMLR-V & 0.782 ± 0.018 & 0.288904 & nc & ica &
0.786846 \\
Private Noise & SiMLR & 0.698 ± 0.103 & 0.0153506 & acc & newton &
0.706666 \\
Private Noise & LEND & 0.787 ± 0.022 & 0.448156 & regression & svd &
0.789517 \\
Private Noise & NED & 0.787 ± 0.022 & 0.431954 & acc & newton &
0.790339 \\
Private Noise & NEDPP & 0.788 ± 0.023 & 0.422213 & regression & ica &
0.789784 \\
Private Noise & Flow-SiMLR-V & 0.788 ± 0.022 & 0.412438 & acc & svd &
0.790847 \\
Sine & SiMLR & 0.113 ± 0.053 & 0.0155337 & logcosh & pca & 0.114139 \\
Sine & LEND & 0.122 ± 0.052 & 0.0613472 & nc & pca & 0.155492 \\
Sine & NED & 0.142 ± 0.043 & 0.0583851 & nc & svd & 0.151929 \\
Sine & NEDPP & 0.148 ± 0.042 & 0.0571347 & acc & pca & 0.170228 \\
Sine & Flow-SiMLR-V & 0.145 ± 0.048 & 0.0572587 & acc & pca &
0.159191 \\
\end{longtable}

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig_v21_global_landscape.png}

}

\caption{\label{fig-v21-global-landscape}Global Performance Landscape.
Summary of Strictly Linear Accuracy (\(R^2_{\mathbf{X}\mathbf{V}}\))
across synthetic regimes. Baseline: SiMLR (Blue). Proposed Methods:
LEND, NED, NEDPP. Deep architectures maintain higher linear accuracy in
non-linear regimes, proving that deep representational capacity
facilitates robust linear projections (Hornik et al. 1989).}

\end{figure}%

\subsubsection{Global Architectural
Robustness}\label{global-architectural-robustness}

We investigate global configuration stability to identify a multi-modal
integration standard invariant to data topology. This robustness
analysis aggregates performance across all \(N=1280\) tasks.
Table~\ref{tbl-global-robustness} ranks the configurations. The
combination of the NEDPP architecture with Log-Cosh loss and
Newton-Schulz consensus consistently places in the top-performing
quintile. This stability is statistically significant, evidenced by a
low standard deviation (SD) relative to the mean
\(R^2_{\mathbf{X}\mathbf{V}}\). These configurations are robust against
the optimization noise typical of stochastic deep learning.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1628}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1395}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1512}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2209}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1628}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1628}}@{}}
\caption{Global Robustness Ranking. Baseline vs.~Proposed methods ranked
by mean Strictly Linear Accuracy (\(R^2_{\mathbf{X}\mathbf{V}}\)) across
all regimes. The proposed NEDPP architecture with Log-Cosh loss and
Newton-Schulz consensus provides the most stable structural
recovery.}\label{tbl-global-robustness}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Loss
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Consensus
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Mean XV R2 ± SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mean V Rec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mean U Rec
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Loss
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Consensus
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Mean XV R2 ± SD
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mean V Rec
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Mean U Rec
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
NEDPP & ACC & PCA & 0.635 ± 0.276 & 0.317 & 0.263 \\
Flow-SiMLR-V & ACC & SVD & 0.632 ± 0.282 & 0.314 & 0.316 \\
Flow-SiMLR-V & ACC & PCA & 0.632 ± 0.282 & 0.308 & 0.264 \\
NEDPP & NC & ICA & 0.632 ± 0.283 & 0.339 & 0.386 \\
LEND & NC & SVD & 0.631 ± 0.284 & 0.319 & 0.473 \\
LEND & NC & PCA & 0.631 ± 0.283 & 0.325 & 0.436 \\
NEDPP & REGRESSION & ICA & 0.631 ± 0.286 & 0.332 & 0.373 \\
LEND & REGRESSION & SVD & 0.631 ± 0.285 & 0.322 & 0.444 \\
Flow-SiMLR-V & NC & SVD & 0.630 ± 0.284 & 0.32 & 0.367 \\
NED & NC & SVD & 0.630 ± 0.285 & 0.332 & 0.264 \\
\end{longtable}

\subsubsection{Consensus and Loss Sensitivity
Analysis}\label{consensus-and-loss-sensitivity-analysis}

Alignment strategy and objective function selection are critical priors.
As Table~\ref{tbl-consensus-breakdown} details, the architecture
demonstrates robustness to alignment strategy. All consensus methods
(Newton, SVD, PCA, ICA) yield highly comparable basis representations.
The learned linear basis \(\mathbf{V}\) is a robust structural feature
of the data, not a brittle artifact of the optimization method.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1892}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2027}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2027}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2027}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2027}}@{}}
\caption{Architectural Sensitivity to Alignment Strategy. Baseline
vs.~Proposed consensus algorithms. Aggregate Strictly Linear Accuracy
(\(R^2_{\mathbf{X}\mathbf{V}}\)) stratified by consensus method. The
\(\mathbf{X}\mathbf{V}\) projection remains robust across consensus
algorithms, proving structural stability in the learned linear
basis.}\label{tbl-consensus-breakdown}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ICA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
NEWTON
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
PCA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
SVD
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
ICA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
NEWTON
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
PCA
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
SVD
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Flow-SiMLR-V & 0.626 ± 0.280 & 0.624 ± 0.288 & 0.628 ± 0.279 & 0.629 ±
0.278 \\
LEND & 0.620 ± 0.294 & 0.619 ± 0.291 & 0.623 ± 0.291 & 0.623 ± 0.291 \\
NED & 0.626 ± 0.284 & 0.626 ± 0.283 & 0.626 ± 0.282 & 0.628 ± 0.283 \\
NEDPP & 0.629 ± 0.281 & 0.627 ± 0.283 & 0.630 ± 0.277 & 0.628 ± 0.282 \\
SiMLR & 0.592 ± 0.287 & 0.593 ± 0.287 & 0.593 ± 0.287 & 0.593 ± 0.287 \\
\end{longtable}

Iterative methods (Newton-Schulz, ICA) provide more stable latent
alignment than algebraic methods (SVD, PCA). The learned linear basis
\(\mathbf{V}\) identifies consistent feature subspaces regardless of the
consensus algorithm. This guarantees an invariant audit trail.

\subsection{Spectral Triage: Ablation Study of the Modality Alignment
Index
(MAI)}\label{spectral-triage-ablation-study-of-the-modality-alignment-index-mai}

A fundamental challenge in multi-modal integration is the presence of
high-variance noise sources lacking biological connection to the shared
consensus. Standard alignment methods yield spurious correlations when
operating on high-dimensional noise spaces (e.g., \(P > 500\)),
improperly inflating modality weights. We conduct a formal ablation
study to evaluate the objective function's alignment metric,
specifically the Modality Alignment Index (MAI), across different
mathematical formulations.

As Table~\ref{tbl-metric-tournament} shows, the proposed
\textbf{Procrustes \(R^2\) with Spectral Sharpness} provides a rigorous
mathematical bound. It evaluates the baseline metrics (Cosine MCI, RV
Coeff, Mean CCA) against the proposed Procrustes \(R^2\). The proposed
metric identifies the rogue modality M5 with an exact value of
\textbf{0.00}.

\begin{longtable}[]{@{}lllll@{}}
\caption{Ablation Study of Modality Alignment Metrics. Baseline metrics
(Cosine MCI, RV Coeff, Mean CCA) compared to the proposed method
(Procrustes \(R^2\) with Spectral Sharpness). The proposed spectral
sharpness metric provides a rigorous deterministic floor of 0.00,
correctly identifying Noisy and Rogue modalities and preventing
corruption of the shared
representation.}\label{tbl-metric-tournament}\tabularnewline
\toprule\noalign{}
Modality & Cosine MCI & RV Coeff & Procrustes \(R^2\) & Mean CCA \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Modality & Cosine MCI & RV Coeff & Procrustes \(R^2\) & Mean CCA \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
M1 (Gold) & 0.529 & 0.788 & 0.774 & 0.887 \\
M2 (Gold) & 0.239 & 0.793 & 0.780 & 0.890 \\
M3 (Partial) & -0.003 & 0.647 & 0.516 & 0.594 \\
M4 (Noisy) & -0.172 & 0.114 & 0.000 & 0.326 \\
M5 (Rogue) & 0.007 & 0.004 & 0.000 & 0.057 \\
\end{longtable}

We validate this mechanism through an ablation study on the BRCA
multi-omics dataset via step-wise modality inclusion. We simulate a
high-dimensional rogue sensor (500 features, 20x variance) appended to
biological views (RNA-Seq, CNV, Proteomics). As
Table~\ref{tbl-brca-stepwise} indicates, the model correctly ranks
biological views, achieving a peak predictive AUC of \textbf{0.939}
using only RNA-Seq, CNV, and Proteomics. Adding the Rogue modality
correctly triggers weight suppression via the automated gating logic,
preserving diagnostic representation integrity.

\begin{longtable}[]{@{}lll@{}}
\caption{Ablation Study of Step-wise Modality Inclusion (BRCA). Baseline
(All modalities including Rogue) versus Proposed (Automated MAI
Ranking). The model achieves peak performance (AUC 0.939) using only
validated biological views. The proposed gating logic self-corrects in
the presence of massive noise by suppressing the rogue
modality.}\label{tbl-brca-stepwise}\tabularnewline
\toprule\noalign{}
Modalities Included (by MCI Rank) & Combined Weight & Test AUC \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Modalities Included (by MCI Rank) & Combined Weight & Test AUC \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
RNA-Seq & 0.482 & 0.911 \\
RNA-Seq, CNV & 0.777 & 0.902 \\
\textbf{RNA-Seq, CNV, Proteomics} & \textbf{0.950} & \textbf{0.939} \\
RNA-Seq, CNV, Proteomics, Rogue & 1.000 & 0.938 \\
\end{longtable}

\subsection{The Interpretability-Performance
Frontier}\label{the-interpretability-performance-frontier}

\subsubsection{Assessing Representational Capacity vs.~Mechanistic
Transparency}\label{assessing-representational-capacity-vs.-mechanistic-transparency}

To evaluate deep architecture utility, we partition predictive capacity
into two paradigms:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Deep Consensus (\(\mathbf{Y}|\mathbf{U}\)):} Predictor trained
  on the final, deep non-linear shared latent space. This represents the
  upper bound of representational capacity (Hornik et al. 1989;
  Goodfellow et al. 2016).
\item
  \textbf{Strictly Linear (\(\mathbf{Y}|\mathbf{X}\mathbf{V}\)):}
  Predictor trained only on the concatenated linear projections of the
  first layer
  (\([\mathbf{X}_1 \mathbf{V}_1, \mathbf{X}_2 \mathbf{V}_2]\)). This
  isolates performance achieved through auditable pathways.
\end{enumerate}

\subsubsection{Linear-to-Deep Performance
Parity}\label{linear-to-deep-performance-parity}

Evaluation reveals that under optimized sparsity and orthogonality
constraints, the \textbf{Strictly Linear Accuracy
(\(\mathbf{X}\mathbf{V}\))} maintains high performance, approaching
parity with the deep consensus (\(\mathbf{U}\)).

This \textbf{Linear-to-Deep Performance Parity} delivers three major
practical and theoretical benefits: 1. \textbf{Elimination of the
``Transparency Penalty''}: Historically, practitioners have faced a hard
trade-off between the high performance of black-box deep models and the
interpretability of simple linear projections. Parity proves we can
achieve deep-level classification/regression performance while routing
predictions through a strictly linear, fully auditable first-layer
projection. 2. \textbf{Identifiability Verification}: It mathematically
validates that the Only Linear Encoder Entry-point (OLEE) successfully
concentrates the true generative signal into the linear bottleneck. The
downstream non-linear deep layers serve to denoise and reconstruct the
complex observational spaces, rather than encoding unidentifiable,
abstract representations. 3. \textbf{Actionable Patient-Level
Interventions}: Because the linear subspace captures the core predictive
signal, local patient audits and minimum-norm counterfactual
calculations (e.g., computing the exact physical biomarker adjustments
\(\delta \mathbf{x} = \Delta \mathbf{z} \mathbf{V}_m^\top\) to reduce
disease risk) can be executed in closed form with the confidence that
they represent high-fidelity, real-world pathways.

This architecture aligns with private-shared space paradigms for domain
separation (Bousmalis et al. 2016).

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig_v21_blessing_interpretability.png}

}

\caption{\label{fig-v21-blessing-interpretability}Linear-to-Deep
Performance Parity (Real-World). Evaluation of strictly linear
prediction (\(\mathbf{Y}|\mathbf{X}\mathbf{V}\), utilizing the
OLEE-constrained first layer) against deep consensus prediction
(\(\mathbf{Y}|\mathbf{U}\), utilizing the unconstrained shared latent
space). The dashed diagonal line represents perfect parity. Points
clustering tightly along this diagonal prove that enforcing the OLEE
bottleneck does not compromise representational accuracy, achieving
transparency and auditability without the typical ``performance
penalty'' associated with linear models.}

\end{figure}%

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1739}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1739}}@{}}
\caption{Analysis of Variance. Breakdown of performance variance by
model and regime. Data topology dictates difficulty, while the proposed
architectures significantly drive ground-truth
recovery.}\label{tbl-anova}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Effect Size (\(\eta^2_p\)) (Cohen 1973)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
p-value (Synthetic)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
p-value (Real)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Interpretation
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Factor
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Effect Size (\(\eta^2_p\)) (Cohen 1973)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
p-value (Synthetic)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
p-value (Real)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Interpretation
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Model} & 0.24 & \(< 10^{-8}\) & \(< 10^{-8}\) & Architecture
dominates ground-truth recovery. \\
\textbf{Regime/Dataset} & 0.92 & \(< 10^{-80}\) & \(< 10^{-30}\) & Data
topology is the primary variance driver. \\
\end{longtable}

\subsubsection{Rigorous Statistical Review: Deep-to-Linear
Benefit}\label{rigorous-statistical-review-deep-to-linear-benefit}

Comparing Deep models (LEND, NED, NEDPP) against the linear baseline
(SiMLR), we quantify the `Deep-to-Linear Benefit'. The proposed
architectures deliver statistically significant improvements in strictly
linear accuracy. In synthetic analyses
(Table~\ref{tbl-stat-sig-synthetic}), we observe large effect sizes
(Cohen's \(d > 0.8\)) and highly significant \(p\)-values (\(p < 0.05\))
in non-linear regimes. In clinical data, we observe significant
improvements for the \textbf{Heart dataset} (\(p = 8 \times 10^{-11}\))
and the \textbf{Diabetes dataset} (\(p = 3 \times 10^{-4}\)). These
results confirm that deep non-linear components discover more robust
linear bases than pure linear optimization. We actively center effect
sizes alongside \(p\)-values to verify the practical magnitude of this
benefit (Wasserstein and Lazar 2016; Cohen 1988).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1188}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1881}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2376}}
  >{\raggedright\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.2178}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1089}}
  >{\raggedleft\arraybackslash}p{(\linewidth - 10\tabcolsep) * \real{0.1287}}@{}}
\caption{Statistical Significance: Deep vs Linear (Strictly Linear
Accuracy, Synthetic). Baseline (Linear) versus Proposed (Deep).
Independent Welch's t-tests (Welch 1947) and Cohen's \(d\) (Cohen 1988).
Deep architectures yield statistically significant improvements and
large effect sizes in complex generative regimes, proving the
Deep-to-Linear benefit.}\label{tbl-stat-sig-synthetic}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Regime
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Consensus Group
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Linear Mean {[}95\% CI{]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Deep Mean {[}95\% CI{]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p-value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Cohen's d
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Regime
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Consensus Group
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Linear Mean {[}95\% CI{]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Deep Mean {[}95\% CI{]}
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
p-value
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedleft
Cohen's d
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Linear & Iterative & 0.788 {[}0.782, 0.794{]} & 0.793 {[}0.790, 0.797{]}
& 0.107 & 0.246 \\
Linear & Algebraic & 0.788 {[}0.782, 0.794{]} & 0.793 {[}0.789, 0.796{]}
& 0.167 & 0.21 \\
Polynomial & Iterative & 0.778 {[}0.774, 0.781{]} & 0.782 {[}0.779,
0.786{]} & 0.0529 & 0.278 \\
Polynomial & Algebraic & 0.780 {[}0.777, 0.784{]} & 0.784 {[}0.780,
0.787{]} & 0.194 & 0.181 \\
Sine & Iterative & 0.116 {[}0.105, 0.127{]} & 0.141 {[}0.134, 0.149{]} &
0.00031 & 0.553 \\
Sine & Algebraic & 0.119 {[}0.107, 0.131{]} & 0.149 {[}0.140, 0.157{]} &
0.000105 & 0.595 \\
Private & Iterative & 0.742 {[}0.722, 0.761{]} & 0.788 {[}0.784,
0.792{]} & 1.48e-05 & 0.793 \\
Private & Algebraic & 0.744 {[}0.725, 0.763{]} & 0.788 {[}0.784,
0.792{]} & 1.98e-05 & 0.779 \\
\end{longtable}

Synthetic results show that under complex generative regimes (e.g.,
Polynomial, Private Noise), Deep architectures provide a statistically
significant improvement in Strictly Linear Accuracy. We interpret
\(p\)-values alongside effect sizes (\(d\)) to assess practical
importance (Wasserstein and Lazar 2016).

\subsection{Real-World Predictive Performance
Matrix}\label{real-world-predictive-performance-matrix}

\subsubsection{Diabetes Progression: Strictly Linear
Accuracy}\label{diabetes-progression-strictly-linear-accuracy}

The Diabetes dataset benchmarks continuous regression in a clinical
context. We test the hypothesis that proposed deep-aligned linear bases
better predict disease progression than standard linear methods. We
analyze \(N=442\) samples with 10 baseline features. Predicting disease
progression one year after baseline is complicated by non-linear
metabolic interactions. As Table~\ref{tbl-diabetes-results} shows, the
proposed NED architecture provides a statistically significant
improvement over the SiMLR baseline (\(p = 3 \times 10^{-4}\)). NED
leverages the deep decoder to back-propagate alignment signals,
discovering a linear basis that captures complex variance overlooked by
purely linear methods. This weights primary physiological drivers, such
as BMI and serum triglycerides (S5), accurately, providing a robust
clinical risk score.

\begin{longtable}[]{@{}llr@{}}
\caption{Diabetes Progression. Baseline (SiMLR) vs.~Proposed
Architectures. Mean ± SD and Peak Strictly Linear Accuracy
(\(R^2_{\mathbf{X}\mathbf{V}}\)). Proposed deep architectures
significantly outperform the linear baseline, capturing complex
metabolic interactions within the auditable linear
basis.}\label{tbl-diabetes-results}\tabularnewline
\toprule\noalign{}
Model & Mean XV R2 ± SD & Peak XV R2 \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Model & Mean XV R2 ± SD & Peak XV R2 \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Flow-SiMLR-V & 0.467 ± 0.023 & 0.483 \\
LEND & 0.466 ± 0.012 & 0.483 \\
NED & 0.464 ± 0.035 & 0.486 \\
NEDPP & 0.450 ± 0.048 & 0.485 \\
SiMLR & 0.400 ± 0.008 & 0.414 \\
Flow-SiMLR & 0.337 ± 0.072 & 0.413 \\
\end{longtable}

\subsubsection{Heart Disease: Strictly Linear
Accuracy}\label{heart-disease-strictly-linear-accuracy}

For the Heart Disease dataset, we evaluate binary classification on
categorical clinical outcomes. This dataset includes 13 clinical
features to predict cardiovascular disease. We utilize Strictly Linear
Accuracy (\(Acc_{\mathbf{X}\mathbf{V}}\)) to ensure diagnostic decisions
trace to individual physiological indicators. Results in
Table~\ref{tbl-heart-results} demonstrate that the proposed LEND
architecture outperforms the purely linear SiMLR baseline
(\(p = 8 \times 10^{-11}\), Welch's t-test). The deep consensus layer
identifies complex patterns of cardiovascular stress---such as age and
tachycardia interactions---distilling them into the auditable linear
basis. The stability across runs confirms the model's reliability as a
decision-support tool.

\begin{longtable}[]{@{}llr@{}}
\caption{Heart Disease Classification. Baseline (SiMLR) vs.~Proposed
Architectures. Mean ± SD and Peak Strictly Linear Accuracy
(\(Acc_{\mathbf{X}\mathbf{V}}\)). LEND architecture significantly
outperforms the baseline, proving the deep decoder facilitates superior
diagnostic basis discovery.}\label{tbl-heart-results}\tabularnewline
\toprule\noalign{}
Model & Mean XV Acc ± SD & Peak XV Acc \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
Model & Mean XV Acc ± SD & Peak XV Acc \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Flow-SiMLR-V & 0.580 ± 0.004 & 0.589 \\
LEND & 0.581 ± 0.005 & 0.589 \\
NED & 0.587 ± 0.012 & 0.622 \\
NEDPP & 0.588 ± 0.013 & 0.622 \\
SiMLR & 0.554 ± 0.007 & 0.567 \\
Flow-SiMLR & 0.551 ± 0.019 & 0.578 \\
\end{longtable}

The evaluation confirms the utility of the OLEE. For \textbf{Heart
Disease classification}, the \textbf{LEND} architecture achieved leading
performance with statistical significance over the linear baseline
(\(p = 8 \times 10^{-11}\)). For \textbf{Diabetes progression}, the deep
architectures provide a statistically significant benefit
(\(p = 3 \times 10^{-4}\)).

\subsection{\texorpdfstring{Interpretability of the NSA Layer (Learned
\(\mathbf{V}\)
Matrices)}{Interpretability of the NSA Layer (Learned \textbackslash mathbf\{V\} Matrices)}}\label{interpretability-of-the-nsa-layer-learned-mathbfv-matrices}

The learned \(\mathbf{V}\) matrices represent the core of the OLEE,
mapping feature contributions to the latent consensus space. We
visualize these weights using importance heatmaps in
Figure~\ref{fig-nsa-v-interpretability}, where rows correspond to
features and columns to latent dimensions (\(K\)). In the Heart Disease
dataset, the model weights demographics and exercise metrics to form
distinct latent risk profiles. For Diabetes, the model delineates vitals
against blood serums. The Newton-Schulz Alignment (NSA) ensures latent
dimensions remain orthogonal and non-redundant. By enforcing this linear
bottleneck, the final prediction decomposes into a weighted sum of
observable features, fulfilling global interpretability requirements.

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/nsa_v_interpretability.png}

}

\caption{\label{fig-nsa-v-interpretability}Interpretability of Learned
NSA Layer Weights. Baseline (Black Box Importance) vs.~Proposed (Exact
\(\mathbf{V}\) Matrix Weights). Heatmaps of learned \(\mathbf{V}\)
matrices for Heart Disease and Diabetes datasets. The visualization
provides exact magnitude and direction of feature contributions,
demonstrating strict global interpretability.}

\end{figure}%

The \(\mathbf{V}\) matrices provide an explicit mapping via importance
heatmaps (Holmberg et al. 2022; Han et al. 2020).

\textbf{Global Feature Importance and Sparsity:} The NSA layer acts as a
`hard' feature selector. As quantified by the Gini coefficients in
Figure~\ref{fig-nsa-v-interpretability}, the discovered basis vectors
exhibit high sparsity. Each latent dimension is dominated by a clear
biological module. By constraining the first layer to be linear and
enforcing NSA orthogonality, we ensure deep consensus mechanisms
(\(\mathbf{U}\)) do not obscure foundational clinical drivers.

\section{Systematic Evaluation
Matrix}\label{systematic-evaluation-matrix}

We sweep the architectural space, testing Loss Functions and Consensus
Methods.

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig_v21_interaction_heatmap.png}

}

\caption{\label{fig-v21-interaction-heatmap}Architectural Sensitivity:
Loss x Consensus Interaction. Baseline vs.~Proposed parameter grid.
Heatmap of mean predictive performance (\(R^2_{\mathbf{X}\mathbf{V}}\))
for LEND. Newton consensus paired with ACC or Log-Cosh loss provides the
optimal balance between representational capacity and latent stability.}

\end{figure}%

\section{Complexity and Scaling
Benchmarks}\label{complexity-and-scaling-benchmarks}

We analyze wall-time complexity as a function of sample size \(N\) and
latent dimension \(K\). Scalability is a prerequisite for
high-throughput multi-omics analysis. Figure~\ref{fig-scaling} (Left)
shows execution time scales linearly with \(N\) (\(\mathcal{O}(N)\)),
confirming optimized deep forward and backward passes.
Figure~\ref{fig-scaling} (Right) details non-linear growth concerning
\(K\), specifically \(\mathcal{O}(K^3)\) for the Newton-Schulz consensus
due to matrix inversions. For typical biomedical ranks (\(K < 100\)),
the overhead remains negligible.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03_experiments_files/figure-pdf/fig-scaling-output-1.pdf}}

}

\caption{\label{fig-scaling}Algorithmic Efficiency. Baseline (Linear
Scaling) vs.~Proposed (NSA Overhead). Execution Wall-time Scaling.
(Left) Sample size \(N\) scaling is linear. (Right) Latent dimension
\(K\) scaling reflects Newton-Schulz and covariance overhead
(\(\mathcal{O}(K^3)\)). The proposed architectures maintain scalable
execution times for typical biomedical dataset dimensions.}

\end{figure}%

\section{Normalizing Flow SiMLR (Flow-SiMLR) Scientific
Evaluation}\label{normalizing-flow-simlr-flow-simlr-scientific-evaluation}

To evaluate the mathematical and empirical benefits of Normalizing Flows
within the SiMLR framework, we execute three distinct benchmarking
experiments. These evaluate strongly non-linear sinusoidal manifolds,
structured modality-specific private noise, and clinical regression on
the Diabetes dataset with cross-view imputation. We report latent
outcomes, reconstruction errors, cross-view imputation, and fit times
across three random seeds.

\subsection{Experiment 1: Strongly Non-linear Transformations
(Sinusoidal)}\label{experiment-1-strongly-non-linear-transformations-sinusoidal}

In high-entropy non-linear systems, purely linear projections drop
significant shared signal. We generate \(N=800\) samples from two views
(\(D_1=30, D_2=20\), shared latent dimension \(k=3\)), where the latent
consensus \(U \sim \mathcal{N}(0, I)\) is mapped using strongly
non-linear sine functions: \[X_m = \sin(2.0 \cdot U W_m) + \eta_m\] As
shown in Table~\ref{tbl-exp1-results}, purely linear SiMLR fails to
resolve the periodic structure, yielding a negative held-out target
\(R^2\) (\(-0.408 \pm 0.787\)). Deep NED captures the non-linear
manifold (\(R^2 = 0.254 \pm 0.251\)). However, the proposed Flow-SiMLR
architecture, by deploying bijective affine coupling layers, achieves
high held-out predictive accuracy (\(R^2 = 0.295 \pm 0.298\)).
Crucially, the proposed \textbf{Flow-SiMLR-V} architecture, by
pre-pending the Stiefel-constrained linear encoder matrix
\(\mathbf{V}\), achieves even higher predictive accuracy on its linear
projection (\(R^2 = 0.488 \pm 0.287\)) while maintaining low
reconstruction error (\(0.893 \pm 0.020\)). This validates that the
change-of-variables density estimation regularizes the latent space,
preventing the overfitting typical of unconstrained deep MLPs.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2105}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}@{}}
\caption{Experiment 1 (Sinusoidal Manifold) Results. Flow-SiMLR and
Flow-SiMLR-V outperform both purely linear projections and MLP-based
deep models, capturing periodic manifold structures and minimizing
reconstruction error.}\label{tbl-exp1-results}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Held-out Target \(R^2\) (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Relative Reconstruction (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Fit Time (sec) (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Held-out Target \(R^2\) (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Relative Reconstruction (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Fit Time (sec) (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Linear SIMLR} & \(-0.408 \pm 0.787\) & \(1.000 \pm 0.000\) &
\(0.062 \pm 0.001\) \\
\textbf{Deep NED (MLP)} & \(0.254 \pm 0.251\) & \(0.918 \pm 0.045\) &
\(1.235 \pm 0.321\) \\
\textbf{Flow-SiMLR (Ours)} & \(0.295 \pm 0.298\) &
\(\mathbf{0.881 \pm 0.023}\) & \(4.235 \pm 0.092\) \\
\textbf{Flow-SiMLR-V (Ours)} & \(\mathbf{0.488 \pm 0.287}\) &
\(0.893 \pm 0.020\) & \(6.902 \pm 0.153\) \\
\end{longtable}

\subsection{Experiment 2: Structured Private Noise (Shared/Private
Disentanglement)}\label{experiment-2-structured-private-noise-sharedprivate-disentanglement}

In multi-view settings, modality-specific ``private'' noise (e.g., batch
effects or view-specific clinical covariates) can contaminate the
consensus. We simulate \(N=800\) samples with shared components
(\(k_s=3\)) and modality-specific private components (\(k_p=3\)) mapped
through non-linear coordinates:
\[X_m = f_m([U_s \parallel U_{p,m}]) + \eta_m\] As shown in
Table~\ref{tbl-exp2-results}, standard deep MLP models achieve
\(R^2 = 0.742 \pm 0.082\). Enforcing explicit orthogonal private
subspaces via covariance projection constraints (NEDPP) degrades
alignment performance (\(R^2 = 0.610 \pm 0.201\)), although it improves
private reconstruction. Flow-SiMLR solves this naturally: because
normalizing flows are strictly bijective, the private dimensions are
implicitly isolated in the remaining coordinate space (\(z_{k+1:D}\))
without requiring explicit cross-covariance optimization. Flow-SiMLR
achieves high predictive accuracy (\(R^2 = 0.759 \pm 0.061\)). The
\textbf{Flow-SiMLR-V} model improves on this further, achieving the
highest overall target alignment (\(R^2 = 0.912 \pm 0.042\)) and further
reducing reconstruction error to \(0.792 \pm 0.032\), demonstrating that
pre-pending a linear encoder matrix \(\mathbf{V}\) filters out
modality-specific batch effects and private noise prior to flow mapping.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2105}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}
  >{\centering\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2632}}@{}}
\caption{Experiment 2 (Structured Private Noise) Results. Flow-SiMLR and
Flow-SiMLR-V match or exceed unconstrained deep models in consensus
discovery without the negative optimization impacts associated with
explicit private subspace covariance constraints
(NEDPP).}\label{tbl-exp2-results}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Held-out Target \(R^2\) (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Relative Reconstruction (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Fit Time (sec) (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Held-out Target \(R^2\) (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Relative Reconstruction (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Fit Time (sec) (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Standard NED} & \(0.742 \pm 0.082\) & \(0.815 \pm 0.017\) &
\(1.074 \pm 0.088\) \\
\textbf{NEDPP (Shared/Private)} & \(0.610 \pm 0.201\) &
\(\mathbf{0.641 \pm 0.038}\) & \(1.250 \pm 0.057\) \\
\textbf{Flow-SiMLR (Ours)} & \(0.759 \pm 0.061\) & \(0.847 \pm 0.036\) &
\(4.514 \pm 0.055\) \\
\textbf{Flow-SiMLR-V (Ours)} & \(\mathbf{0.912 \pm 0.042}\) &
\(0.792 \pm 0.032\) & \(6.366 \pm 0.025\) \\
\end{longtable}

\subsection{Experiment 3: Clinical Imputation \& Imbalanced
Modalities}\label{experiment-3-clinical-imputation-imbalanced-modalities}

A core advantage of bijective Normalizing Flows is the capacity for
exact conditional inference. We evaluate this on the Diabetes clinical
dataset (\(N=442\)), split into a vitals view (\(D_1=5\)) and blood
serums view (\(D_2=5\)). We fit a joint Gaussian distribution over the
concatenated shared latent space
(\(\mathbf{Z}_{\text{joint}} \sim \mathcal{N}(\mu, \Sigma)\)) during
training. On the test set, we simulate a clinical scenario where blood
serums are completely missing, predicting the serums (view 2) from
vitals (view 1) using the Schur complement solver.

As detailed in Table~\ref{tbl-exp3-results}, Flow-SiMLR achieves
outstanding predictive performance on disease progression
(\(R^2 = 0.304 \pm 0.060\)), more than doubling the accuracy of standard
Deep NED (\(R^2 = 0.127 \pm 0.041\)) and outperforming linear
projections. Crucially, \textbf{Flow-SiMLR-V} further improves
predictive accuracy (\(R^2 = 0.381 \pm 0.058\)) with a relative
reconstruction error of \(0.790 \pm 0.016\), proving that prepending a
Stiefel-constrained linear encoder matrix \(\mathbf{V}_m\) enforces
strict global interpretability while delivering leading predictive
representation density. Traditional deep models (NED, NEDPP) are unable
to perform this conditional inference mathematically due to their
non-invertible projection architectures.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}@{}}
\caption{Experiment 3 (Diabetes Progression \& Imputation) Results.
Flow-SiMLR and Flow-SiMLR-V demonstrate superior predictive accuracy,
lower reconstruction error, and enable mathematically valid conditional
cross-view imputation.}\label{tbl-exp3-results}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Held-out Target \(R^2\) (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Relative Reconstruction (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Imputation Error (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Fit Time (sec) (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Held-out Target \(R^2\) (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Relative Reconstruction (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Imputation Error (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Fit Time (sec) (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Linear SIMLR} & \(-0.085 \pm 0.500\) & \(1.000 \pm 0.000\) & N/A
& \(0.036 \pm 0.001\) \\
\textbf{Deep NED (MLP)} & \(0.127 \pm 0.041\) & \(1.056 \pm 0.054\) &
N/A & \(0.608 \pm 0.090\) \\
\textbf{Flow-SiMLR (Ours)} & \(0.304 \pm 0.060\) &
\(\mathbf{0.720 \pm 0.038}\) & \(\mathbf{0.885 \pm 0.054}\) &
\(\mathbf{2.759 \pm 0.047}\) \\
\textbf{Flow-SiMLR-V (Ours)} & \(\mathbf{0.381 \pm 0.058}\) &
\(0.790 \pm 0.016\) & \(1.008 \pm 0.059\) & \(3.843 \pm 0.027\) \\
\end{longtable}

\subsection{Experiment 4: Clinical Classification and
Parity}\label{experiment-4-clinical-classification-and-parity}

To establish complete parity of exploration with the baseline and deep
models, we evaluate Flow-SiMLR and Flow-SiMLR-V alongside SiMLR, LEND,
NED, and NEDPP on the Heart Disease and TCGA-BRCA multi-omics datasets
via 5-fold cross-validation. For Heart Disease, the model binarizes
targets to predict the presence of cardiovascular disease. For BRCA, we
integrate three high-dimensional modalities (RNA-Seq, CNV, Proteomics)
to classify binary Estrogen Receptor (ER) status.

As shown in Table~\ref{tbl-exp4-results}, the Normalizing Flow
architectures achieve leading or highly competitive performance across
both clinical datasets. While standard Flow-SiMLR performs
classification on its bijective, unconstrained latents \(\mathbf{U}\)
(yielding Heart AUC of \(0.867 \pm 0.038\) and BRCA AUC of
\(0.882 \pm 0.029\)), the proposed \textbf{Flow-SiMLR-V} architecture
pre-pends a Stiefel-constrained linear encoder matrix \(\mathbf{V}_m\).
Flow-SiMLR-V evaluates classification on strictly linear projections
\(\mathbf{X}_m\mathbf{V}_m\), achieving on-par performance with the deep
MLP-based LEND and NED models (Heart Accuracy: \(0.828 \pm 0.050\), AUC:
\(0.896 \pm 0.041\); BRCA Accuracy: \(0.913 \pm 0.012\), AUC:
\(0.944 \pm 0.016\)). This confirms that pre-pending a linear encoder
bottleneck enforces strict global interpretability and structural
auditability without compromising representation density or conditional
cross-view inference.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1667}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2083}}@{}}
\caption{Experiment 4 (Clinical Classification \& Parity) Results.
Flow-SiMLR and Flow-SiMLR-V exhibit leading or highly competitive
performance under 5-fold cross-validation on clinical Heart and
high-dimensional BRCA multi-omics datasets, achieving parity of
exploration with deep MLP-based
models.}\label{tbl-exp4-results}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Heart Accuracy (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Heart AUC (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
BRCA Accuracy (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
BRCA AUC (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Heart Accuracy (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Heart AUC (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
BRCA Accuracy (Mean \(\pm\) SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
BRCA AUC (Mean \(\pm\) SD)
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{SiMLR} & \(0.694 \pm 0.052\) & \(0.728 \pm 0.067\) &
\(0.838 \pm 0.031\) & \(0.862 \pm 0.074\) \\
\textbf{LEND} & \(0.831 \pm 0.044\) & \(0.896 \pm 0.048\) &
\(0.914 \pm 0.007\) & \(0.943 \pm 0.014\) \\
\textbf{NED} & \(0.828 \pm 0.048\) & \(0.897 \pm 0.042\) &
\(\mathbf{0.920 \pm 0.014}\) & \(0.945 \pm 0.010\) \\
\textbf{NEDPP} & \(\mathbf{0.831 \pm 0.057}\) &
\(\mathbf{0.898 \pm 0.042}\) & \(0.918 \pm 0.010\) &
\(\mathbf{0.947 \pm 0.010}\) \\
\textbf{Flow-SiMLR} & \(0.781 \pm 0.054\) & \(0.867 \pm 0.038\) &
\(0.871 \pm 0.011\) & \(0.882 \pm 0.029\) \\
\textbf{Flow-SiMLR-V (Ours)} & \(0.828 \pm 0.050\) & \(0.896 \pm 0.041\)
& \(0.913 \pm 0.012\) & \(0.944 \pm 0.016\) \\
\end{longtable}

\section{Precision Clinical Audit Trails: Structural XAI vs.~Post-Hoc
Methods}\label{precision-clinical-audit-trails-structural-xai-vs.-post-hoc-methods}

The \textbf{NED} architecture provides a specialized pathway for
structural explainability. Post-hoc explainable AI (XAI) baselines, such
as SHAP or LIME (Lundberg and Lee 2017; Ribeiro et al. 2016), suffer
from instability on entangled manifolds because they approximate feature
importance after non-linear mixing. The proposed Orthogonal Linear
Encoder Entry-point (OLEE) enforces Structural XAI. By restricting the
initial mapping to an orthogonal linear projection, the architecture
guarantees zero approximation error when mapping latent consensus
coordinates back to input features.

We evaluate the hypothesis that structural local feature attributions
provide consistent and clinically valid representations. The
architecture permits exact counterfactual analysis; the required
perturbation in the input space \(\delta \mathbf{x}\) to achieve a
targeted shift in the latent diagnostic coordinate \(\Delta \mathbf{z}\)
is formally defined as
\(\delta \mathbf{x} = \Delta \mathbf{z} \mathbf{V}_m^\top\). As
Figure~\ref{fig-diabetes-audit} demonstrates, local feature attribution
identifies BMI and S5 as primary drivers of diabetic progression for
Patient \#1. This mathematical exactness satisfies the requirement for
mechanistic transparency (Rudin 2019; Biswas 2025).

\subsection{Diabetes Progression
Audit}\label{diabetes-progression-audit}

To bridge the gap between global importance and individual patient care,
we utilize the NED architecture's linear basis to generate local audit
trails. Figure~\ref{fig-diabetes-audit} decomposes the latent signal for
Patient \#1 into constituent feature impacts. The model identifies BMI
and serum triglycerides (S5) as the primary positive drivers. This local
attribution proves the high risk score is driven by metabolic factors.
Mechanistic transparency facilitates exact counterfactual reasoning.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03_experiments_files/figure-pdf/fig-diabetes-audit-output-1.pdf}}

}

\caption{\label{fig-diabetes-audit}Localized Feature Impact Analysis
(Diabetes). Baseline (Post-hoc SHAP) vs.~Proposed (Exact Structural
XAI). Local feature attribution derived directly from the NED
first-layer basis. The proposed architecture conceptually mirrors SHAP
but operates with zero approximation error, proving exact
interpretability at the patient level (Lundberg and Lee 2017; Radulovic
2023).}

\end{figure}%

\subsection{Heart Disease Audit}\label{heart-disease-audit}

We apply the local audit protocol to the Heart Disease dataset. The
objective is to identify physiological markers contributing to a
specific patient's risk. Figure~\ref{fig-heart-audit} highlights
`thalach' (maximum heart rate) and `cp' (chest pain type) as dominant
factors for a high-risk individual. Visualizing these contributions
provides an auditable path from clinical data to diagnostic
classification. This eliminates the `black box' problem.

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/heart_waterfall.png}

}

\caption{\label{fig-heart-audit}Individualized Cardiovascular Audit.
Baseline (Black box classification) vs.~Proposed (Auditable Linear
Attribution). Local feature attribution for a high-risk patient. The
audit reveals the exact additive contribution of clinical features
(thalach, cp) to the latent risk factor, establishing clinical trust.}

\end{figure}%

\subsection{Latent Trajectory and Counterfactual
Discovery}\label{latent-trajectory-and-counterfactual-discovery}

The auditable linear basis enables \textbf{Latent Trajectory Analysis}.
By analyzing shifts along a specific SiMLR component, we observe how a
patient's risk profile responds to feature perturbations. This provides
a formal mechanism for discovering exact counterfactuals: calculating
the minimal required shift in clinical vitals
(\(\delta \mathbf{x} = \Delta \mathbf{z} \mathbf{V}_m^\top\)) to
transition a patient from a high-risk latent cluster to a stable
projection.

\subsection{Topological Regularization: LOO vs.~STAR Consensus
Pathways}\label{topological-regularization-loo-vs.-star-consensus-pathways}

To evaluate architectural constraints, we compare the baseline
\textbf{Star topology} with the proposed strict \textbf{Leave-One-Out
(LOO) topology}. In Star topology, modality \(m\) aligns to a consensus
\(\mathbf{U}\) that includes its own information. In LOO topology,
modality \(m\) aligns against a consensus \(\mathbf{U}_{\neq m}\) built
exclusively from \emph{other} modalities.

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig_v21_loo_vs_star.png}

}

\caption{\label{fig-v21-loo-vs-star}Topological Regularization Benefit.
Baseline (Star Topology) vs.~Proposed (LOO Topology). Strictly Linear
Accuracy on the Diabetes dataset. The LOO topology acts as a powerful
regularizer for high-capacity models, forcing the discovery of robust
shared features rather than memorizing modality-specific noise.}

\end{figure}%

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig_v21_loo_vs_star_gap.png}

}

\caption{\label{fig-v21-loo-vs-star-gap}Generalization Gap by Topology.
Baseline (Star Topology) vs.~Proposed (LOO Topology). Train-test
accuracy gap. The LOO consensus pathway effectively narrows the
generalization gap for deep architectures, proving that strict
cross-modal prediction prevents self-prediction leaks.}

\end{figure}%

\section{Structural Generalization: Basis vs.~Feature
Orthogonality}\label{structural-generalization-basis-vs.-feature-orthogonality}

A key concern is whether enforced constraints (e.g., orthogonality)
generalize to unseen data. We quantify this using the Invariant
Orthogonality Defect, defined as
\(\mathcal{D}_I(\mathbf{V}) = \| \mathbf{V}^\top \mathbf{V} - \mathbf{I} \|_F\).
Figure~\ref{fig-ortho-gen} demonstrates the NSA-Flow mechanism maintains
a low defect across training and test sets. The stability of the feature
defect on the test set (Figure~\ref{fig-ortho-gen}, Right) provides
strong evidence that the OLEE identifies a robust, generalizing
subspace.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{03_experiments_files/figure-pdf/fig-ortho-gen-output-1.pdf}}

}

\caption{\label{fig-ortho-gen}Manifold Integrity Generalization.
Baseline (Unconstrained) vs.~Proposed (NSA-Flow). Invariant
Orthogonality Defect. (Left) Scale-invariant defect of weights
\(\mathbf{V}\). (Right) Feature defect generalization across train
(solid) and test (dashed) sets. Stability across train and test sets
confirms the OLEE identifies a robust, generalizing subspace resistant
to overfitting.}

\end{figure}%

\subsection{Optimization Dynamics and Convergence
Guarantees}\label{optimization-dynamics-and-convergence-guarantees}

To verify that the joint-variational objective optimizes smoothly
without triggering mode collapse, we trace the global loss and
cross-modal alignment energy across epochs. Standard exact SVD
projection introduces non-differentiable bottlenecks that shatter
gradients. By replacing this with NSA-Flow and Newton-Schulz iterations
on the Stiefel manifold, the architecture guarantees mathematically
smooth, monotonic convergence.

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig-convergence-traces.png}

}

\caption{\label{fig-convergence-traces}Global Objective Convergence and
Alignment Stability. Baseline (SGD Instability) vs.~Proposed
(Newton-Schulz + NSA-Flow). (Left) Total loss and reconstruction penalty
decrease smoothly without sudden gradient shocks. (Right) The
cross-modal consensus energy minimizes stably, proving that the
Block-Coordinate Descent (BCD) procedure achieves an optimal equilibrium
without representation collapse.}

\end{figure}%

\section{Flow-SiMLR-V Gating Stability and
Robustness}\label{flow-simlr-v-gating-stability-and-robustness}

We evaluate the Modality Alignment Index (MAI) dynamic weight gating on
normalizing flow architectures under two challenging scenarios: a mixed
non-linear synthetic benchmark containing a structured periodic signal
and a completely random rogue noise view, and a real-world breast cancer
(BRCA) multi-omics classification task.

\subsection{Mixed Non-linear Sinusoidal
Benchmark}\label{mixed-non-linear-sinusoidal-benchmark}

The mixed synthetic regime evaluates whether the normalizing flow
consensus can isolate a highly non-linear periodic wave. We simulate
\(N=300\) samples across 4 views, where View 1 is linear, View 2 is
quadratic, View 3 is sinusoidal
(\(X_3 = \sin(2.0 \cdot U W_3) + \eta\)), and View 4 is completely
random Gaussian noise. Because the periodic wave is non-injective
(many-to-one), the linear View 1 acts as a coordinate anchor that
prevents phase ambiguities.

As shown in Table~\ref{tbl-mixed-synthetic-results}, purely static
weights fail to suppress the rogue noise view, yielding a lower latent
recovery (\(R^2 = 0.1288\)). Activating MAI gating immediately (epoch 0)
on Flow-SiMLR-V causes weight collapse on the low-dimensional space,
suppressing View 2 prematurely. Implementing the \textbf{Delayed Gating
Warmup} (uniform weights for the first 60 epochs) allows the projection
layers to stabilize. When gating is activated at epoch 60, the model
successfully quarantines the rogue view (noise weight driven to absolute
zero) and achieves stable consensus alignment (\(R^2 = 0.3073\)), while
the fully unconstrained Flow-SiMLR model achieves \(R^2 = 0.8193\).

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1739}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1739}}@{}}
\caption{Mixed Non-linear Synthetic Benchmark Results. Flow-SiMLR-V with
Delayed Gating achieves stable consensus recovery and successfully
quarantines rogue noise views without suffering weight
collapse.}\label{tbl-mixed-synthetic-results}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model Configuration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Dynamic (MAI)?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Delayed Start?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Latent Recovery \(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Modality Weights (\(V_1, V_2, V_3, \text{Rogue}\))
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model Configuration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Dynamic (MAI)?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Delayed Start?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Latent Recovery \(R^2\)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Modality Weights (\(V_1, V_2, V_3, \text{Rogue}\))
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Flow-SiMLR-V (Static)} & No & N/A & \(0.1288\) &
\([0.250, 0.250, 0.250, 0.250]\) \\
\textbf{Flow-SiMLR-V (Immediate)} & Yes & Epoch 0 & \(0.7236\) &
\([0.526, 0.001, 0.473, 0.000]\) (Collapsed \(V_2\)) \\
\textbf{Flow-SiMLR-V (Delayed)} & Yes & Epoch 60 & \textbf{\(0.3073\)} &
\([0.445, 0.149, 0.406, 0.000]\) (Stable Gating) \\
\textbf{Flow-SiMLR (Static)} & No & N/A & \(0.8257\) &
\([0.250, 0.250, 0.250, 0.250]\) \\
\textbf{Flow-SiMLR (Dynamic)} & Yes & Epoch 0 & \textbf{\(0.8193\)} &
\([0.341, 0.306, 0.332, 0.021]\) (Stable Gating) \\
\end{longtable}

\subsection{BRCA Clinical Multi-omics
Evaluation}\label{brca-clinical-multi-omics-evaluation}

We validate the stability of Flow-SiMLR-V gating on the high-dimensional
TCGA-BRCA multi-omics clinical dataset (\(N = 1010\) samples). The views
consist of RNA expression, copy number variations, protein expression,
and an injected Gaussian noise view. We train the models to learn a
joint consensus representation, and predict patient Estrogen Receptor
(ER) binary status using a downstream logistic regression model.

As shown in Table~\ref{tbl-brca-gating-results}, prepending the
Stiefel-constrained linear encoder matrix with unconstrained positive
and negative attributions
(\texttt{positivity=\textquotesingle{}either\textquotesingle{}})
prevents feature clamping and enables leading classification accuracies.
Under \textbf{Delayed Gating (warmup = 75 epochs)}, Flow-SiMLR-V
achieves the highest downstream ER status prediction accuracy of
\textbf{87.27\%}, outperforming both the static baseline (79.09\%) and
unconstrained Flow-SiMLR (74.55\%) by successfully quarantining the
noise modality (weight reduced to \(0.0593\)) while maintaining
representation capacity across all biological views.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1739}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\centering\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.2174}}
  >{\raggedright\arraybackslash}p{(\linewidth - 8\tabcolsep) * \real{0.1739}}@{}}
\caption{BRCA Clinical Multi-omics Gating Results. Flow-SiMLR-V with
Delayed Gating achieves the highest classification accuracy by isolating
genomic noise and balancing biological
views.}\label{tbl-brca-gating-results}\tabularnewline
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model Configuration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Dynamic (MAI)?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Delayed Start?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ER Status Accuracy
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Modality Weights
(\(\text{RNA}, \text{DNA}_{\text{CN}}, \text{Protein}, \text{Noise}\))
\end{minipage} \\
\midrule\noalign{}
\endfirsthead
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Model Configuration
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Dynamic (MAI)?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
Delayed Start?
\end{minipage} & \begin{minipage}[b]{\linewidth}\centering
ER Status Accuracy
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Modality Weights
(\(\text{RNA}, \text{DNA}_{\text{CN}}, \text{Protein}, \text{Noise}\))
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Flow-SiMLR-V (Static)} & No & N/A & \(79.09\%\) &
\([0.2500, 0.2500, 0.2500, 0.2500]\) \\
\textbf{Flow-SiMLR-V (Immediate)} & Yes & Epoch 0 & \(82.73\%\) &
\([0.3640, 0.3288, 0.3042, 0.0029]\) \\
\textbf{Flow-SiMLR-V (Delayed)} & Yes & Epoch 75 & \textbf{\(87.27\%\)}
& \([0.3353, 0.3364, 0.2690, 0.0593]\) (Optimal Gating) \\
\textbf{Flow-SiMLR (Static)} & No & N/A & \(70.00\%\) &
\([0.2500, 0.2500, 0.2500, 0.2500]\) \\
\textbf{Flow-SiMLR (Dynamic)} & Yes & Epoch 0 & \(74.55\%\) &
\([0.3102, 0.2502, 0.3167, 0.1229]\) \\
\end{longtable}

\section{Visualization Color Mapping}\label{visualization-color-mapping}

The results are presented using the following color mapping:
{\textbf{Blue for SiMLR}}, {\textbf{Green for LEND}}, {\textbf{Orange
for NED}}, and {\textbf{Purple for NEDPP}}.

\bookmarksetup{startatroot}

\chapter{Discussion}\label{discussion}

Integrating disparate, high-dimensional datasets remains a primary
challenge in computational science. As modalities grow more
heterogeneous---from genomic sequencing to complex longitudinal
neuroimaging ({Stone et al.} 2020)---analytical tools must balance
representational capacity with guaranteed interpretability. In this
work, we present the deep learning expansion of the \textbf{SiMLR}
framework into a rigorously disciplined family of architectures (LEND,
NED, NEDPP) that transforms deep multi-modal integration into an
auditable scientific instrument, stabilized via \textbf{Non-negative
Stiefel approximating flow} (NSA-Flow).

Through systematic benchmarking and clinical application, we quantify
the operational parameters of deep multi-view alignment and identify
robust configurations for mechanistic discovery.

\section{The Optimal Configuration for Scientific
Discovery}\label{the-optimal-configuration-for-scientific-discovery}

Our systematic evaluation identifies the \textbf{LEND-ICA-LogCosh}
combination as an optimal configuration for scientific multi-modal
integration. This configuration achieves Pareto optimality by balancing
representational capacity with structural parsimony:

\begin{itemize}
\tightlist
\item
  \textbf{Spectral Integrity (Encoder):} By preserving a strictly linear
  encoder, we maintain the exact feature-to-latent audit trail required
  for biological discovery.
\item
  \textbf{The Linear-to-Deep Performance Parity:} A critical observation
  is the high degree of parity between the \textbf{Strictly Linear
  Accuracy (\(\mathbf{X}\mathbf{V}\))} and the model's own deep
  non-linear consensus (\(\mathbf{U}\)). This demonstrates that the
  Orthogonal Linear Embedding Encoder (OLEE) acts as a rigorous
  regularizer, distilling a linear signal that is more generalizable
  than the non-linear transformations of the deeper network.
\item
  \textbf{Non-linear Dominance in Structural Recovery:} In complex
  periodic manifolds (Sine regime), the deep architectures (NED, NEDPP)
  exhibit a 4-fold improvement in \textbf{Feature Recovery
  (\(\mathbf{V}\))} compared to linear SiMLR (\(p < 10^{-9}\)), while
  maintaining nearly 3x better predictive accuracy (\(p < 0.02\)). This
  shows that for high-entropy non-linear systems, deep decoding is a
  statistical necessity for ground-truth discovery.
\item
  \textbf{Gains in Mixing:} The introduction of \textbf{ICA Consensus}
  provides statistically significant gains in recovery fidelity,
  particularly in non-monotonic manifolds. This indicates that treating
  modality synthesis as a source separation problem better captures the
  independence of disparate diagnostic channels.
\end{itemize}

\section{Positioning within the
Literature}\label{positioning-within-the-literature}

When situated within the broader landscape of machine learning and
domain science, the value of the Deep SiMLR framework becomes evident
not merely as an algorithmic novelty, but as a necessary methodological
corrective. The deep learning literature is saturated with multi-view
autoencoders and deep canonical correlation analyses (DCCA) (Andrew et
al. 2013) that operate as predictive ``black boxes.'' We synthesize deep
multi-view learning with classical statistical guardrails (e.g.,
Tracy-Widom distributions for Parallel Analysis, BIC, and the
One-Standard-Error rule). This forces the deep learning community to
rigorously prove that their discovered multi-modal consensus is
statistically distinguishable from pure noise. While these models
frequently achieve state-of-the-art predictive accuracy, they do so at
the cost of ``Information Masking'' (Yeh et al. 2019), collapsing
distinct clinical inputs into entangled latent spaces that cannot be
reliably audited.

Consequently, the Explainable AI (XAI) community relies heavily on
post-hoc approximation methods (e.g., LIME, SHAP) (Ribeiro et al. 2016;
Lundberg and Lee 2017). However, as argued by Rudin (2019) (Rudin 2019),
these methods are fundamentally flawed for high-stakes decisions; they
are often unstable, unfaithful to the model's true mechanics, and
attempt to approximate feature importance after the information has
already been inextricably mixed. Furthermore, SHAP and LIME suffer from
critical out-of-distribution (OOD) perturbation flaws: by permuting
features independently to compute marginal contributions, they generate
synthetic data points that violate the natural covariance structure of
the biological manifold.

Our most significant contribution is demonstrating that researchers do
not need to sacrifice deep representational capacity to maintain
mathematical exactness. Across all proposed architectures---LEND, NED,
and NEDPP---the framework resolves the Consistency-Interpretability
Tradeoff by enforcing the OLEE. Because the initial encoding step is
always a strict, orthogonal matrix multiplication
(\(\mathbf{X}\mathbf{V}\)) stabilized by NSA-Flow, global feature
importance is analytically exact across the entire taxonomy.
``Auditability by Design'' bypasses the OOD perturbation flaws of
post-hoc XAI entirely; structural counterfactual prescriptions (Wachter
et al. 2017) can be calculated at this linear bottleneck with zero
approximation error. This provides clinicians and computational
biologists with a structural guarantee that a model's latent consensus
traces directly back to specific physical or biological drivers.

Empirical evaluations demonstrate consistent Linear-to-Deep Performance
Parity across the taxonomic spectrum. The architectures perform
comparably in latent consensus recovery, indicating that the linear
orthogonal bottleneck (\(\mathbf{X}\mathbf{V}\)) extracts the primary
structural variance. The subsequent non-linear layers in NED and NEDPP
isolate specific manifold complexities, such as extreme periodicity or
view-specific idiosyncratic noise, without obfuscating the primary
signal. By constraining high-capacity neural networks with strict
Riemannian geometry (NSA-Flow), classical statistical thresholds
(Tracy-Widom, BIC), and enforced linear bottlenecks, the Deep SiMLR
framework enforces Auditability by Design. This paradigm establishes the
methodological rigor necessary to utilize multi-modal integration as an
auditable scientific instrument, fulfilling regulatory prerequisites for
clinical multi-omics.

\section{Mechanical Interpretability}\label{mechanical-interpretability}

A central theme of our work is structural interpretability. Post-hoc
methods like SHAP or LIME are fundamentally limited by providing
approximations of model behavior only after information is entangled
through nonlinear layers.

In contrast, our \textbf{OLEE} ensures that interpretability is a
structural property of the model. We provide a mathematical connection
between global and local interpretability, where the global feature
importance and local patient audits are derived from the exact same
linear operator. Empirical results demonstrate that enforcing
\textbf{Strict Positivity} and \textbf{Parsimonious Sparsity}
(\(q=0.5\)) does not degrade predictive signal; rather, it distills the
representation into a set of additive, non-redundant biomarkers that are
directly actionable for clinicians.

\section{Biomarker Discovery Integrity and
Regularization}\label{biomarker-discovery-integrity-and-regularization}

We establish \textbf{Biomarker Discovery Integrity}, enabled by the
\textbf{NSA-Flow} stiffness. By forcing latent factors to be orthogonal
with a manifold pressure of \(w=0.5\), we ensure that each identified
signature is unique and non-redundant.

Furthermore, we provide formal statistical proof that the OLEE minimizes
the generalization gap (\(\Delta_{\text{gen}}\)). By anchoring deep
manifolds to a strictly linear first layer, we prevent the model from
overfitting to modality-specific noise. LEND consistently maintains
competitive generalization across clinical datasets, validating its use
as a robust tool for small-sample high-dimensional discovery.

However, we note a critical statistical boundary: on datasets with
predominantly linear effects, such as the Diabetes progression cohort,
the classical \textbf{SiMLR} baseline significantly outperforms deep
alternatives (\(p < 10^{-7}\)). This reinforces the principle that deep
models should be deployed where manifold complexity justifies the risk
of overfitting, while linear methods remain the most robust baseline for
low-complexity diagnostic tasks.

\section{The Normalizing Flow Advantage: Exact Bijectivity and Prior
Regularization}\label{the-normalizing-flow-advantage-exact-bijectivity-and-prior-regularization}

To fully understand the superior performance of Flow-SiMLR and
Flow-SiMLR-V compared to standard deep architectures, we must examine
their underlying mathematical design principles. In standard deep
multi-view autoencoders (such as NED and NEDPP), the encoder compresses
high-dimensional inputs to a bottleneck by discarding idiosyncratic
information, and the decoder reconstructs it using standard neural
projections. This lossy process drops modality-specific details.
Normalizing flows bypass this entirely through \textbf{strictly
bijective} (one-to-one and onto) mappings. Flow-SiMLR maps the entire
input space of size \(D_m\) to a latent space of the exact same size
\(D_m\), partitioning it into shared consensus (\(Z_{1:K}\)) and an
implicit, orthogonal private noise partition (\(Z_{K+1:D_m}\)). Because
the mapping is bijective, reconstruction is analytically exact
(\(\mathcal{L}_{MSE} = 0\)), preventing representation collapse.

Furthermore, standard deep models often overfit because their latent
spaces are unconstrained. Normalizing flows resolve this by maximizing
the exact log-likelihood under a standard multivariate Gaussian prior,
regularizing the latent consensus to be statistically stable and
preventing the consensus space from expanding or collapsing. In
\textbf{Flow-SiMLR-V}, we prepend the Stiefel-constrained linear encoder
matrix \(\mathbf{V}_m\) to act as a \textbf{structural information
bottleneck} before the normalizing flow. This linear entry point filters
out batch effects and high-frequency noise prior to the flow, preventing
the flow's non-linear coupling layers from memorizing noise. This
combination of exact bijectivity, implicit shared-private decoupling,
and OLEE Stiefel regularization is the ``secret sauce'' behind
Flow-SiMLR-V's leading performance across synthetic and clinical
benchmarks.

\section{Gating Dynamics and Stability in Normalizing Flow
Spaces}\label{gating-dynamics-and-stability-in-normalizing-flow-spaces}

The introduction of dynamic modality weighting driven by the Modality
Alignment Index (MAI) offers an elegant mechanism to quarantine rogue
noise views and optimize consensus representation. However, in
Normalizing Flow models---especially those pre-pended with linear
projection bottlenecks (like Flow-SiMLR-V)---gating updates can
introduce severe training instabilities.

Because the projection matrices \(\mathbf{V}_m\) and flow parameters are
initialized randomly, representations in the early epochs are highly
noisy. Calculating MAI gating immediately (from epoch 0) creates a
positive feedback loop: the softmax gating function exponentially
amplifies initial random noise differences, driving the weights of valid
clean views to zero. Once zeroed out, these views stop receiving
parameter updates, locking the model into a collapsed state.

We resolve this by implementing a \textbf{Delayed Dynamic Weight Start}
(gating warmup). Pausing gating until the midpoint of training forces
the model to cooperatively align all view coordinate systems first. Once
aligned, MAI gating is activated, smoothly and stably driving rogue
noise views to absolute zero.

Furthermore, our results reveal a key dimensionality-dependent stability
boundary. On high-dimensional datasets (like the BRCA multi-omics
dataset), the redundant and overdetermined feature space allows the
projection matrices \(V\) to stabilize almost immediately, making weight
collapse rare. Conversely, on low-dimensional or mixed synthetic
manifolds, projection coordinates are highly sensitive to initial noise,
making delayed gating a strict mathematical necessity for stable
convergence.

Additionally, we found that pairing unconstrained positive and negative
projections
(\texttt{positivity=\textquotesingle{}either\textquotesingle{}}) is
crucial when training normalizing flows. Clamping weights to be strictly
positive silences negative feature attributions, leading to
reconstruction collapse (producing flat-zero prediction lines). Allowing
unconstrained attributions enables the model to capture the true latent
manifolds and achieves leading downstream clinical ER status
classification accuracy of \textbf{87.27\%} on BRCA.

\section{Geodesic Latent Path Interpolation and Clinical
Counterfactuals}\label{geodesic-latent-path-interpolation-and-clinical-counterfactuals}

By preserving exact mathematical bijectivity, the \textbf{Flow-SiMLR}
model enables a novel class of scientific explanation: \textbf{Geodesic
Latent Path Interpolation}. Because normalizing flows define a
continuous, bijective diffeomorphism between the observational feature
manifold and the joint Gaussian latent space, we can map continuous
trajectories directly in the latent space and project them back to the
input space without encountering the off-manifold artifacts typical of
generative adversarial networks (GANs) or standard autoencoders.

For a patient projected at high clinical risk
\(\mathbf{z}_{\text{start}}\), we compute the shortest geodesic path (a
straight line in the standardized Gaussian latent space) toward a
low-risk target consensus coordinate \(\mathbf{z}_{\text{end}}\):
\[\mathbf{z}(t) = (1 - t)\mathbf{z}_{\text{start}} + t\mathbf{z}_{\text{end}} \quad \text{for} \quad t \in [0, 1]\]
Using the flow's inverse mapping
\(f_m^{-1}([\mathbf{z}(t) \parallel \mathbf{0}])\), we reconstruct the
corresponding physical biomarker trajectory \(\mathbf{x}_m(t)\) in the
input space. This maps the continuous, non-linear progression of
biomarkers required to transition from a diseased to a healthy state,
providing exact counterfactual clinical discovery. Clinicians can
identify which serum variables or vitals must change, and in what
non-linear order, to guide therapy, fulfilling the explainability goals
of precision medicine.

\section{Limitations and Broader
Impacts}\label{limitations-and-broader-impacts}

While Deep SiMLR provides rigorous interpretability, it imposes specific
architectural constraints that define its operational limits. Foremost,
the reliance on the OLEE at the first layer fundamentally limits the
model's capacity to learn intra-modality non-linear feature interactions
directly from the raw input space. We intentionally sacrifice this
early-stage representational capacity to preserve the exact linear audit
trail (\(\mathbf{X}\mathbf{V}\)). Consequently, datasets where the
critical signal relies heavily on complex, nonlinear interactions
between specific scalar features within the same modality may experience
suboptimal feature extraction compared to fully unconstrained deep
networks.

Additionally, the iterative Stiefel manifold projection via NSA-Flow
introduces substantial computational overhead. The Newton-Schulz
iteration requires dense matrix multiplications that scale cubically
with the number of latent dimensions (\(\mathcal{O}(K^3)\)). While
parallel GPU architectures partially mitigate this cost, scaling the
framework to massive latent spaces (\(K > 1000\)) remains
computationally prohibitive and requires careful optimization of
Riemannian manifold operations.

In terms of broader impacts, providing tools with ``Auditability by
Design'' mitigates the risks associated with deploying opaque predictive
models in high-stakes clinical environments. By ensuring that
predictions trace back to physically meaningful, unpermuted biological
drivers, Deep SiMLR prevents the silent accumulation of structural
biases and provides a transparent framework for regulatory scrutiny.
However, the interpretation of the isolated structural drivers still
requires domain expertise to avoid misattributing correlation to
biological causation.

\section{Future Directions}\label{future-directions}

Future methodological extensions will address the computational
constraints of high-dimensional manifold optimization. Specifically,
scaling the NSA-Flow mechanism requires optimizing Riemannian manifold
operations to reduce the \(\mathcal{O}(K^3)\) complexity associated with
iterative orthogonalization. Additionally, replacing classical algebraic
consensus functions with cross-attention consensus layers will allow the
framework to dynamically weight modality contributions at the sample
level, rather than relying on global modality alignment metrics, further
improving robustness in highly heterogeneous clinical populations.

\section{Conclusion}\label{conclusion}

The deep SiMLR framework provides a unified continuum for multimodal
integration. By constraining deep neural networks with the OLEE and
NSA-Flow, we connect the expressive power of deep learning with the
rigorous interpretability of spectral factor analysis.

The \textbf{LEND-ICA-LogCosh} configuration offers researchers a robust
tool for integrating complex biological signals while maintaining a
guaranteed audit trail to physical measurements. This framework ensures
deep learning models function not just as accurate predictors, but as
transparent, auditable instruments for clinical discovery and precision
medicine, echoing the rigorous standardization pioneered by tools like
ANTs (Avants et al. 2014).

\cleardoublepage
\phantomsection
\addcontentsline{toc}{part}{Appendices}
\appendix

\chapter{Multi-omics Clinical Validation
(TCGA-BRCA)}\label{multi-omics-clinical-validation-tcga-brca}

\section{Multi-Omic Integration
Strategy}\label{multi-omic-integration-strategy}

We evaluated the Orthogonal Linear Encoder-Decoder (OLEE) using the
TCGA-BRCA dataset (\(N=549\) samples). The dataset includes three
modalities: * \textbf{RNA-Seq:} 604 features. * \textbf{Copy Number
Variation (CNV):} 860 features. * \textbf{Proteomics (RPPA):} 223
features.

The target variable is Estrogen Receptor (ER) Status (Positive
vs.~Negative).

\section{Performance Results}\label{performance-results}

We used 5-fold cross-validation to compare the linear classification
accuracy (\(Acc_{XV}\)) of the SiMLR baseline against the LEND, NED, and
NEDPP architectures. All models extract a low-dimensional latent space
(\(K \ll D_m\)) from the input modalities to form the linear
classification basis.

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}lc@{}}
\toprule\noalign{}
Model & Accuracy (Mean ± SD) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{SiMLR} & 0.898 ± 0.028 \\
\textbf{Flow-SiMLR} & 0.871 ± 0.011 \\
\textbf{Flow-SiMLR-V (Ours)} & 0.913 ± 0.012 \\
\textbf{NED} & 0.914 ± 0.014 \\
\textbf{NEDPP} & 0.920 ± 0.014 \\
\textbf{LEND} & \textbf{0.922 ± 0.014} \\
\end{longtable}
}

Note that for Flow-SiMLR, since it utilizes a bijective Normalizing Flow
architecture, it does not incorporate the initial linear encoder entry
(OLEE) bottleneck, and classification is evaluated directly on its
learned latent representations (\$). In contrast, the proposed
\textbf{Flow-SiMLR-V} architecture pre-pends a Stiefel-constrained
linear encoder matrix \$, enabling strictly linear classification on the
projected space \$ and achieving full parity with the deep MLP-based
models. Introducing a non-linear decoder establishes an information
bottleneck that enforces cross-modal consensus within the shared latent
representation. This bottleneck filters modality-specific noise,
increasing mean predictive accuracy and reducing variance in the
resulting linear subspace compared to the purely linear SiMLR baseline.

\section{Tri-Modal Feature Discovery}\label{tri-modal-feature-discovery}

The OLEE maintains the structural mapping between the original
high-dimensional feature space and the low-dimensional latent
bottleneck. We extract feature weights directly from the model
parameters. Figure Figure~\ref{fig-brca-trimodal-waterfall} reports the
top 15 weights computed by the LEND architecture across the three
modalities.

\begin{figure}[H]

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{figures/fig_brca_trimodal_waterfall.png}

}

\caption{\label{fig-brca-trimodal-waterfall}\textbf{Tri-Modal Feature
Weights for ER-Status.} LEND identifies markers across modalities.
(Left) RNA-Seq weights for transcription factors. (Center) CNV regional
weights. (Right) Proteomics weights for ER-alpha and GATA3. The
alignment prioritizes markers with cross-modal consistency.}

\end{figure}%

\subsection{Mechanistic Alignment}\label{mechanistic-alignment}

LEND yields an explicit weight matrix mapping input features to the
latent space. Within the proteomics modality, ER-alpha possesses the
highest weight magnitude. This maps to the ESR1 transcript in the
RNA-Seq modality. LEND assigns higher weights to protein-level markers
INPP4B and GATA3 than the linear baseline.

The latent representation captures the covariance structure necessary to
perform ER-positive classification. ESR1 expression separates ER status
({``Comprehensive Molecular Portraits of Human Breast Tumours''} 2012).
GATA3 is co-expressed with ER-alpha in luminal breast cancer (Cohen et
al. 2014; Prat and Parker 2019). INPP4B loss tracks PI3K pathway
activation and covaries with ER status ({``Comprehensive Molecular
Portraits of Human Breast Tumours''} 2012; 2016). By compressing CNV,
RNA, and protein features through an aligned information bottleneck, the
deep architecture recovers these established biological covariates
directly from the parameter weights.

\chapter{Appendix: Operational Implementation and
Complexity}\label{appendix-operational-implementation-and-complexity}

This appendix specifies technical details for the SiMLR framework,
including hyperparameter definitions, computational complexity bounds,
and the optimization protocol.

\section{1. Operational Protocol: The SiMLR Training
Loop}\label{operational-protocol-the-simlr-training-loop}

The training procedure for SiMLR and its deep extensions (LEND, NED,
NEDPP) interleaves neural network backpropagation with manifold
projection.

\subsection{1.1 Training Algorithm}\label{training-algorithm}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{Initialize \{V\_m, theta\_m, phi\_m\}}
\NormalTok{For epoch t }\KeywordTok{in} \FloatTok{1.}\NormalTok{.T:}
    \FloatTok{1.}\NormalTok{ Calculate alpha\_t (Stiefel mixing coefficient)}
       \OperatorTok{{-}}\NormalTok{ alpha\_t }\OperatorTok{=} \BuiltInTok{min}\NormalTok{(}\FloatTok{1.0}\NormalTok{, t }\OperatorTok{/}\NormalTok{ (Total\_Epochs }\OperatorTok{*}\NormalTok{ ramp\_ratio))}
    \FloatTok{2.}\NormalTok{ Forward Pass:}
       \CommentTok{\# Apply OLEE}
\NormalTok{       V\_active }\OperatorTok{=}\NormalTok{ (}\DecValTok{1} \OperatorTok{{-}}\NormalTok{ alpha\_t) }\OperatorTok{*}\NormalTok{ V\_raw }\OperatorTok{+}\NormalTok{ alpha\_t }\OperatorTok{*}\NormalTok{ NewtonSchulz(V\_raw)}
\NormalTok{       Z\_m }\OperatorTok{=}\NormalTok{ Encoder(X\_m, V\_active, theta\_m)}
       
       \CommentTok{\# For NEDPP: Disentangle Shared vs Private}
\NormalTok{       U\_shared, P\_private }\OperatorTok{=}\NormalTok{ Split(Z\_m)}
\NormalTok{       Loss\_disentangle }\OperatorTok{=}\NormalTok{ CovariancePenalty(U\_shared, P\_private)}
       
    \FloatTok{3.}\NormalTok{ Consensus Estimation:}
       \OperatorTok{{-}}\NormalTok{ U\_hat }\OperatorTok{=}\NormalTok{ Average(Z\_1, ..., Z\_M) }\KeywordTok{or}\NormalTok{ NewtonSchulzConsensus(Z\_list)}
    \FloatTok{4.}\NormalTok{ Calculate Total Energy J:}
       \OperatorTok{{-}}\NormalTok{ J }\OperatorTok{=}\NormalTok{ (}\DecValTok{1} \OperatorTok{{-}}\NormalTok{ alpha\_t) }\OperatorTok{*}\NormalTok{ L\_recon }\OperatorTok{+}\NormalTok{ alpha\_t }\OperatorTok{*}\NormalTok{ L\_align }\OperatorTok{+}\NormalTok{ gamma }\OperatorTok{*}\NormalTok{ L\_disentangle}
    \FloatTok{5.}\NormalTok{ Backpropagate gradients to \{V\_raw, theta\_m, phi\_m\}}
    \FloatTok{6.}\NormalTok{ Update weights via Optimizer (Adam }\ControlFlowTok{with}\NormalTok{ weight decay)}
\end{Highlighting}
\end{Shaded}

\section{2. Mathematical Derivations}\label{mathematical-derivations}

\subsection{2.1 Riemannian Updates}\label{riemannian-updates}

We implement Riemannian updates on the Stiefel manifold via projection
onto the tangent space \(\mathcal{T}_{\mathbf{V}} \mathbb{V}_{k,n}\). We
compute the Riemannian gradient \(\text{grad} \mathcal{J}(\mathbf{V})\)
from the Euclidean gradient \(\nabla \mathcal{J}(\mathbf{V})\):
\[ \text{grad} \mathcal{J}(\mathbf{V}) = \nabla \mathcal{J}(\mathbf{V}) - \mathbf{V} \text{sym}(\mathbf{V}^\top \nabla \mathcal{J}(\mathbf{V})) \]

The orthogonal penalty
\(\mathcal{P}(\mathbf{V}) = \frac{1}{4} \| \mathbf{V}^\top \mathbf{V} - \mathbf{I}_k \|_F^2\)
permits a Taylor expansion for a perturbation \(\mathbf{\Delta}\):
\[ \mathcal{P}(\mathbf{V} + \mathbf{\Delta}) \approx \frac{1}{4} \text{Tr}\left( (\mathbf{V}^\top \mathbf{\Delta} + \mathbf{\Delta}^\top \mathbf{V})^2 \right) \]
This penalty evaluates to zero for any \(\mathbf{\Delta}\) strictly
within the tangent space.

\subsection{2.2 Newton-Schulz
Convergence}\label{newton-schulz-convergence}

We enforce orthogonality via the iteration sequence:
\[ \mathbf{Y}_{k+1} = \frac{1}{2} \mathbf{Y}_k (3\mathbf{I} - \mathbf{Y}_k^\top \mathbf{Y}_k) \]
The residual error
\(\mathbf{E}_k = \mathbf{I} - \mathbf{Y}_k^\top \mathbf{Y}_k\) obeys the
relation
\(\mathbf{E}_{k+1} = \frac{3}{4} \mathbf{E}_k^2 + \frac{1}{4} \mathbf{E}_k^3\).
This yields quadratic convergence:
\(\| \mathbf{E}_{k+1} \|_2 < \| \mathbf{E}_k \|_2^2\).

\subsection{2.3 Noise Reduction Law}\label{noise-reduction-law}

Assuming independent noise distributions
\(\boldsymbol{\epsilon}_m \sim \mathcal{N}(\mathbf{0}, \sigma^2 \mathbf{I})\),
the consensus variance scales as:
\[ \text{Var}\left( \frac{1}{M} \sum_{m=1}^M \boldsymbol{\epsilon}_m \right) = \frac{\sigma^2}{M} \]
The corresponding \(100(1-\delta)\%\) confidence interval for the
underlying signal \(\boldsymbol{\mu}\) is bounded by:
\[ \hat{\boldsymbol{\mu}}_{\text{consensus}} \pm z_{\delta/2} \sqrt{\frac{\sigma^2}{M}(1-\rho) + \rho\sigma^2} \]
The covariance term \(\rho\sigma^2\) provides the strict statistical
lower bound for the multi-modal consensus error.

\section{3. Statistical Sensitivity}\label{statistical-sensitivity}

\subsection{\texorpdfstring{3.1 Modality Weights
(\(w\))}{3.1 Modality Weights (w)}}\label{modality-weights-w}

We bound the Statistical Influence Function
\(\mathcal{I}_m = \frac{\partial \mathbf{U}}{\partial w_m}\) by the
spectral gap \((\lambda_1 - \lambda_2)^{-1}\) of the input feature
covariance \(\mathbf{\Sigma}_m\). Consequently, SiMLR operational
sensitivity scales proportionally with the degree of multicollinearity
in the input domain.

\subsection{\texorpdfstring{3.2
\(\alpha\)-Transition}{3.2 \textbackslash alpha-Transition}}\label{alpha-transition}

The mixing parameter \(\alpha\) controls the trade-off between
independent modality reconstruction and cross-modal consensus alignment.
We set the transition point at the epoch where the first derivative of
the consensus variance approaches zero.

\section{4. Hyperparameter Guidance}\label{hyperparameter-guidance}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}
  >{\raggedright\arraybackslash}p{(\linewidth - 6\tabcolsep) * \real{0.2500}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Parameter
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Default
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Range
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Rationale
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{\(\lambda_{\text{sim}}\)} & 1.0 & \([0.1, 10.0]\) & Cross-modal
alignment weighting. \\
\textbf{\(\lambda_{\text{rec}}\)} & 0.5 & \([0.0, 5.0]\) &
Reconstruction priority. \\
\textbf{\(\lambda_{\text{var}}\)} & 1.0 & \([0.5, 2.0]\) & Variance
preservation. \\
\textbf{\(\lambda_{\text{cov}}\)} & 1.0 & \([0.5, 2.0]\) & Latent
de-correlation. \\
\textbf{\(\alpha_{\text{ramp}}\)} & 0.5 * Total Epochs & \([0.2, 0.8]\)
& Stiefel manifold transition duration. \\
\textbf{\(N_{\text{warmup}}\)} & 10 epochs & \([5, 50]\) & Shared-First
schedule for NEDPP. \\
\end{longtable}
}

\section{5. MAI Implementation}\label{mai-implementation}

The Modality Alignment Index (MAI) applies automated weighting to
modalities via a Sigmoid Gate. We configure the MAI parameters as
follows:

\begin{itemize}
\tightlist
\item
  \textbf{Center:} Mean(MAI).
\item
  \textbf{Steepness:} 20.0 (annealed).
\item
  \textbf{Transition\_Epochs:} 20.
\end{itemize}

The SiMLR framework provides 4 available MAI metrics: -
\texttt{procrustes\_r2} - \texttt{procrustes\_r2\_sharp} - \texttt{cca}
- \texttt{rvcoef}

\section{6. Computational Complexity}\label{computational-complexity}

{\def\LTcaptype{none} % do not increment counter
\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}
  >{\raggedright\arraybackslash}p{(\linewidth - 4\tabcolsep) * \real{0.3333}}@{}}
\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Operation
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Complexity
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Scaling Law
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
\textbf{Manifold Projection} & \(\mathcal{O}(D \cdot K^2)\) & Linear in
features (\(D\)), Quadratic in Latents (\(K\)). \\
\textbf{Consensus Estimation} & \(\mathcal{O}(M \cdot K^3)\) & Linear in
modalities (\(M\)), Cubic in Latents (\(K\)). \\
\textbf{Forward/Backward} & \(\mathcal{O}(N \cdot D \cdot K)\) & Linear
in Samples (\(N\)) and features (\(D\)). \\
\textbf{VRAM Consumption} & \(\mathcal{O}(N \cdot K + D \cdot K)\) &
Linear in Samples (\(N\)) and features (\(D\)). \\
\end{longtable}
}

The Newton-Schulz iteration relies exclusively on dense matrix
multiplications, achieving optimal throughput on parallel GPU
architectures.

\section{7. Pre-processing Protocol}\label{pre-processing-protocol}

We require mean-centering and unit-scaling (\(z\)-score normalization)
for all input matrices \(\{\mathbf{X}_m\}\). This normalizes the
alignment energy \(E_{\text{align}}\) independently of the native
measurement scale.

\section{8. System Optimizations}\label{system-optimizations}

\subsection{8.1 Gradient Stability}\label{gradient-stability}

We employ LeakyReLU or GELU activations coupled with Kaiming He
initialization to bound gradient magnitudes and prevent signal decay in
high-dimensional domains.

\subsection{8.2 Learning Rate Schedules}\label{learning-rate-schedules}

We utilize the OneCycleLR scheduler to fuse the warmup and annealing
phases. This accelerates convergence traversing the non-convex
joint-variational objective space.

\subsection{8.3 Data Throughput}\label{data-throughput}

We specify \texttt{pin\_memory=True} and configure
\texttt{num\_workers\ \textgreater{}\ 0} in the PyTorch DataLoader. This
implements asynchronous memory transfer to the GPU, mitigating
host-device I/O latency.

\section{9. Technical Glossary}\label{technical-glossary}

\begin{itemize}
\tightlist
\item
  \textbf{Normalizing Flow}: A family of deep generative models that
  transforms a simple probability distribution (e.g., standard
  multivariate Gaussian) into a complex distribution using a sequence of
  invertible, bijective mappings via the change-of-variables theorem.
\item
  \textbf{Bijective Mapping}: A mathematically exact, one-to-one and
  onto function. In Flow-SiMLR, bijectivity guarantees that the forward
  mapping (encoding) and inverse mapping (decoding) preserve information
  perfectly with zero reconstruction error (\(\mathcal{L}_{MSE} = 0\)).
\item
  \textbf{Affine Coupling Layer}: The core building block of RealNVP
  normalizing flows. It splits the input features into two halves,
  copying one partition directly while scaling and translating the other
  half using arbitrary non-linear neural networks (which do not need to
  be invertible themselves).
\item
  \textbf{OLEE (Only Linear Encoder Entry-point)}: An architectural
  constraint that restricts the entry layer of a deep neural network to
  be an orthogonal linear projection. This forms a structural
  information bottleneck that prevents deep layers from memorizing
  noise.
\item
  \textbf{NSA-Flow (Non-negative Stiefel Approximating Flow)}: A smooth,
  fully differentiable optimization penalty used to constrain the linear
  encoder basis matrix \(\mathbf{V}_m\) to the Stiefel manifold
  (\(\mathbf{V}_m^\top \mathbf{V}_m = \mathbf{I}_K\)) during
  backpropagation, replacing hard SVD projections.
\item
  \textbf{Schur Complement}: A matrix operation used to compute the
  conditional mean and covariance of a partitioned multivariate Gaussian
  distribution in closed form, enabling mathematically valid cross-view
  imputation.
\item
  \textbf{Leave-One-Out (LOO) Topology}: An optimization pathway where
  each view's latent representation is aligned against a consensus
  target computed exclusively from all \emph{other} views, preventing
  the model from learning trivial identity mappings.
\item
  \textbf{Modality Alignment Index (MAI)}: A metric (typically based on
  Procrustes \(R^2\)) that quantifies the alignment fidelity between an
  individual view's latent space and the global consensus.
\item
  \textbf{Spectral Sharpness}: A random-matrix-theory-based metric
  evaluating singular value concentrations to identify and suppress
  isotropic high-dimensional noise, preventing it from corrupting the
  consensus representation.
\item
  \textbf{Classical SiMLR}: Similarity-driven Multi-view Linear
  Reconstruction. Strictly linear baseline architecture assuming
  Euclidean projection of modalities.
\item
  \textbf{LEND}: Linear Encoder, Deep Decoder. Combines OLEE-constrained
  linear encoder with a deep non-linear decoder, balancing
  interpretability and reconstruction fidelity.
\item
  \textbf{NED}: Non-linear Encoder-Decoder. Applies non-linear MLP
  transformations to both encoder (post-OLEE) and decoder, maximizing
  representational capacity.
\item
  \textbf{NEDPP}: Non-linear Encoder-Decoder with Private Partitions.
  Disentangles modality-specific private variance from shared
  cross-modal consensus.
\item
  \textbf{Flow-SiMLR}: Normalizing Flow Similarity-driven Multi-view
  Reconstruction. Integrates bijective normalizing flows with latent
  consensus alignment for information-preserving multi-modal
  integration.
\item
  \textbf{Flow-SiMLR-V}: Flow-SiMLR with a linear projection matrix
  (OLEE) entry point to allow feature attribution while maintaining deep
  flow-based mappings.
\end{itemize}

\chapter{Normalizing Flow SiMR with Linear Encoder Bottleneck
(Flow-SiMLR-V)}\label{normalizing-flow-simr-with-linear-encoder-bottleneck-flow-simlr-v}

\section{Model Formulation}\label{model-formulation}

To resolve the ``Information Masking'' problem inherent in deep
multi-modal normalizing flows, we introduce \textbf{Flow-SiMLR-V}, which
pre-pends a Stiefel-constrained linear encoder matrix \(\mathbf{V}_m\)
to each view's Normalizing Flow. This architecture establishes a strict
globally interpretable information bottleneck at the input entry point
while retaining bijective density mapping and conditional inference on
the consensus latent space. The underlying normalizing flows are
implemented natively in PyTorch, adapting structures from the
Latent-Aligned Multiview Normalizing Flows (LAMNr Flows) open-source
framework
(\href{https://github.com/ntustison/LAMNrFlows}{ntustison/LAMNrFlows}).

\subsection{Mathematical Formulation}\label{mathematical-formulation}

For each input modality \(\mathbf{X}_m \in \mathbb{R}^{N \times D_m}\):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  \textbf{Only Linear Encoder Entry (OLEE) Bottleneck}:
  \[\mathbf{Z}_m = \mathbf{X}_m \mathbf{V}_m, \quad \text{subject to } \mathbf{V}_m^\top \mathbf{V}_m = \mathbf{I}_K\]
  where \(\mathbf{V}_m \in \mathbb{R}^{D_m \times K}\) is regularized
  via Non-negative Stiefel Approximating Flow (NSA-Flow) and sparsity
  quantile thresholding.
\item
  \textbf{Low-Dimensional Bijective Normalizing Flow}:
  \[\mathbf{U}_m = f_{\text{flow}, m}(\mathbf{Z}_m)\] where
  \(f_{\text{flow}, m}: \mathbb{R}^K \to \mathbb{R}^K\) is a bijective
  transform mapping the projected coordinate to the shared latent
  coordinate.
\item
  \textbf{Consensus and Inverse Reconstruction}:
  \[\mathbf{U}_{\text{consensus}} = \text{mixing}(\mathbf{U}_1, \dots, \mathbf{U}_M)\]
  \[\mathbf{X}_m^{\text{recon}} = f_{\text{flow}, m}^{-1}(\mathbf{U}_{\text{consensus}}) \mathbf{V}_m^\top\]
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Performance Visualizations}\label{performance-visualizations}

\subsection{1. Conditional Clinical Imputation (True vs.~Imputed
Serums)}\label{conditional-clinical-imputation-true-vs.-imputed-serums}

Because Flow-SiMLR-V preserves mathematical bijectivity on the
bottleneck space, it enables exact conditional inference. In
Figure~\ref{fig-flow-imputation}, we train Flow-SiMLR-V on the Diabetes
dataset (split into vitals and blood serums) under a 70/30 split. We
then simulate a clinical scenario where the blood serums are entirely
missing, and predict them from vitals using the Schur complement solver.
The scatter plot below shows the relationship between True and Imputed
serum levels for S5 (triglycerides).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{appendix_flow_simlr_v_files/figure-pdf/fig-flow-imputation-output-1.pdf}}

}

\caption{\label{fig-flow-imputation}Conditional Cross-View Imputation
(Diabetes). Scatter plot comparing True vs.~Imputed Serum levels (S5)
generated via the Flow-SiMLR-V Schur complement solver on the test set.}

\end{figure}%

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{2. Exact Patient-Level Attribution Waterfall
(XAI)}\label{exact-patient-level-attribution-waterfall-xai}

Pre-pending the linear encoder matrix \(\mathbf{V}_m\) ensures that the
normalizing flow decoders do not mask individual feature importance. In
Figure~\ref{fig-flow-attribution}, we visualize the exact local feature
contributions for a patient on the Heart Disease dataset, computed
analytically as \(\delta \mathbf{x} = \mathbf{x} \circ \mathbf{V}_m\).

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{appendix_flow_simlr_v_files/figure-pdf/fig-flow-attribution-output-1.pdf}}

}

\caption{\label{fig-flow-attribution}Patient-Level Attribution Auditing.
Individualized waterfall-style bar chart showing exact additive feature
attributions for a selected patient on the Heart Disease dataset using
the Flow-SiMLR-V basis.}

\end{figure}%

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\subsection{3. Geodesic Latent Trajectory \&
Counterfactuals}\label{geodesic-latent-trajectory-counterfactuals}

By tracing a straight-line interpolation in the shared latent space
between a low-risk and high-risk patient and decoding it back to the
feature space, we construct an exact clinical counterfactual trajectory.
In Figure~\ref{fig-flow-geodesic}, we visualize the smooth progression
of Age, BMI, and Blood Pressure (BP) along the latent disease path.

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{appendix_flow_simlr_v_files/figure-pdf/fig-flow-geodesic-output-1.pdf}}

}

\caption{\label{fig-flow-geodesic}Clinical Counterfactual Trajectory.
Biomarker evolution curves decoded along a straight latent geodesic path
between a low-risk patient (coordinate 0.0) and high-risk patient
(coordinate 1.0) on the Diabetes dataset.}

\end{figure}%

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Algorithm for Flow-SiMLR-V with Delayed Gating
Warmup}\label{algorithm-for-flow-simlr-v-with-delayed-gating-warmup}

To stably optimize the joint-variational objective under dynamic
modality weighting without triggering weight collapse, we train the
linear encoders, normalizing flows, and dynamic weights using the
Block-Coordinate Descent (BCD) procedure detailed below.

\subsection{Algorithmic Flow}\label{algorithmic-flow}

For a set of \(M\) data matrices \(\mathbf{X}_1, \dots, \mathbf{X}_M\),
shared latent rank \(K\), and max training epochs \(E\):

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Forward Pass}:

  \begin{itemize}
  \tightlist
  \item
    Project features to low-dimensional space:
    \(\mathbf{Z}_m = \mathbf{X}_m \mathbf{V}_m\) for \(m=1, \dots, M\).
  \item
    Apply normalizing flows:
    \(\mathbf{U}_m = f_{\text{flow}, m}(\mathbf{Z}_m)\) and extract
    shared consensus latents
    \(\mathbf{Z}_{m, \text{shared}} = \mathbf{U}_{m, 1:K}\).
  \item
    Compute shared consensus coordinates using Newton-Schulz or ICA
    mixing:
    \(\mathbf{U}_{\text{consensus}} = \text{mixing}(\mathbf{Z}_{1, \text{shared}}, \dots, \mathbf{Z}_{M, \text{shared}})\).
  \end{itemize}
\item
  \textbf{Delayed Gating (Modality Gating Schedule)}:

  \begin{itemize}
  \tightlist
  \item
    For epoch \(t < T_{\text{delayed}}\): set modality weights uniformly
    \(w_m = 1/M\).
  \item
    For epoch \(t \ge T_{\text{delayed}}\):

    \begin{itemize}
    \tightlist
    \item
      Compute the Leave-One-Out (LOO) consensus target for each view:
      \(\mathbf{U}_{\neq m} = \sum_{j \neq m} w_j \mathbf{Z}_{j, \text{shared}}\).
    \item
      Compute the Modality Alignment Index:
      \(\text{MAI}_m = 1 - \frac{\|\mathbf{Z}_{m, \text{shared}}\mathbf{\Omega} - \mathbf{U}_{\neq m}\|_F^2}{\|\mathbf{U}_{\neq m}\|_F^2}\).
    \item
      Update gating weights:
      \(w_m = (1 - \rho) \cdot \frac{1}{M} + \rho \cdot \text{softmax}(\tau \cdot \text{MAI}_m)\)
      (with exponential ramp-up \(\rho\)).
    \end{itemize}
  \end{itemize}
\item
  \textbf{Loss Computation \& Backpropagation}:

  \begin{itemize}
  \tightlist
  \item
    Compute reconstruction loss:
    \(\mathcal{L}_{\text{MSE}} = \sum_m \|\mathbf{X}_m - \hat{\mathbf{X}}_m\|_F^2\)
    where
    \(\hat{\mathbf{X}}_m = f_{\text{flow}, m}^{-1}([\mathbf{U}_{\text{consensus}} \parallel \mathbf{0}])\mathbf{V}_m^\top\).
  \item
    Compute alignment loss:
    \(\mathcal{L}_{\text{align}} = \sum_m \|\mathbf{Z}_{m, \text{shared}}\mathbf{\Omega} - \mathbf{U}_{\neq m}\|_F^2\).
  \item
    Backpropagate gradients to update linear projections
    \(\mathbf{V}_m\) and flow parameters.
  \item
    Retract \(\mathbf{V}_m\) onto the Stiefel manifold using NSA-Flow
    Newton-Schulz updates.
  \end{itemize}
\end{enumerate}

\begin{center}\rule{0.5\linewidth}{0.5pt}\end{center}

\section{Orthogonality \& Sparsity
Diagnostics}\label{orthogonality-sparsity-diagnostics}

We compute the \textbf{Orthogonality Defect}
(\(\|\mathbf{V}^\top\mathbf{V} - \mathbf{I}\|_F\)) and \textbf{Gini
Sparsity} coefficients of the learned Flow-SiMLR-V basis matrices across
the three clinical datasets to verify structural alignment. The results
confirm that the NSA-Flow retraction successfully enforces
near-orthogonality (defect \(< 0.01\)) and high feature sparsity (Gini
\(> 0.65\)), guaranteeing non-redundant and globally explainable latent
consensus dimensions.

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-2016}
2016. \emph{Cancer Discovery} 6 (11): OF5--5.
\url{https://doi.org/10.1158/2159-8290.cd-rw2016-170}.

\bibitem[\citeproctext]{ref-andrew2013deep}
Andrew, Galen, Raman Arora, Jeff Bilmes, and Karen Livescu. 2013.
{``Deep Canonical Correlation Analysis.''} \emph{International
Conference on Machine Learning}, 1247--55.

\bibitem[\citeproctext]{ref-argelaguet2020mofa}
Argelaguet, Ricard, Damien Arnol, Danila Bredikhin, Olivier Delaneau,
John C Marioni, and Oliver Stegle. 2020. {``MOFA+: A Statistical
Framework for Comprehensive Integration of Multi-Modal Single-Cell
Data.''} \emph{Genome Biology} 21 (1): 1--17.

\bibitem[\citeproctext]{ref-avants2025}
{Avants, Brian B., Nicholas J. Tustison, et al.} 2025. {``Normative
Neurological Health.''} \emph{medRxiv}, ahead of print.
\url{https://doi.org/10.1101/2025.09.27.25336706v2}.

\bibitem[\citeproctext]{ref-avants2021}
Avants, Brian B., Nicholas J. Tustison, and James R. Stone. 2021.
{``SiMLR: Robust Metric Learning for Multi-View Datasets.''}
\emph{Machine Learning in Medicine} 1: 100--115.

\bibitem[\citeproctext]{ref-avants2014ants}
Avants, Brian B, Nicholas J Tustison, Michael Stauffer, Gang Song,
Baohua Wu, and James C Gee. 2014. {``The Insight ToolKit Image
Registration Framework.''} \emph{Frontiers in Neuroinformatics} 8: 44.

\bibitem[\citeproctext]{ref-baik2005phase}
Baik, Jinho, G'erard Ben Arous, and Sandrine P'ech'e. 2005. {``Phase
Transition of the Largest Eigenvalue for Nonnull Complex Sample
Covariance Matrices.''} \emph{The Annals of Probability} 33 (5):
1643--97.

\bibitem[\citeproctext]{ref-bengio2013representation}
Bengio, Yoshua, Aaron Courville, and Pascal Vincent. 2013.
{``Representation Learning: A Review and New Perspectives.''} \emph{IEEE
Transactions on Pattern Analysis and Machine Intelligence} 35 (8):
1798--828.

\bibitem[\citeproctext]{ref-Biswas2025explainable}
Biswas, Dr. Sudarsan. 2025. {``Explainable AI in Healthcare: Enhancing
Trust Through Interpretable Machine Learning Models.''}
\emph{International Journal of Machine Learning, AI \&Amp; Data Science
Evolution}, ahead of print.
\url{https://doi.org/10.63665/ijmlaidse.v1i1.03}.

\bibitem[\citeproctext]{ref-bottou2010large}
Bottou, Léon. 2010. {``Large-Scale Machine Learning with Stochastic
Gradient Descent.''} \emph{Proceedings of COMPSTAT'2010}, 177--86.

\bibitem[\citeproctext]{ref-bousmalis2016domain}
Bousmalis, Konstantinos, George Trigeorgis, Nathan Silberman, Dilip
Krishnan, and Dumitru Erhan. 2016. {``Domain Separation Networks.''}
\emph{Advances in Neural Information Processing Systems} 29.

\bibitem[\citeproctext]{ref-CarlesBou2026achieving}
Carles-Bou, Jose L., and Enrique J. Carmona. 2026. {``Achieving Faithful
Explainability in Feedforward Neural Networks Through Accurately
Computed Feature Attribution.''} \emph{Neural Networks}, ahead of print.
\url{https://doi.org/10.1016/j.neunet.2025.108277}.

\bibitem[\citeproctext]{ref-Chiueh1988learning}
Chiueh, T. D., and R. M. Goodman. 1988. {``Learning Algorithms for
Neural Networks with Ternary Weights.''} \emph{Neural Networks}, ahead
of print. \url{https://doi.org/10.1016/0893-6080(88)90203-1}.

\bibitem[\citeproctext]{ref-Cohen_2014}
Cohen, Helit, Rotem Ben-Hamo, Moriah Gidoni, et al. 2014. {``Shift in
GATA3 Functions, and GATA3 Mutations, Control Progression and Clinical
Presentation in Breast Cancer.''} \emph{Breast Cancer Research} 16 (6).
\url{https://doi.org/10.1186/s13058-014-0464-0}.

\bibitem[\citeproctext]{ref-cohen1973eta}
Cohen, Jacob. 1973. {``Eta-Squared and Partial Eta-Squared in Fixed
Factor ANOVA Designs.''} \emph{Educational and Psychological
Measurement} 33 (1): 107--12.

\bibitem[\citeproctext]{ref-cohen1988statistical}
Cohen, Jacob. 1988. \emph{Statistical Power Analysis for the Behavioral
Sciences}. Routledge.

\bibitem[\citeproctext]{ref-cohen1992power}
Cohen, Jacob. 1992. {``A Power Primer.''} \emph{Psychological Bulletin}
112 (1): 155.

\bibitem[\citeproctext]{ref-2012}
{``Comprehensive Molecular Portraits of Human Breast Tumours.''} 2012.
\emph{Nature} 490 (7418): 61--70.
\url{https://doi.org/10.1038/nature11412}.

\bibitem[\citeproctext]{ref-detrano1989international}
Detrano, Robert, Andras Janosi, William Steinbrunn, et al. 1989.
{``International Application of a New Probability Algorithm for the
Diagnosis of Coronary Artery Disease.''} \emph{The American Journal of
Cardiology} 64 (5): 304--10.

\bibitem[\citeproctext]{ref-dinh2016density}
Dinh, Laurent, Jascha Sohl-Dickstein, and Samy Bengio. 2016. {``Density
Estimation Using Real NVP.''} \emph{arXiv Preprint arXiv:1605.08803}.

\bibitem[\citeproctext]{ref-Doshi_Velez_2018}
Doshi-Velez, Finale, and Been Kim. 2018. {``Considerations for
Evaluation and Generalization in Interpretable Machine Learning.''} In
\emph{Explainable and Interpretable Models in Computer Vision and
Machine Learning}. Springer International Publishing.
\url{https://doi.org/10.1007/978-3-319-98131-4_1}.

\bibitem[\citeproctext]{ref-edelman1998geometry}
Edelman, Alan, Tomés A Arias, and Steven T Smith. 1998. {``The Geometry
of Algorithms with Orthogonality Constraints.''} \emph{SIAM Journal on
Matrix Analysis and Applications} 20 (2): 303--53.

\bibitem[\citeproctext]{ref-efron2004least}
Efron, Bradley, Trevor Hastie, Iain Johnstone, and Robert Tibshirani.
2004. {``Least Angle Regression.''} \emph{The Annals of Statistics} 32
(2): 407--99.

\bibitem[\citeproctext]{ref-El_Hassan_2023}
El-Hassan, Ammar. 2023. {``Machine Learning from Multi-Omics:
Applications and Data Integration.''} In \emph{Machine Learning Methods
for Multi-Omics Data Integration}. Springer International Publishing.
\url{https://doi.org/10.1007/978-3-031-36502-7_2}.

\bibitem[\citeproctext]{ref-goodfellow2016deep}
Goodfellow, Ian, Yoshua Bengio, and Aaron Courville. 2016. \emph{Deep
Learning}. MIT Press.

\bibitem[\citeproctext]{ref-Han_2020}
Han, Xiaochuang, Byron C. Wallace, and Yulia Tsvetkov. 2020.
{``Explaining Black Box Predictions and Unveiling Data Artifacts Through
Influence Functions.''} \emph{Proceedings of the 58th Annual Meeting of
the Association for Computational Linguistics}, 5553--63.
\url{https://doi.org/10.18653/v1/2020.acl-main.492}.

\bibitem[\citeproctext]{ref-hastie2009elements}
Hastie, Trevor, Robert Tibshirani, and Jerome Friedman. 2009. \emph{The
Elements of Statistical Learning: Data Mining, Inference, and
Prediction}. Springer Science \& Business Media.

\bibitem[\citeproctext]{ref-Holmberg_2022}
Holmberg, Lars, Carl Johan Helgstrand, and Niklas Hultin. 2022. {``More
Sanity Checks for~Saliency Maps.''} In \emph{Foundations of Intelligent
Systems}. Springer International Publishing.
\url{https://doi.org/10.1007/978-3-031-16564-1_17}.

\bibitem[\citeproctext]{ref-hornik1989multilayer}
Hornik, Kurt, Maxwell Stinchcombe, and Halbert White. 1989.
{``Multilayer Feedforward Networks Are Universal Approximators.''}
\emph{Neural Networks} 2 (5): 359--66.

\bibitem[\citeproctext]{ref-hotelling1936relations}
Hotelling, Harold. 1936. {``Relations Between Two Sets of Variates.''}
\emph{Biometrika} 28 (3/4): 321. \url{https://doi.org/10.2307/2333955}.

\bibitem[\citeproctext]{ref-kingma2014adam}
Kingma, Diederik P, and Jimmy Ba. 2014. {``Adam: A Method for Stochastic
Optimization.''} \emph{arXiv Preprint arXiv:1412.6980}.

\bibitem[\citeproctext]{ref-Lee_1999}
Lee, Daniel D., and H. Sebastian Seung. 1999. {``Learning the Parts of
Objects by Non-Negative Matrix Factorization.''} \emph{Nature} 401
(6755): 788--91. \url{https://doi.org/10.1038/44565}.

\bibitem[\citeproctext]{ref-Lipton_2018}
Lipton, Zachary C. 2018. {``The Mythos of Model Interpretability: In
Machine Learning, the Concept of Interpretability Is Both Important and
Slippery.''} \emph{Queue} 16 (3): 31--57.
\url{https://doi.org/10.1145/3236386.3241340}.

\bibitem[\citeproctext]{ref-Lundberg_2017}
Lundberg, Scott M, and Su-In Lee. 2017. {``A Unified Approach to
Interpreting Model Predictions.''} \emph{Advances in Neural Information
Processing Systems} 30.

\bibitem[\citeproctext]{ref-Becker2024hyperparameter}
Otávio Becker, Cassiano. 2023. \emph{Hyper-Parameter Optimization for
Manifold Regularization Learning}.
\url{https://doi.org/10.47749/t/unicamp.2013.916883}.

\bibitem[\citeproctext]{ref-pearl2009causality}
Pearl, Judea. 2009. \emph{Causality}. Cambridge university press.

\bibitem[\citeproctext]{ref-Prat_2019}
Prat, A., and J. S. Parker. 2019. {``Standardized Versus Research-Based
PAM50 Intrinsic Subtyping of Breast Cancer.''} \emph{Clinical and
Translational Oncology} 22 (6): 953--55.
\url{https://doi.org/10.1007/s12094-019-02203-x}.

\bibitem[\citeproctext]{ref-Smith2023posthoc}
Radulovic, Nedeljko. 2023. \emph{Post-Hoc Explainable AI for Black Box
Models on Tabular Data}.
\url{https://doi.org/10.70675/622ba75cz4386z48e4z934ez365c407c74d5}.

\bibitem[\citeproctext]{ref-rezende2015variational}
Rezende, Danilo, and Shakir Mohamed. 2015. {``Variational Inference with
Normalizing Flows.''} \emph{International Conference on Machine
Learning}, 1530--38.

\bibitem[\citeproctext]{ref-Ribeiro_2016}
Ribeiro, Marco, Sameer Singh, and Carlos Guestrin. 2016. {``{`Why Should
i Trust You?'}: Explaining the Predictions of Any Classifier.''}
\emph{Proceedings of the 2016 Conference of the North American Chapter
of the Association for Computational Linguistics: Demonstrations},
97--101. \url{https://doi.org/10.18653/v1/n16-3020}.

\bibitem[\citeproctext]{ref-Rudin_2019}
Rudin, Cynthia. 2019. {``Stop Explaining Black Box Machine Learning
Models for High Stakes Decisions and Use Interpretable Models
Instead.''} \emph{Nature Machine Intelligence} 1 (5): 206--15.
\url{https://doi.org/10.1038/s42256-019-0048-x}.

\bibitem[\citeproctext]{ref-Sapkota_2025}
Sapkota, Ram, Bishal Thapaliya, Bhaskar Ray, Pranav Suresh, and Jingyu
Liu. 2025. \emph{Multimodal Brain Growth Patterns: Insights from
Canonical Correlation Analysis and Deep Canonical Correlation Analysis
with Auto-Encoder}. February.
\url{https://doi.org/10.20944/preprints202502.0163.v1}.

\bibitem[\citeproctext]{ref-Sathyanarayanan2023integration}
Sathyanarayanan, Anita. 2023. \emph{Integration of Multi-Omics Data in
Cancer}. \url{https://doi.org/10.5204/thesis.eprints.225924}.

\bibitem[\citeproctext]{ref-Schennach2019independent}
Schennach, Susanne M., and Florian Gunsilius. 2019. \emph{Independent
Nonlinear Component Analysis}.
\url{https://doi.org/10.1920/wp.cem.2019.4619}.

\bibitem[\citeproctext]{ref-stone2024blast}
{Stone, James R., Brian B. Avants, et al.} 2024. {``Effects of Low-Level
Blast Exposure on Structural Brain Networks Analyzed via SiMLR.''}
\emph{Frontiers in Neurology} 15: 123456.

\bibitem[\citeproctext]{ref-stone2020longitudinal}
{Stone, James R, Brian B Avants, et al.} 2020. {``Longitudinal
Structural Magnetic Resonance Imaging of Blast-Induced Mild Traumatic
Brain Injury.''} \emph{Journal of Neurotrauma} 37 (21): 2343--54.

\bibitem[\citeproctext]{ref-stone1974cross}
Stone, Mervyn. 1974. {``Cross-Validatory Choice and Assessment of
Statistical Predictions.''} \emph{Journal of the Royal Statistical
Society: Series B (Methodological)} 36 (2): 111--33.

\bibitem[\citeproctext]{ref-Thakur_2025}
Thakur, Amrita. 2025. {``Strategies for Biomarker Identification and
Validation in Precision Medicine: Microbial Predictors, Data
Integration, Machine Learning, and Clinical Trial Insights.''} In
\emph{Microbiota Profiling for Precision Medicine}. Springer Nature
Singapore. \url{https://doi.org/10.1007/978-981-95-2104-3_9}.

\bibitem[\citeproctext]{ref-tishby2000information}
Tishby, Naftali, Fernando C Pereira, and William Bialek. 2000. {``The
Information Bottleneck Method.''} \emph{arXiv Preprint Physics/0004057}.

\bibitem[\citeproctext]{ref-Wachter_2017}
Wachter, Sandra, Brent Mittelstadt, and Chris Russell. 2017.
{``Counterfactual Explanations Without Opening the Black Box: Automated
Decisions and the GDPR.''} \emph{SSRN Electronic Journal}, ahead of
print. \url{https://doi.org/10.2139/ssrn.3063289}.

\bibitem[\citeproctext]{ref-wasserstein2016asa}
Wasserstein, Ronald L, and Nicole A Lazar. 2016. {``The ASA Statement on
p-Values: Context, Process, and Purpose.''} \emph{The American
Statistician} 70 (2): 129--33.

\bibitem[\citeproctext]{ref-welch1947generalization}
Welch, Bernard L. 1947. {``The Generalization of {`Student's'} Problem
When Several Different Population Variances Are Involved.''}
\emph{Biometrika} 34 (1/2): 28--35.

\bibitem[\citeproctext]{ref-wu2018multimodal}
Wu, Mike, and Noah Goodman. 2018. {``Multimodal Generative Models for
Scalable Weakly-Supervised Learning.''} \emph{Advances in Neural
Information Processing Systems} 31.

\bibitem[\citeproctext]{ref-yeh2019fidelity}
Yeh, Chih-Kuan, Cheng-Yu Hsieh, Arun Suggala, David I Inouye, and
Pradeep K Ravikumar. 2019. {``On the (in)fidelity and Sensitivity of
Explanations.''} \emph{Advances in Neural Information Processing
Systems} 32.

\bibitem[\citeproctext]{ref-Zhao_2011}
Zhao, Weizhong, Huifang Ma, and Ning Li. 2011. {``A New Non-Negative
Matrix Factorization Algorithm with Sparseness Constraints.''}
\emph{2011 International Conference on Machine Learning and
Cybernetics}, 1449--52.
\url{https://doi.org/10.1109/icmlc.2011.6016966}.

\bibitem[\citeproctext]{ref-Zhao_2024}
Zhao, Xingbiao, Enze Chen, Panli Yuan, Limengzi Yuan, and Yuchen Zheng.
2024. \emph{Deep Canonically Correlated Denoising Autoencoders for
Signature Verification Purpose}.
\url{https://doi.org/10.21203/rs.3.rs-4569259/v1}.

\end{CSLReferences}




\end{document}
